#!/bin/bash
#
# Skript zum Übersetzen 
#
# (c) Gunter Mueller   v. 0.1  Januar 2017

export MOCKA=/usr/local/mocka
#export MOCKAM2="-d  $MURUS/m2bin -CcallsMocka"
export MOCKAM2="-d  ../maskern/m2bin "
export MOCKALINK="-lpthread -L/usr/X11R6/lib -lX11"




B=./m2bin
rm -f $B/* # alte Kompilate werden entfernt


# Definition Modules :
for d in SACANF.def   SACEXT2.def  SACEXT4.def  SACEXT6.def  SACEXT8.def   SACPFAC.def  SACROOT.def \
SACEXT1.def  SACEXT3.def  SACEXT5.def  SACEXT7.def  SACMUFAC.def  SACPGCD.def  SACUPFAC.def
do
 echo $d
 m=${d%.def}
 m2 -s $m
done

# Implementation Modules: 
for d in SACANF.mod   SACEXT2.mod  SACEXT4.mod  SACEXT6.mod  SACEXT8.mod   SACPFAC.mod  SACROOT.mod \
SACEXT1.mod  SACEXT3.mod  SACEXT5.mod  SACEXT7.mod  SACMUFAC.mod  SACPGCD.mod  SACUPFAC.mod
do
 echo $d
 m=${d%.mod}
 m2 -c $m
done

