#!/bin/bash
#
# Skript zum Übersetzen 
#
# (c) Gunter Mueller   v. 0.1  Januar 2017

export MOCKA=/usr/local/mocka
#export MOCKAM2="-d  $MURUS/m2bin -CcallsMocka"
export MOCKAM2="-d  ../maskern/m2bin -d ../masarith/m2bin -d ../maspoly/m2bin"
export MOCKALINK="-lpthread -L/usr/X11R6/lib -lX11"




B=./m2bin
rm -f $B/* # alte Kompilate werden entfernt


# Definition Modules :
for d in GSYMFUIN.def  GSYMINP.def  LINALGRN.def  SACLDIO.def  SYMMFU.def   SYZGB.def   SYZMAIN.def \
GSYMFURN.def  LINALGI.def  NOETHER.def   SUBST.def    SYZFUNC.def  SYZHLP.def  TIPRNGB.def
do
 echo $d
 m=${d%.def}
 m2 -s $m
done

# Implementation Modules: 
for d in  GSYMFUIN.mod  GSYMINP.mod  LINALGRN.mod  SACLDIO.mod  SYMMFU.mod   SYZGB.mod   SYZMAIN.mod \
GSYMFURN.mod  LINALGI.mod  NOETHER.mod   SUBST.mod    SYZFUNC.mod  SYZHLP.mod  TIPRNGB.mod
do
 echo $d
 m=${d%.mod}
 m2 -c $m
done

