#define DEFINITION_ADEXTRA

#ifndef DEFINITION_MASSTOR
#include "MASSTOR.h"
#endif

extern CHAR ADEXTRA_rcsid[];
extern CHAR ADEXTRA_copyright[];
extern MASSTOR_LIST ADEXTRA_ADPCP ARGS((MASSTOR_LIST C_1_A));
extern MASSTOR_LIST ADEXTRA_ADPNEG ARGS((MASSTOR_LIST C_2_A));
extern MASSTOR_LIST ADEXTRA_ADPIQ ARGS((MASSTOR_LIST C_3_A, MASSTOR_LIST b));
extern BOOLEAN ADEXTRA_ADLGinH ARGS((MASSTOR_LIST H, MASSTOR_LIST G));
extern BOOLEAN ADEXTRA_ADLGeqH ARGS((MASSTOR_LIST H, MASSTOR_LIST G));
extern BOOLEAN ADEXTRA_ADPFeqG ARGS((MASSTOR_LIST F, MASSTOR_LIST G));
extern MASSTOR_LIST ADEXTRA_ADIredG ARGS((MASSTOR_LIST I, MASSTOR_LIST G));
extern MASSTOR_LIST ADEXTRA_ADGJredI ARGS((MASSTOR_LIST G, MASSTOR_LIST I));
extern MASSTOR_LIST ADEXTRA_IBeqGB ARGS((MASSTOR_LIST G, MASSTOR_LIST I));
extern void BEGIN_ADEXTRA();
