#define DEFINITION_CGBAPPL

#ifndef DEFINITION_MASSTOR
#include "MASSTOR.h"
#endif

extern CHAR CGBAPPL_rcsid[];
extern CHAR CGBAPPL_copyright[];
extern void CGBAPPL_GTEST ARGS((MASSTOR_LIST C, MASSTOR_LIST P, MASSTOR_LIST *C0, MASSTOR_LIST *C1));
extern void CGBAPPL_GBHELP ARGS((MASSTOR_LIST COND, MASSTOR_LIST PPAIRS, MASSTOR_LIST P, MASSTOR_LIST *C0, MASSTOR_LIST *C1));
extern void CGBAPPL_NSET ARGS((MASSTOR_LIST NN0, MASSTOR_LIST NN1, MASSTOR_LIST CC0, MASSTOR_LIST CC1, MASSTOR_LIST *C0, MASSTOR_LIST *C1));
extern void CGBAPPL_WRTEST ARGS((MASSTOR_LIST C, MASSTOR_LIST PP, MASSTOR_LIST CGB0, MASSTOR_LIST CGB1));
extern MASSTOR_LIST CGBAPPL_CPART ARGS((MASSTOR_LIST COND, MASSTOR_LIST CONDS));
extern void CGBAPPL_CGBQUA ARGS((MASSTOR_LIST PP));
extern void CGBAPPL_MCOEF ARGS((MASSTOR_LIST PCO, MASSTOR_LIST *COEFLI, MASSTOR_LIST *COEF, MASSTOR_LIST *TL));
extern void CGBAPPL_NFEXEC ARGS((MASSTOR_LIST C, MASSTOR_LIST PPS, MASSTOR_LIST PP, MASSTOR_LIST *NOUT));
extern void CGBAPPL_WRQFN0 ARGS((MASSTOR_LIST N0));
extern MASSTOR_LIST CGBAPPL_DIMEXE ARGS((MASSTOR_LIST GS, MASSTOR_LIST V));
extern MASSTOR_LIST CGBAPPL_INTDIM ARGS((MASSTOR_LIST V, MASSTOR_LIST PP));
extern void CGBAPPL_WRDIMS ARGS((MASSTOR_LIST DIML));
extern void CGBAPPL_WRCONJ ARGS((MASSTOR_LIST CONDS));
extern void BEGIN_CGBAPPL();
