#define DEFINITION_CGBFUNC

#ifndef DEFINITION_MASSTOR
#include "MASSTOR.h"
#endif

extern CHAR CGBFUNC_rcsid[];
extern CHAR CGBFUNC_copyright[];
extern void CGBFUNC_WRCOL ARGS((MASSTOR_LIST COL, MASSTOR_LIST POL));
extern void CGBFUNC_WRTERM ARGS((MASSTOR_LIST TERM, MASSTOR_LIST V));
extern void CGBFUNC_DWRIT ARGS((MASSTOR_LIST DE));
extern MASSTOR_LIST CGBFUNC_CGBCOL ARGS((MASSTOR_LIST COND, MASSTOR_LIST PL));
extern void CGBFUNC_DCLWR ARGS((MASSTOR_LIST PL, MASSTOR_LIST B));
extern MASSTOR_LIST CGBFUNC_FINDCP ARGS((MASSTOR_LIST TTERM, MASSTOR_LIST WHITE));
extern MASSTOR_LIST CGBFUNC_FINDBC ARGS((MASSTOR_LIST RE, MASSTOR_LIST POL));
extern MASSTOR_LIST CGBFUNC_FINDRM ARGS((MASSTOR_LIST RE, MASSTOR_LIST POL));
extern MASSTOR_LIST CGBFUNC_CGBFRM ARGS((MASSTOR_LIST CGBL));
extern MASSTOR_LIST CGBFUNC_MKPOL ARGS((MASSTOR_LIST PCO));
extern MASSTOR_LIST CGBFUNC_GREPOL ARGS((MASSTOR_LIST PL));
extern MASSTOR_LIST CGBFUNC_WMEMB ARGS((MASSTOR_LIST TTERM, MASSTOR_LIST WHITE));
extern MASSTOR_LIST CGBFUNC_EQPLCL ARGS((MASSTOR_LIST ALIST, MASSTOR_LIST BLIST));
extern MASSTOR_LIST CGBFUNC_CGBLM ARGS((MASSTOR_LIST L1, MASSTOR_LIST L2));
extern MASSTOR_LIST CGBFUNC_CGBLPM ARGS((MASSTOR_LIST C_1_A));
extern MASSTOR_LIST CGBFUNC_ADDCON ARGS((MASSTOR_LIST COEFL, MASSTOR_LIST COND));
extern MASSTOR_LIST CGBFUNC_INICOL ARGS((MASSTOR_LIST COND, MASSTOR_LIST PI));
extern MASSTOR_LIST CGBFUNC_SETCOL ARGS((MASSTOR_LIST COND, MASSTOR_LIST COL));
extern MASSTOR_LIST CGBFUNC_REDSRT ARGS((MASSTOR_LIST RALT, MASSTOR_LIST RNEU));
extern MASSTOR_LIST CGBFUNC_TESTHT ARGS((MASSTOR_LIST COL));
extern void CGBFUNC_DETPOL ARGS((MASSTOR_LIST GA, MASSTOR_LIST PI, MASSTOR_LIST COL, MASSTOR_LIST *DLIST, MASSTOR_LIST *CLIST));
extern void CGBFUNC_DET ARGS((MASSTOR_LIST CONDS, MASSTOR_LIST P, MASSTOR_LIST *DLIST, MASSTOR_LIST *PPL));
extern MASSTOR_LIST CGBFUNC_VERIFY ARGS((MASSTOR_LIST D, MASSTOR_LIST CLIST));
extern MASSTOR_LIST CGBFUNC_AINB ARGS((MASSTOR_LIST ALIST, MASSTOR_LIST BLIST));
extern void BEGIN_CGBFUNC();
