#define DEFINITION_CGBMAIN

#ifndef DEFINITION_MASSTOR
#include "MASSTOR.h"
#endif

extern CHAR CGBMAIN_rcsid[];
extern CHAR CGBMAIN_copyright[];
extern MASSTOR_LIST CGBMAIN_CDINIT ARGS((MASSTOR_LIST CD));
extern MASSTOR_LIST CGBMAIN_GSYS ARGS((MASSTOR_LIST CDP));
extern MASSTOR_LIST CGBMAIN_GSYSF ARGS((MASSTOR_LIST CDP));
extern MASSTOR_LIST CGBMAIN_GSYSDIM ARGS((MASSTOR_LIST GS));
extern MASSTOR_LIST CGBMAIN_DIMIS ARGS((MASSTOR_LIST PL, MASSTOR_LIST VL, MASSTOR_LIST *MAXVL));
extern MASSTOR_LIST CGBMAIN_GSYSRED ARGS((MASSTOR_LIST GS));
extern MASSTOR_LIST CGBMAIN_CGBFGSYS ARGS((MASSTOR_LIST S));
extern MASSTOR_LIST CGBMAIN_CGBGLOBRED ARGS((MASSTOR_LIST CGB));
extern void CGBMAIN_CGBQFWRITE ARGS((MASSTOR_LIST CGB));
extern MASSTOR_LIST CGBMAIN_CGBQFF ARGS((MASSTOR_LIST CGB));
extern void CGBMAIN_CGBIN ARGS(());
extern void CGBMAIN_CGBOUT ARGS((MASSTOR_LIST AC));
extern MASSTOR_LIST CGBMAIN_DVREAD ARGS(());
extern MASSTOR_LIST CGBMAIN_CONINI ARGS((MASSTOR_LIST VD));
extern void CGBMAIN_CONDRD ARGS((MASSTOR_LIST V, MASSTOR_LIST D, MASSTOR_LIST B, MASSTOR_LIST DALT, MASSTOR_LIST *DNEU));
extern MASSTOR_LIST CGBMAIN_UPDCAS ARGS((MASSTOR_LIST ALIST, MASSTOR_LIST DALT, MASSTOR_LIST B));
extern MASSTOR_LIST CGBMAIN_CCOVER ARGS((MASSTOR_LIST CONS));
extern MASSTOR_LIST CGBMAIN_SCOV ARGS((MASSTOR_LIST CONDA, MASSTOR_LIST CONS, MASSTOR_LIST B));
extern void CGBMAIN_CHDOM ARGS((MASSTOR_LIST CONDS, MASSTOR_LIST PPS, MASSTOR_LIST *CONS, MASSTOR_LIST *PP));
extern MASSTOR_LIST CGBMAIN_EXECRD ARGS(());
extern void CGBMAIN_SEENR ARGS((MASSTOR_LIST AC, MASSTOR_LIST *NR));
extern void CGBMAIN_WRTITL ARGS((MASSTOR_LIST NR));
extern void CGBMAIN_WRGBS ARGS((MASSTOR_LIST PLS));
extern void CGBMAIN_WRCGB ARGS((MASSTOR_LIST CGB, MASSTOR_LIST I));
extern void CGBMAIN_WRRCGB ARGS((MASSTOR_LIST CGB, MASSTOR_LIST I));
extern void CGBMAIN_GGREEN ARGS((MASSTOR_LIST GS));
extern void CGBMAIN_NWRIT0 ARGS((MASSTOR_LIST N));
extern void CGBMAIN_NWRIT1 ARGS((MASSTOR_LIST N));
extern void CGBMAIN_WPAIRS ARGS((MASSTOR_LIST PS));
extern void CGBMAIN_WPLIST ARGS((MASSTOR_LIST PL));
extern void CGBMAIN_NFWRIT ARGS((MASSTOR_LIST NOUT));
extern void BEGIN_CGBMAIN();
