#define DEFINITION_CGBSYS

#ifndef DEFINITION_MASSTOR
#include "MASSTOR.h"
#endif

extern CHAR CGBSYS_rcsid[];
extern CHAR CGBSYS_copyright[];
extern void CGBSYS_GRED ARGS((MASSTOR_LIST COND, MASSTOR_LIST PCO, MASSTOR_LIST PCI, MASSTOR_LIST RE, MASSTOR_LIST *RCO, MASSTOR_LIST *HA));
extern void CGBSYS_GBDIFF ARGS((MASSTOR_LIST COND, MASSTOR_LIST C_1_A, MASSTOR_LIST ACOLS, MASSTOR_LIST B, MASSTOR_LIST BCOLS, MASSTOR_LIST *C, MASSTOR_LIST *CCOLS));
extern MASSTOR_LIST CGBSYS_COLPRD ARGS((MASSTOR_LIST COL1, MASSTOR_LIST TTERM));
extern MASSTOR_LIST CGBSYS_CMULT ARGS((MASSTOR_LIST ONECL, MASSTOR_LIST TTERM, MASSTOR_LIST B));
extern MASSTOR_LIST CGBSYS_WHSRT ARGS((MASSTOR_LIST COL, MASSTOR_LIST TTERM, MASSTOR_LIST ALIST));
extern MASSTOR_LIST CGBSYS_WUPD ARGS((MASSTOR_LIST ALIST, MASSTOR_LIST BLIST));
extern void CGBSYS_COLDIF ARGS((MASSTOR_LIST T, MASSTOR_LIST ACOLS, MASSTOR_LIST COLR, MASSTOR_LIST COLW, MASSTOR_LIST *CRED, MASSTOR_LIST *CWHITE));
extern void CGBSYS_KEYCOL ARGS((MASSTOR_LIST EL, MASSTOR_LIST ACOLS, MASSTOR_LIST *KEY, MASSTOR_LIST *ALIST));
extern void CGBSYS_MKACOL ARGS((MASSTOR_LIST ALIST, MASSTOR_LIST EL, MASSTOR_LIST COLR, MASSTOR_LIST COLW, MASSTOR_LIST *CRED, MASSTOR_LIST *CWHITE));
extern void CGBSYS_MKCOL ARGS((MASSTOR_LIST COND, MASSTOR_LIST CA, MASSTOR_LIST CE, MASSTOR_LIST COLR, MASSTOR_LIST COLW, MASSTOR_LIST *CRED, MASSTOR_LIST *CWHITE));
extern void CGBSYS_FINCOL ARGS((MASSTOR_LIST APP, MASSTOR_LIST ACOLS, MASSTOR_LIST COLR, MASSTOR_LIST COLW, MASSTOR_LIST *CRED, MASSTOR_LIST *CWHITE));
extern void CGBSYS_NFORM ARGS((MASSTOR_LIST GA, MASSTOR_LIST FCO, MASSTOR_LIST P, MASSTOR_LIST *N0, MASSTOR_LIST *N1));
extern void CGBSYS_NFTOP ARGS((MASSTOR_LIST GA, MASSTOR_LIST FCO, MASSTOR_LIST P, MASSTOR_LIST *N0, MASSTOR_LIST *N1));
extern void CGBSYS_FINDPI ARGS((MASSTOR_LIST PCO, MASSTOR_LIST P, MASSTOR_LIST *PCI, MASSTOR_LIST *RE));
extern void CGBSYS_FINDPITOP ARGS((MASSTOR_LIST PCO, MASSTOR_LIST P, MASSTOR_LIST *PCI, MASSTOR_LIST *RE));
extern MASSTOR_LIST CGBSYS_SPOL ARGS((MASSTOR_LIST COND, MASSTOR_LIST HA, MASSTOR_LIST HB));
extern MASSTOR_LIST CGBSYS_GBSYS ARGS((MASSTOR_LIST CNDS, MASSTOR_LIST P));
extern MASSTOR_LIST CGBSYS_GBSYSF ARGS((MASSTOR_LIST CNDS, MASSTOR_LIST P));
extern void CGBSYS_VRNORM ARGS((MASSTOR_LIST COND, MASSTOR_LIST PP, MASSTOR_LIST N0, MASSTOR_LIST N1, MASSTOR_LIST PPAIRS, MASSTOR_LIST *P, MASSTOR_LIST *PAIRS, MASSTOR_LIST *PAIRSL, MASSTOR_LIST *GSYS));
extern MASSTOR_LIST CGBSYS_CHDEGL ARGS((MASSTOR_LIST PLIST));
extern void CGBSYS_MKN1 ARGS((MASSTOR_LIST NN1, MASSTOR_LIST P, MASSTOR_LIST PAIRS, MASSTOR_LIST *PPLIST, MASSTOR_LIST *GSYS));
extern void CGBSYS_MKN0 ARGS((MASSTOR_LIST NN0, MASSTOR_LIST P, MASSTOR_LIST PAIRS, MASSTOR_LIST *PPLIST));
extern void CGBSYS_GSYSN0 ARGS((MASSTOR_LIST NN0, MASSTOR_LIST P, MASSTOR_LIST *GSYS));
extern MASSTOR_LIST CGBSYS_MINPP ARGS((MASSTOR_LIST PP, MASSTOR_LIST PCO));
extern MASSTOR_LIST CGBSYS_UPDPP ARGS((MASSTOR_LIST COND, MASSTOR_LIST P));
extern MASSTOR_LIST CGBSYS_GBUPD ARGS((MASSTOR_LIST COND, MASSTOR_LIST P, MASSTOR_LIST GBSYS));
extern MASSTOR_LIST CGBSYS_MKPAIR ARGS((MASSTOR_LIST PP));
extern MASSTOR_LIST CGBSYS_PRSCOP ARGS((MASSTOR_LIST PAIRS));
extern MASSTOR_LIST CGBSYS_MKNEWP ARGS((MASSTOR_LIST P, MASSTOR_LIST POL, MASSTOR_LIST PRS));
extern void CGBSYS_MKCGB ARGS((MASSTOR_LIST PL, MASSTOR_LIST *X, MASSTOR_LIST *I));
extern MASSTOR_LIST CGBSYS_ADDCGB ARGS((MASSTOR_LIST PLIST, MASSTOR_LIST P));
extern MASSTOR_LIST CGBSYS_GSRED ARGS((MASSTOR_LIST GS));
extern MASSTOR_LIST CGBSYS_REDUCT ARGS((MASSTOR_LIST PELEM));
extern MASSTOR_LIST CGBSYS_REXTP ARGS((MASSTOR_LIST P));
extern void CGBSYS_RDNORM ARGS((MASSTOR_LIST COND, MASSTOR_LIST FCO, MASSTOR_LIST P, MASSTOR_LIST *NCO));
extern void CGBSYS_REFIND ARGS((MASSTOR_LIST PCO, MASSTOR_LIST P, MASSTOR_LIST *PLI, MASSTOR_LIST *RE));
extern MASSTOR_LIST CGBSYS_RMGRT ARGS((MASSTOR_LIST COND, MASSTOR_LIST PP));
extern MASSTOR_LIST CGBSYS_GLOBRE ARGS((MASSTOR_LIST COND, MASSTOR_LIST P));
extern MASSTOR_LIST CGBSYS_GLEXTP ARGS((MASSTOR_LIST P));
extern void BEGIN_CGBSYS();
