#define DEFINITION_DIPC

#ifndef DEFINITION_MASSTOR
#include "MASSTOR.h"
#endif

#define DIPC_LEX	1
#define DIPC_INVLEX	2
#define DIPC_GRLEX	3
#define DIPC_IGRLEX	4
#define DIPC_REVLEX	5
#define DIPC_REVILEX	6
#define DIPC_REVTDEG	7
#define DIPC_REVITDG	8
extern MASSTOR_LIST DIPC_EVORD;
extern MASSTOR_LIST DIPC_VALIS;
extern CHAR DIPC_rcsid[];
extern CHAR DIPC_copyright[];
extern void DIPC_BACKUB ARGS(());
extern MASSTOR_LIST DIPC_CLIN ARGS(());
extern void DIPC_DILBSO ARGS((MASSTOR_LIST C_1_A));
extern MASSTOR_LIST DIPC_DILFPL ARGS((MASSTOR_LIST RL, MASSTOR_LIST C_2_A));
extern MASSTOR_LIST DIPC_DILPERM ARGS((MASSTOR_LIST dil, MASSTOR_LIST perm));
extern void DIPC_DIPADM ARGS((MASSTOR_LIST C_3_A, MASSTOR_LIST *EL, MASSTOR_LIST *FL, MASSTOR_LIST *BL, MASSTOR_LIST *B));
extern void DIPC_DIPADS ARGS((MASSTOR_LIST C_4_A, MASSTOR_LIST IL, MASSTOR_LIST SL, MASSTOR_LIST *EL, MASSTOR_LIST *FL, MASSTOR_LIST *BL, MASSTOR_LIST *B));
extern void DIPC_DIPADV ARGS((MASSTOR_LIST C_5_A, MASSTOR_LIST IL, MASSTOR_LIST *EL, MASSTOR_LIST *FL, MASSTOR_LIST *BL, MASSTOR_LIST *B));
extern void DIPC_DIPBSO ARGS((MASSTOR_LIST C_6_A));
extern MASSTOR_LIST DIPC_DIPCMP ARGS((MASSTOR_LIST EL, MASSTOR_LIST C_7_A));
extern MASSTOR_LIST DIPC_DIPDEG ARGS((MASSTOR_LIST C_8_A));
extern MASSTOR_LIST DIPC_DIPDPV ARGS((MASSTOR_LIST C_9_A, MASSTOR_LIST SL, MASSTOR_LIST QL));
extern MASSTOR_LIST DIPC_DIPERM ARGS((MASSTOR_LIST C_10_A, MASSTOR_LIST P));
extern MASSTOR_LIST DIPC_DIPEVL ARGS((MASSTOR_LIST C_11_A));
extern MASSTOR_LIST DIPC_DIPEVP ARGS((MASSTOR_LIST C_12_A, MASSTOR_LIST EL));
extern MASSTOR_LIST DIPC_DIPEXC ARGS((MASSTOR_LIST C_13_A, MASSTOR_LIST ILP, MASSTOR_LIST JLP));
extern MASSTOR_LIST DIPC_DIPFMO ARGS((MASSTOR_LIST AL, MASSTOR_LIST EL));
extern MASSTOR_LIST DIPC_DIPFP ARGS((MASSTOR_LIST RL, MASSTOR_LIST C_14_A));
extern MASSTOR_LIST DIPC_DIPINV ARGS((MASSTOR_LIST C_15_A, MASSTOR_LIST JL, MASSTOR_LIST KL));
extern MASSTOR_LIST DIPC_DIPLBC ARGS((MASSTOR_LIST C_16_A));
extern MASSTOR_LIST DIPC_DIPLDC ARGS((MASSTOR_LIST C_17_A));
extern MASSTOR_LIST DIPC_DIPLM ARGS((MASSTOR_LIST L1, MASSTOR_LIST L2));
extern MASSTOR_LIST DIPC_DIPLPM ARGS((MASSTOR_LIST C_18_A));
extern void DIPC_DIPLRS ARGS((MASSTOR_LIST C_19_A));
extern void DIPC_DIPMAD ARGS((MASSTOR_LIST C_20_A, MASSTOR_LIST *AL, MASSTOR_LIST *EL, MASSTOR_LIST *AP));
extern MASSTOR_LIST DIPC_DIPMCP ARGS((MASSTOR_LIST AL, MASSTOR_LIST EL, MASSTOR_LIST C_21_A));
extern MASSTOR_LIST DIPC_DIPMPM ARGS((MASSTOR_LIST C_22_A, MASSTOR_LIST PL));
extern MASSTOR_LIST DIPC_DIPMPV ARGS((MASSTOR_LIST C_23_A, MASSTOR_LIST SL, MASSTOR_LIST PL));
extern MASSTOR_LIST DIPC_DIPMRD ARGS((MASSTOR_LIST C_24_A));
extern void DIPC_DIPMST ARGS((MASSTOR_LIST C_25_A, MASSTOR_LIST AL, MASSTOR_LIST EL));
extern MASSTOR_LIST DIPC_DIPNBC ARGS((MASSTOR_LIST C_26_A));
extern MASSTOR_LIST DIPC_DIPNOV ARGS((MASSTOR_LIST C_27_A));
extern MASSTOR_LIST DIPC_DIPRED ARGS((MASSTOR_LIST C_28_A));
extern MASSTOR_LIST DIPC_DIPTBC ARGS((MASSTOR_LIST C_29_A));
extern MASSTOR_LIST DIPC_DIPTCF ARGS((MASSTOR_LIST C_30_A));
extern MASSTOR_LIST DIPC_DIPTCS ARGS((MASSTOR_LIST C_31_A, MASSTOR_LIST IL));
extern MASSTOR_LIST DIPC_DIPTDG ARGS((MASSTOR_LIST C_32_A));
extern MASSTOR_LIST DIPC_DIPUNT ARGS((MASSTOR_LIST C_33_A));
extern MASSTOR_LIST DIPC_DIPUV ARGS((MASSTOR_LIST C_34_A));
extern MASSTOR_LIST DIPC_EPREAD ARGS(());
extern void DIPC_EVCADD ARGS((MASSTOR_LIST U, MASSTOR_LIST IL, MASSTOR_LIST EL, MASSTOR_LIST *V, MASSTOR_LIST *FL));
extern MASSTOR_LIST DIPC_EVCOMP ARGS((MASSTOR_LIST U, MASSTOR_LIST V));
extern void DIPC_EVCSUB ARGS((MASSTOR_LIST U, MASSTOR_LIST IL, MASSTOR_LIST EL, MASSTOR_LIST *V, MASSTOR_LIST *FL));
extern void DIPC_EVDEL ARGS((MASSTOR_LIST U, MASSTOR_LIST IL, MASSTOR_LIST *V, MASSTOR_LIST *EL));
extern void DIPC_EVDER ARGS((MASSTOR_LIST U, MASSTOR_LIST IL, MASSTOR_LIST EL, MASSTOR_LIST *V, MASSTOR_LIST *FL));
extern void DIPC_EVDFSI ARGS((MASSTOR_LIST U, MASSTOR_LIST V, MASSTOR_LIST *W, MASSTOR_LIST *SL));
extern MASSTOR_LIST DIPC_EVDIF ARGS((MASSTOR_LIST U, MASSTOR_LIST V));
extern MASSTOR_LIST DIPC_EVDOV ARGS((MASSTOR_LIST U));
extern MASSTOR_LIST DIPC_EVEXC ARGS((MASSTOR_LIST U, MASSTOR_LIST IL, MASSTOR_LIST JL));
extern MASSTOR_LIST DIPC_EVIGLC ARGS((MASSTOR_LIST U, MASSTOR_LIST V));
extern MASSTOR_LIST DIPC_EVILCI ARGS((MASSTOR_LIST U, MASSTOR_LIST V));
extern MASSTOR_LIST DIPC_EVILCP ARGS((MASSTOR_LIST U, MASSTOR_LIST V));
extern MASSTOR_LIST DIPC_EVITDC ARGS((MASSTOR_LIST U, MASSTOR_LIST V));
extern MASSTOR_LIST DIPC_EVLFCP ARGS((MASSTOR_LIST L, MASSTOR_LIST U, MASSTOR_LIST V));
extern MASSTOR_LIST DIPC_EVLCM ARGS((MASSTOR_LIST U, MASSTOR_LIST V));
extern MASSTOR_LIST DIPC_EVMT ARGS((MASSTOR_LIST U, MASSTOR_LIST V));
extern MASSTOR_LIST DIPC_EVNNZE ARGS((MASSTOR_LIST U));
extern void DIPC_EVOWRITE ARGS((MASSTOR_LIST EVO));
extern void DIPC_EvordWrite ARGS(());
extern MASSTOR_LIST DIPC_EVRAND ARGS((MASSTOR_LIST RL, MASSTOR_LIST KL));
extern MASSTOR_LIST DIPC_EVRASP ARGS((MASSTOR_LIST RL, MASSTOR_LIST KL, MASSTOR_LIST QL));
extern MASSTOR_LIST DIPC_EVSIGN ARGS((MASSTOR_LIST U));
extern void DIPC_EVSU ARGS((MASSTOR_LIST U, MASSTOR_LIST IL, MASSTOR_LIST FL, MASSTOR_LIST *V, MASSTOR_LIST *EL));
extern MASSTOR_LIST DIPC_EVSUM ARGS((MASSTOR_LIST U, MASSTOR_LIST V));
extern MASSTOR_LIST DIPC_EVTDEG ARGS((MASSTOR_LIST U));
extern MASSTOR_LIST DIPC_PBCLI ARGS((MASSTOR_LIST RL, MASSTOR_LIST C_35_A));
extern void DIPC_PFDIP ARGS((MASSTOR_LIST C_36_A, MASSTOR_LIST *RL, MASSTOR_LIST *B));
extern void DIPC_PLFDIL ARGS((MASSTOR_LIST C_37_A, MASSTOR_LIST *RL, MASSTOR_LIST *B));
extern MASSTOR_LIST DIPC_PMPV ARGS((MASSTOR_LIST RL, MASSTOR_LIST C_38_A, MASSTOR_LIST IL, MASSTOR_LIST NL));
extern MASSTOR_LIST DIPC_PPERMV ARGS((MASSTOR_LIST RL, MASSTOR_LIST C_39_A, MASSTOR_LIST P));
extern MASSTOR_LIST DIPC_STVL ARGS((MASSTOR_LIST RL));
extern MASSTOR_LIST DIPC_DIP2AD ARGS((MASSTOR_LIST P, MASSTOR_LIST d, MASSTOR_LIST rest));
extern MASSTOR_LIST DIPC_AD2DIP ARGS((MASSTOR_LIST P));
extern void BEGIN_DIPC();
