#define DEFINITION_DIPDEC0

#ifndef DEFINITION_MASSTOR
#include "MASSTOR.h"
#endif

extern CHAR DIPDEC0_rcsid[];
extern CHAR DIPDEC0_copyright[];
extern MASSTOR_LIST DIPDEC0_DIGFET ARGS((MASSTOR_LIST P, MASSTOR_LIST IL, MASSTOR_LIST JL));
extern MASSTOR_LIST DIPDEC0_DIGISM ARGS((MASSTOR_LIST P));
extern MASSTOR_LIST DIPDEC0_DIGISR ARGS((MASSTOR_LIST P));
extern MASSTOR_LIST DIPDEC0_DINTFE ARGS((MASSTOR_LIST T, MASSTOR_LIST IL, MASSTOR_LIST JL));
extern MASSTOR_LIST DIPDEC0_DINTSR ARGS((MASSTOR_LIST T));
extern MASSTOR_LIST DIPDEC0_DINTSS ARGS((MASSTOR_LIST T));
extern MASSTOR_LIST DIPDEC0_DINTZS ARGS((MASSTOR_LIST N));
extern MASSTOR_LIST DIPDEC0_DIRGZS ARGS((MASSTOR_LIST VB, MASSTOR_LIST PB, MASSTOR_LIST W));
extern MASSTOR_LIST DIPDEC0_DIRLPD ARGS((MASSTOR_LIST C_1_A, MASSTOR_LIST VP));
extern void DIPDEC0_DIRLPW ARGS((MASSTOR_LIST C_2_A, MASSTOR_LIST V, MASSTOR_LIST L));
extern MASSTOR_LIST DIPDEC0_DIRPDA ARGS((MASSTOR_LIST C_3_A, MASSTOR_LIST VP));
extern MASSTOR_LIST DIPDEC0_DITFZS ARGS((MASSTOR_LIST N));
extern void DIPDEC0_DITSPL ARGS((MASSTOR_LIST T, MASSTOR_LIST *T0, MASSTOR_LIST *T1));
extern void BEGIN_DIPDEC0();
