#define DEFINITION_DIPDIM

#ifndef DEFINITION_MASSTOR
#include "MASSTOR.h"
#endif

extern CHAR DIPDIM_rcsid[];
extern CHAR DIPDIM_copyright[];
extern MASSTOR_LIST DIPDIM_DIGBZT ARGS((MASSTOR_LIST S));
extern void DIPDIM_DILDIM ARGS((MASSTOR_LIST G, MASSTOR_LIST *DL, MASSTOR_LIST *S, MASSTOR_LIST *M));
extern MASSTOR_LIST DIPDIM_DIDIMS ARGS((MASSTOR_LIST G, MASSTOR_LIST S, MASSTOR_LIST U, MASSTOR_LIST M));
extern MASSTOR_LIST DIPDIM_EVGBIT ARGS((MASSTOR_LIST S, MASSTOR_LIST G));
extern MASSTOR_LIST DIPDIM_USETCT ARGS((MASSTOR_LIST U, MASSTOR_LIST V));
extern MASSTOR_LIST DIPDIM_IXSUBS ARGS((MASSTOR_LIST V, MASSTOR_LIST I));
extern void DIPDIM_DIDIMWR ARGS((MASSTOR_LIST DL, MASSTOR_LIST S, MASSTOR_LIST M, MASSTOR_LIST V));
extern void BEGIN_DIPDIM();
