#define DEFINITION_DIPDDGB

#ifndef DEFINITION_MASSTOR
#include "MASSTOR.h"
#endif

extern MASSTOR_LIST DIPDDGB_DIDPELIMDGB ARGS((MASSTOR_LIST P));
extern MASSTOR_LIST DIPDDGB_DIDPTDR ARGS((MASSTOR_LIST P, MASSTOR_LIST lcmHT, MASSTOR_LIST pair));
extern MASSTOR_LIST DIPDDGB_DIDPCPLMS1 ARGS((MASSTOR_LIST P));
extern MASSTOR_LIST DIPDDGB_DIDPLM1 ARGS((MASSTOR_LIST onestep, MASSTOR_LIST twostep));
extern MASSTOR_LIST DIPDDGB_DIDPUCPL1 ARGS((MASSTOR_LIST P, MASSTOR_LIST g, MASSTOR_LIST Old));
extern MASSTOR_LIST DIPDDGB_DIDPGPOL ARGS((MASSTOR_LIST g1, MASSTOR_LIST g2));
extern MASSTOR_LIST DIPDDGB_DIDPSPOL2 ARGS((MASSTOR_LIST g1, MASSTOR_LIST g2, MASSTOR_LIST lcmHT, MASSTOR_LIST lcmHK));
extern MASSTOR_LIST DIPDDGB_DIDPLEXTAL ARGS((MASSTOR_LIST AL, MASSTOR_LIST g));
extern void DIPDDGB_DIDPLCPL4 ARGS((MASSTOR_LIST P, MASSTOR_LIST *CPL, MASSTOR_LIST *AL));
extern MASSTOR_LIST DIPDDGB_DIDPALCMPC ARGS((MASSTOR_LIST AL, MASSTOR_LIST g1, MASSTOR_LIST g2, MASSTOR_LIST flag));
extern MASSTOR_LIST DIPDDGB_DIDPENF ARGS((MASSTOR_LIST P, MASSTOR_LIST varl, MASSTOR_LIST g));
extern MASSTOR_LIST DIPDDGB_DIDPREDDGB ARGS((MASSTOR_LIST P));
extern MASSTOR_LIST DIPDDGB_DIDPSPOL ARGS((MASSTOR_LIST g1, MASSTOR_LIST g2));
extern MASSTOR_LIST DIPDDGB_DIDPDNF ARGS((MASSTOR_LIST P, MASSTOR_LIST varl, MASSTOR_LIST g));
extern MASSTOR_LIST DIPDDGB_DIDPDGB ARGS((MASSTOR_LIST F, MASSTOR_LIST TF));
extern MASSTOR_LIST DIPDDGB_DIDPEGB ARGS((MASSTOR_LIST F, MASSTOR_LIST DP, MASSTOR_LIST TF));
extern void BEGIN_DIPDDGB();
