#define DEFINITION_DIPE

#ifndef DEFINITION_MASSTOR
#include "MASSTOR.h"
#endif

extern CHAR DIPE_rcsid[];
extern CHAR DIPE_copyright[];
extern MASSTOR_LIST DIPE_COPYOB ARGS((MASSTOR_LIST C_1_A));
extern void DIPE_EIMWRT ARGS((MASSTOR_LIST C_2_A));
extern MASSTOR_LIST DIPE_EIVABS ARGS((MASSTOR_LIST U));
extern MASSTOR_LIST DIPE_EIVAPP ARGS((MASSTOR_LIST U));
extern void DIPE_EIVCPP ARGS((MASSTOR_LIST U, MASSTOR_LIST *V, MASSTOR_LIST *VL));
extern MASSTOR_LIST DIPE_EIVEPR ARGS((MASSTOR_LIST U, MASSTOR_LIST V));
extern MASSTOR_LIST DIPE_EIVFUP ARGS((MASSTOR_LIST C_3_A, MASSTOR_LIST PL));
extern MASSTOR_LIST DIPE_EIVILP ARGS((MASSTOR_LIST U, MASSTOR_LIST V));
extern MASSTOR_LIST DIPE_EIVIP ARGS((MASSTOR_LIST C_4_A, MASSTOR_LIST BL));
extern MASSTOR_LIST DIPE_EIVIQ ARGS((MASSTOR_LIST C_5_A, MASSTOR_LIST BL));
extern MASSTOR_LIST DIPE_EIVIRP ARGS((MASSTOR_LIST U, MASSTOR_LIST V));
extern MASSTOR_LIST DIPE_EIVNEG ARGS((MASSTOR_LIST U));
extern MASSTOR_LIST DIPE_EIVPP ARGS((MASSTOR_LIST U));
extern MASSTOR_LIST DIPE_EIVSIG ARGS((MASSTOR_LIST U));
extern MASSTOR_LIST DIPE_EIVSUM ARGS((MASSTOR_LIST U, MASSTOR_LIST V));
extern void DIPE_EIVWRT ARGS((MASSTOR_LIST C_6_A));
extern MASSTOR_LIST DIPE_EXIDET ARGS((MASSTOR_LIST M));
extern MASSTOR_LIST DIPE_EXIDT2 ARGS((MASSTOR_LIST M));
extern MASSTOR_LIST DIPE_EXMHOM ARGS((MASSTOR_LIST M));
extern MASSTOR_LIST DIPE_EXVHOM ARGS((MASSTOR_LIST U, MASSTOR_LIST SL));
extern MASSTOR_LIST DIPE_ITD ARGS((MASSTOR_LIST C_7_A));
extern MASSTOR_LIST DIPE_IJACS ARGS((MASSTOR_LIST X, MASSTOR_LIST Y));
extern MASSTOR_LIST DIPE_ILADDC ARGS((MASSTOR_LIST U, MASSTOR_LIST CL));
extern void DIPE_ILEXPR ARGS((MASSTOR_LIST U, MASSTOR_LIST V, MASSTOR_LIST *W, MASSTOR_LIST *SL));
extern void DIPE_ILILPR ARGS((MASSTOR_LIST U, MASSTOR_LIST V, MASSTOR_LIST *W, MASSTOR_LIST *SL));
extern void DIPE_ILINPR ARGS((MASSTOR_LIST U, MASSTOR_LIST V, MASSTOR_LIST *W, MASSTOR_LIST *SL));
extern void DIPE_ILIRPR ARGS((MASSTOR_LIST U, MASSTOR_LIST V, MASSTOR_LIST *W, MASSTOR_LIST *SL));
extern MASSTOR_LIST DIPE_ILSCMP ARGS((MASSTOR_LIST U, MASSTOR_LIST V));
extern MASSTOR_LIST DIPE_ILWCMP ARGS((MASSTOR_LIST U, MASSTOR_LIST V));
extern MASSTOR_LIST DIPE_INDLST ARGS((MASSTOR_LIST RL, MASSTOR_LIST SL));
extern void DIPE_INLWRT ARGS((MASSTOR_LIST U));
extern MASSTOR_LIST DIPE_IPSR ARGS((MASSTOR_LIST R));
extern MASSTOR_LIST DIPE_IVHOM ARGS((MASSTOR_LIST U, MASSTOR_LIST IL, MASSTOR_LIST JL));
extern MASSTOR_LIST DIPE_IVRAND ARGS((MASSTOR_LIST KL, MASSTOR_LIST QL, MASSTOR_LIST NL));
extern MASSTOR_LIST DIPE_KREISP ARGS((MASSTOR_LIST NL));
extern MASSTOR_LIST DIPE_MDVHOM ARGS((MASSTOR_LIST ML, MASSTOR_LIST U));
extern MASSTOR_LIST DIPE_MIRAND ARGS((MASSTOR_LIST KL, MASSTOR_LIST QL, MASSTOR_LIST NL, MASSTOR_LIST ML));
extern MASSTOR_LIST DIPE_POWSEV ARGS((MASSTOR_LIST PL, MASSTOR_LIST C_8_A));
extern void DIPE_UIPRES ARGS((MASSTOR_LIST C_9_A, MASSTOR_LIST B, MASSTOR_LIST *CL, MASSTOR_LIST *KL));
extern MASSTOR_LIST DIPE_UIPRS1 ARGS((MASSTOR_LIST C_10_A, MASSTOR_LIST B));
extern MASSTOR_LIST DIPE_UIPSIL ARGS((MASSTOR_LIST C_11_A, MASSTOR_LIST EL));
extern MASSTOR_LIST DIPE_UIPSIV ARGS((MASSTOR_LIST C_12_A, MASSTOR_LIST B));
extern void BEGIN_DIPE();
