#define DEFINITION_DIPGB

#ifndef DEFINITION_MASSTOR
#include "MASSTOR.h"
#endif

extern CHAR DIPGB_rcsid[];
extern CHAR DIPGB_copyright[];
extern MASSTOR_LIST DIPGB_DIGMIN ARGS((MASSTOR_LIST P));
extern MASSTOR_LIST DIPGB_DILIS ARGS((MASSTOR_LIST P));
extern MASSTOR_LIST DIPGB_DIPGB ARGS((MASSTOR_LIST P, MASSTOR_LIST TF));
extern MASSTOR_LIST DIPGB_DIPNOR ARGS((MASSTOR_LIST P, MASSTOR_LIST S));
extern MASSTOR_LIST DIPGB_DIPSP ARGS((MASSTOR_LIST C_1_A, MASSTOR_LIST B));
extern MASSTOR_LIST DIPGB_DIIFGB ARGS((MASSTOR_LIST P, MASSTOR_LIST TF));
extern MASSTOR_LIST DIPGB_DIIFLS ARGS((MASSTOR_LIST P));
extern MASSTOR_LIST DIPGB_DIIFMI ARGS((MASSTOR_LIST P));
extern MASSTOR_LIST DIPGB_DIIFNF ARGS((MASSTOR_LIST P, MASSTOR_LIST RPP, MASSTOR_LIST S));
extern MASSTOR_LIST DIPGB_DIIFSP ARGS((MASSTOR_LIST C_2_A, MASSTOR_LIST B));
extern void BEGIN_DIPGB();
