#define DEFINITION_DIPGCD

#ifndef DEFINITION_MASSTOR
#include "MASSTOR.h"
#endif

extern CHAR DIPGCD_rcsid[];
extern CHAR DIPGCD_copyright[];
extern MASSTOR_LIST DIPGCD_DIRFAC ARGS((MASSTOR_LIST P));
extern MASSTOR_LIST DIPGCD_IPLCM ARGS((MASSTOR_LIST RL, MASSTOR_LIST C_1_A, MASSTOR_LIST B));
extern void BEGIN_DIPGCD();
