#define DEFINITION_DIPIGB

#ifndef DEFINITION_MASSTOR
#include "MASSTOR.h"
#endif

extern CHAR DIPIGB_rcsid[];
extern CHAR DIPIGB_copyright[];
extern MASSTOR_LIST DIPIGB_DIIGBA ARGS((MASSTOR_LIST PL, MASSTOR_LIST P, MASSTOR_LIST TF));
extern MASSTOR_LIST DIPIGB_DIIGMI ARGS((MASSTOR_LIST P));
extern MASSTOR_LIST DIPIGB_DIILIS ARGS((MASSTOR_LIST P));
extern MASSTOR_LIST DIPIGB_DIIPGB ARGS((MASSTOR_LIST P, MASSTOR_LIST TF));
extern MASSTOR_LIST DIPIGB_DIIPNF ARGS((MASSTOR_LIST P, MASSTOR_LIST RPP, MASSTOR_LIST S));
extern MASSTOR_LIST DIPIGB_DIIPSP ARGS((MASSTOR_LIST C_1_A, MASSTOR_LIST B));
extern void BEGIN_DIPIGB();
