#define DEFINITION_DIPI

#ifndef DEFINITION_MASSTOR
#include "MASSTOR.h"
#endif

extern CHAR DIPI_rcsid[];
extern CHAR DIPI_copyright[];
extern MASSTOR_LIST DIPI_DIIFRP ARGS((MASSTOR_LIST C_1_A));
extern MASSTOR_LIST DIPI_DIILFR ARGS((MASSTOR_LIST C_2_A));
extern MASSTOR_LIST DIPI_DIILFRCD ARGS((MASSTOR_LIST C_3_A));
extern MASSTOR_LIST DIPI_DIILRD ARGS((MASSTOR_LIST V));
extern void DIPI_DIILWR ARGS((MASSTOR_LIST C_4_A, MASSTOR_LIST V));
extern MASSTOR_LIST DIPI_DIIPAB ARGS((MASSTOR_LIST C_5_A));
extern void DIPI_DIIPCP ARGS((MASSTOR_LIST C_6_A, MASSTOR_LIST *CL, MASSTOR_LIST *AP));
extern MASSTOR_LIST DIPI_DIIPDF ARGS((MASSTOR_LIST C_7_A, MASSTOR_LIST B));
extern MASSTOR_LIST DIPI_DIIPDM ARGS((MASSTOR_LIST C_8_A));
extern MASSTOR_LIST DIPI_DIIPDR ARGS((MASSTOR_LIST C_9_A, MASSTOR_LIST IL));
extern MASSTOR_LIST DIPI_DIIPEM ARGS((MASSTOR_LIST C_10_A, MASSTOR_LIST AL));
extern MASSTOR_LIST DIPI_DIIPEV ARGS((MASSTOR_LIST C_11_A, MASSTOR_LIST IL, MASSTOR_LIST AL));
extern MASSTOR_LIST DIPI_DIIPEX ARGS((MASSTOR_LIST C_12_A, MASSTOR_LIST NL));
extern MASSTOR_LIST DIPI_DIIPHD ARGS((MASSTOR_LIST C_13_A, MASSTOR_LIST IL, MASSTOR_LIST NL));
extern MASSTOR_LIST DIPI_DIIPIP ARGS((MASSTOR_LIST C_14_A, MASSTOR_LIST BL));
extern MASSTOR_LIST DIPI_DIIPIQ ARGS((MASSTOR_LIST C_15_A, MASSTOR_LIST BL));
extern MASSTOR_LIST DIPI_DIIPLS ARGS((MASSTOR_LIST C_16_A));
extern MASSTOR_LIST DIPI_DIIPMN ARGS((MASSTOR_LIST C_17_A));
extern MASSTOR_LIST DIPI_DIIPNG ARGS((MASSTOR_LIST C_18_A));
extern MASSTOR_LIST DIPI_DIIPON ARGS((MASSTOR_LIST C_19_A));
extern MASSTOR_LIST DIPI_DIIPPR ARGS((MASSTOR_LIST C_20_A, MASSTOR_LIST B));
extern MASSTOR_LIST DIPI_DIIPPS ARGS((MASSTOR_LIST C_21_A, MASSTOR_LIST B));
extern MASSTOR_LIST DIPI_DIIPQ ARGS((MASSTOR_LIST C_22_A, MASSTOR_LIST B));
extern void DIPI_DIIPQR ARGS((MASSTOR_LIST C_23_A, MASSTOR_LIST B, MASSTOR_LIST *Q, MASSTOR_LIST *R));
extern MASSTOR_LIST DIPI_DIIPRA ARGS((MASSTOR_LIST RL, MASSTOR_LIST KL, MASSTOR_LIST LL, MASSTOR_LIST EL));
extern MASSTOR_LIST DIPI_DIIPRD ARGS((MASSTOR_LIST V));
extern MASSTOR_LIST DIPI_DIIPSG ARGS((MASSTOR_LIST C_24_A));
extern MASSTOR_LIST DIPI_DIIPSM ARGS((MASSTOR_LIST C_25_A, MASSTOR_LIST B));
extern MASSTOR_LIST DIPI_DIIPSN ARGS((MASSTOR_LIST C_26_A));
extern MASSTOR_LIST DIPI_DIIPSO ARGS((MASSTOR_LIST C_27_A));
extern MASSTOR_LIST DIPI_DIIPSU ARGS((MASSTOR_LIST C_28_A, MASSTOR_LIST IL, MASSTOR_LIST B));
extern MASSTOR_LIST DIPI_DIIPSV ARGS((MASSTOR_LIST C_29_A, MASSTOR_LIST B));
extern MASSTOR_LIST DIPI_DIIPTM ARGS((MASSTOR_LIST C_30_A, MASSTOR_LIST HL));
extern MASSTOR_LIST DIPI_DIIPTR ARGS((MASSTOR_LIST C_31_A, MASSTOR_LIST HL, MASSTOR_LIST IL));
extern void DIPI_DIIPWR ARGS((MASSTOR_LIST C_32_A, MASSTOR_LIST V));
extern void DIPI_DIIPWV ARGS((MASSTOR_LIST C_33_A));
extern MASSTOR_LIST DIPI_DIIRAS ARGS((MASSTOR_LIST RL, MASSTOR_LIST KL, MASSTOR_LIST LL, MASSTOR_LIST EL, MASSTOR_LIST QL));
extern void BEGIN_DIPI();
