#define DEFINITION_DIPIDGB

#ifndef DEFINITION_MASSTOR
#include "MASSTOR.h"
#endif

extern MASSTOR_LIST DIPIDGB_DIIPELIMDGB ARGS((MASSTOR_LIST P));
extern MASSTOR_LIST DIPIDGB_DIIPTDR ARGS((MASSTOR_LIST P, MASSTOR_LIST lcmHT, MASSTOR_LIST pair));
extern MASSTOR_LIST DIPIDGB_DIIPCPLMS1 ARGS((MASSTOR_LIST P));
extern MASSTOR_LIST DIPIDGB_DIIPLM1 ARGS((MASSTOR_LIST onestep, MASSTOR_LIST twostep));
extern MASSTOR_LIST DIPIDGB_DIIPUCPL1 ARGS((MASSTOR_LIST P, MASSTOR_LIST g, MASSTOR_LIST Old));
extern MASSTOR_LIST DIPIDGB_DIIPGPOL ARGS((MASSTOR_LIST g1, MASSTOR_LIST g2));
extern MASSTOR_LIST DIPIDGB_DIIPSPOL2 ARGS((MASSTOR_LIST g1, MASSTOR_LIST g2, MASSTOR_LIST lcmHT, MASSTOR_LIST lcmHK));
extern MASSTOR_LIST DIPIDGB_DIIPLEXTAL ARGS((MASSTOR_LIST AL, MASSTOR_LIST g));
extern void DIPIDGB_DIIPLCPL4 ARGS((MASSTOR_LIST P, MASSTOR_LIST *CPL, MASSTOR_LIST *AL));
extern MASSTOR_LIST DIPIDGB_DIIPALCMPC ARGS((MASSTOR_LIST AL, MASSTOR_LIST g1, MASSTOR_LIST g2, MASSTOR_LIST flag));
extern MASSTOR_LIST DIPIDGB_DIIPENF ARGS((MASSTOR_LIST P, MASSTOR_LIST varl, MASSTOR_LIST g));
extern MASSTOR_LIST DIPIDGB_DIIPREDDGB ARGS((MASSTOR_LIST P));
extern MASSTOR_LIST DIPIDGB_DIIPSPOL ARGS((MASSTOR_LIST g1, MASSTOR_LIST g2));
extern MASSTOR_LIST DIPIDGB_DIIPDNF ARGS((MASSTOR_LIST P, MASSTOR_LIST varl, MASSTOR_LIST g));
extern MASSTOR_LIST DIPIDGB_DIIPDGB ARGS((MASSTOR_LIST F, MASSTOR_LIST TF));
extern MASSTOR_LIST DIPIDGB_DIIPEGB ARGS((MASSTOR_LIST F, MASSTOR_LIST TF));
extern void BEGIN_DIPIDGB();
