#define DEFINITION_DIPIIB

#ifndef DEFINITION_MASSTOR
#include "MASSTOR.h"
#endif

extern CHAR DIPIIB_rcsid[];
extern CHAR DIPIIB_copyright[];
extern MASSTOR_LIST DIPIIB_DIIPPR2 ARGS((MASSTOR_LIST C_1_A, MASSTOR_LIST B));
extern MASSTOR_LIST DIPIIB_DIIPNFJ ARGS((MASSTOR_LIST P, MASSTOR_LIST RPP, MASSTOR_LIST S));
extern MASSTOR_LIST DIPIIB_DIILISJ ARGS((MASSTOR_LIST P));
extern MASSTOR_LIST DIPIIB_DIIPCOM ARGS((MASSTOR_LIST F));
extern MASSTOR_LIST DIPIIB_DIIPIB3 ARGS((MASSTOR_LIST F));
extern MASSTOR_LIST DIPIIB_DIIPIB2 ARGS((MASSTOR_LIST F));
extern MASSTOR_LIST DIPIIB_DIIPIB ARGS((MASSTOR_LIST F));
extern void DIPIIB_InitDIPIIB ARGS(());
extern void DIPIIB_SetDIPIIBSelect ARGS((INTEGER SEL));
extern void BEGIN_DIPIIB();
