#define DEFINITION_DIPIPOL

#ifndef DEFINITION_MASSTOR
#include "MASSTOR.h"
#endif

extern CHAR DIPIPOL_rcsid[];
extern CHAR DIPIPOL_copyright[];
extern MASSTOR_LIST DIPIPOL_VIPIIP ARGS((MASSTOR_LIST RL, MASSTOR_LIST C_1_A, MASSTOR_LIST B));
extern MASSTOR_LIST DIPIPOL_HIPRAN ARGS((MASSTOR_LIST RL, MASSTOR_LIST KL, MASSTOR_LIST QL, MASSTOR_LIST NL));
extern MASSTOR_LIST DIPIPOL_IPRAN ARGS((MASSTOR_LIST RL, MASSTOR_LIST KL, MASSTOR_LIST QL, MASSTOR_LIST N));
extern void BEGIN_DIPIPOL();
