#define DEFINITION_DIPROOT

#ifndef DEFINITION_MASSTOR
#include "MASSTOR.h"
#endif

extern CHAR DIPROOT_rcsid[];
extern CHAR DIPROOT_copyright[];
extern MASSTOR_LIST DIPROOT_DIGBSI ARGS((MASSTOR_LIST P, MASSTOR_LIST T, MASSTOR_LIST C_1_A));
extern MASSTOR_LIST DIPROOT_DIITNT ARGS((MASSTOR_LIST T));
extern void DIPROOT_DIITWR ARGS((MASSTOR_LIST TP, MASSTOR_LIST EPS));
extern void DIPROOT_DINTWR ARGS((MASSTOR_LIST TP, MASSTOR_LIST EPS));
extern void DIPROOT_DIROWR ARGS((MASSTOR_LIST V, MASSTOR_LIST P, MASSTOR_LIST EPS));
extern void DIPROOT_GBZSET ARGS((MASSTOR_LIST V, MASSTOR_LIST PP, MASSTOR_LIST EPS));
extern void DIPROOT_RIRWRT ARGS((MASSTOR_LIST R, MASSTOR_LIST EPS));
extern void BEGIN_DIPROOT();
