#define DEFINITION_DIPRNGB

#ifndef DEFINITION_MASSTOR
#include "MASSTOR.h"
#endif

extern CHAR DIPRNGB_rcsid[];
extern CHAR DIPRNGB_copyright[];
extern MASSTOR_LIST DIPRNGB_DIGBC3 ARGS((MASSTOR_LIST B, MASSTOR_LIST PLI, MASSTOR_LIST PLJ, MASSTOR_LIST EL));
extern MASSTOR_LIST DIPRNGB_DIGBC4 ARGS((MASSTOR_LIST PLI, MASSTOR_LIST PLJ, MASSTOR_LIST EL));
extern MASSTOR_LIST DIPRNGB_DIGBMI ARGS((MASSTOR_LIST P));
extern void DIPRNGB_DILCPL ARGS((MASSTOR_LIST P, MASSTOR_LIST *D, MASSTOR_LIST *B));
extern MASSTOR_LIST DIPRNGB_DILUPL ARGS((MASSTOR_LIST PL, MASSTOR_LIST P, MASSTOR_LIST D, MASSTOR_LIST B));
extern MASSTOR_LIST DIPRNGB_DIRGBA ARGS((MASSTOR_LIST PL, MASSTOR_LIST P, MASSTOR_LIST TF));
extern MASSTOR_LIST DIPRNGB_DIRGBR ARGS((MASSTOR_LIST P, MASSTOR_LIST TF));
extern MASSTOR_LIST DIPRNGB_DIRLIS ARGS((MASSTOR_LIST P));
extern MASSTOR_LIST DIPRNGB_DIRPGB ARGS((MASSTOR_LIST P, MASSTOR_LIST TF));
extern MASSTOR_LIST DIPRNGB_DIRPNF ARGS((MASSTOR_LIST P, MASSTOR_LIST S));
extern MASSTOR_LIST DIPRNGB_DIRPSP ARGS((MASSTOR_LIST C_1_A, MASSTOR_LIST B));
extern MASSTOR_LIST DIPRNGB_EVPLM ARGS((MASSTOR_LIST L1, MASSTOR_LIST L2));
extern MASSTOR_LIST DIPRNGB_EVPLSO ARGS((MASSTOR_LIST C_2_A));
extern void BEGIN_DIPRNGB();
