#define DEFINITION_DIPRF

#ifndef DEFINITION_MASSTOR
#include "MASSTOR.h"
#endif

extern CHAR DIPRF_rcsid[];
extern CHAR DIPRF_copyright[];
extern void DIPRF_IFWRIT ARGS((MASSTOR_LIST R, MASSTOR_LIST V));
extern MASSTOR_LIST DIPRF_RFDEN ARGS((MASSTOR_LIST R));
extern MASSTOR_LIST DIPRF_RFDIF ARGS((MASSTOR_LIST R, MASSTOR_LIST S));
extern MASSTOR_LIST DIPRF_RFEXP ARGS((MASSTOR_LIST C_1_A, MASSTOR_LIST NL));
extern MASSTOR_LIST DIPRF_RFFIP ARGS((MASSTOR_LIST RL, MASSTOR_LIST C_2_A));
extern MASSTOR_LIST DIPRF_RFINV ARGS((MASSTOR_LIST R));
extern MASSTOR_LIST DIPRF_RFNEG ARGS((MASSTOR_LIST R));
extern MASSTOR_LIST DIPRF_RFNOV ARGS((MASSTOR_LIST R));
extern MASSTOR_LIST DIPRF_RFNUM ARGS((MASSTOR_LIST R));
extern MASSTOR_LIST DIPRF_RFONE ARGS((MASSTOR_LIST R));
extern MASSTOR_LIST DIPRF_RFPROD ARGS((MASSTOR_LIST R, MASSTOR_LIST S));
extern MASSTOR_LIST DIPRF_RFQ ARGS((MASSTOR_LIST R, MASSTOR_LIST S));
extern MASSTOR_LIST DIPRF_RFREAD ARGS((MASSTOR_LIST V));
extern MASSTOR_LIST DIPRF_RFRED ARGS((MASSTOR_LIST RL, MASSTOR_LIST C_3_A, MASSTOR_LIST B));
extern MASSTOR_LIST DIPRF_RFSIGN ARGS((MASSTOR_LIST R));
extern MASSTOR_LIST DIPRF_RFSUM ARGS((MASSTOR_LIST R, MASSTOR_LIST S));
extern void DIPRF_RFWRIT ARGS((MASSTOR_LIST R, MASSTOR_LIST V));
extern void BEGIN_DIPRF();
