#define DEFINITION_DIPRN

#ifndef DEFINITION_MASSTOR
#include "MASSTOR.h"
#endif

extern CHAR DIPRN_rcsid[];
extern CHAR DIPRN_copyright[];
extern MASSTOR_LIST DIPRN_DIRFIP ARGS((MASSTOR_LIST C_1_A));
extern MASSTOR_LIST DIPRN_DIRLRD ARGS((MASSTOR_LIST V));
extern void DIPRN_DIRLWR ARGS((MASSTOR_LIST C_2_A, MASSTOR_LIST V, MASSTOR_LIST S));
extern MASSTOR_LIST DIPRN_DIRPAB ARGS((MASSTOR_LIST C_3_A));
extern MASSTOR_LIST DIPRN_DIRPDF ARGS((MASSTOR_LIST C_4_A, MASSTOR_LIST B));
extern MASSTOR_LIST DIPRN_DIRPDM ARGS((MASSTOR_LIST C_5_A));
extern MASSTOR_LIST DIPRN_DIRPDR ARGS((MASSTOR_LIST C_6_A, MASSTOR_LIST IL));
extern MASSTOR_LIST DIPRN_DIRPEM ARGS((MASSTOR_LIST C_7_A, MASSTOR_LIST AL));
extern MASSTOR_LIST DIPRN_DIRPEV ARGS((MASSTOR_LIST C_8_A, MASSTOR_LIST IL, MASSTOR_LIST AL));
extern MASSTOR_LIST DIPRN_DIRPEX ARGS((MASSTOR_LIST C_9_A, MASSTOR_LIST NL));
extern MASSTOR_LIST DIPRN_DIRPHD ARGS((MASSTOR_LIST C_10_A, MASSTOR_LIST IL, MASSTOR_LIST NL));
extern MASSTOR_LIST DIPRN_DIRPLS ARGS((MASSTOR_LIST C_11_A));
extern MASSTOR_LIST DIPRN_DIRPMC ARGS((MASSTOR_LIST C_12_A));
extern MASSTOR_LIST DIPRN_DIRPMN ARGS((MASSTOR_LIST C_13_A));
extern MASSTOR_LIST DIPRN_DIRPNG ARGS((MASSTOR_LIST C_14_A));
extern MASSTOR_LIST DIPRN_DIRPON ARGS((MASSTOR_LIST C_15_A));
extern MASSTOR_LIST DIPRN_DIRPPR ARGS((MASSTOR_LIST C_16_A, MASSTOR_LIST B));
extern MASSTOR_LIST DIPRN_DIRPQ ARGS((MASSTOR_LIST C_17_A, MASSTOR_LIST B));
extern void DIPRN_DIRPQR ARGS((MASSTOR_LIST C_18_A, MASSTOR_LIST B, MASSTOR_LIST *Q, MASSTOR_LIST *R));
extern MASSTOR_LIST DIPRN_DIRPRA ARGS((MASSTOR_LIST RL, MASSTOR_LIST KL, MASSTOR_LIST LL, MASSTOR_LIST EL));
extern MASSTOR_LIST DIPRN_DIRPRD ARGS((MASSTOR_LIST V));
extern MASSTOR_LIST DIPRN_DIRPRP ARGS((MASSTOR_LIST C_19_A, MASSTOR_LIST BL));
extern MASSTOR_LIST DIPRN_DIRPRQ ARGS((MASSTOR_LIST C_20_A, MASSTOR_LIST BL));
extern MASSTOR_LIST DIPRN_DIRPSG ARGS((MASSTOR_LIST C_21_A));
extern MASSTOR_LIST DIPRN_DIRPSM ARGS((MASSTOR_LIST C_22_A, MASSTOR_LIST B));
extern MASSTOR_LIST DIPRN_DIRPSN ARGS((MASSTOR_LIST C_23_A));
extern MASSTOR_LIST DIPRN_DIRPSO ARGS((MASSTOR_LIST C_24_A));
extern MASSTOR_LIST DIPRN_DIRPSU ARGS((MASSTOR_LIST C_25_A, MASSTOR_LIST IL, MASSTOR_LIST B));
extern MASSTOR_LIST DIPRN_DIRPSV ARGS((MASSTOR_LIST C_26_A, MASSTOR_LIST B));
extern MASSTOR_LIST DIPRN_DIRPTM ARGS((MASSTOR_LIST C_27_A, MASSTOR_LIST HL));
extern MASSTOR_LIST DIPRN_DIRPTR ARGS((MASSTOR_LIST C_28_A, MASSTOR_LIST HL, MASSTOR_LIST IL));
extern void DIPRN_DIRPWR ARGS((MASSTOR_LIST C_29_A, MASSTOR_LIST V, MASSTOR_LIST S));
extern void DIPRN_DIRPWV ARGS((MASSTOR_LIST C_30_A));
extern MASSTOR_LIST DIPRN_DIRRAS ARGS((MASSTOR_LIST RL, MASSTOR_LIST KL, MASSTOR_LIST LL, MASSTOR_LIST EL, MASSTOR_LIST QL));
extern void BEGIN_DIPRN();
