#define DEFINITION_DIPRNIB

#ifndef DEFINITION_MASSTOR
#include "MASSTOR.h"
#endif

extern CHAR DIPRNIB_rcsid[];
extern CHAR DIPRNIB_copyright[];
extern MASSTOR_LIST DIPRNIB_DIRPNFJ ARGS((MASSTOR_LIST P, MASSTOR_LIST S));
extern MASSTOR_LIST DIPRNIB_DIRLISJ ARGS((MASSTOR_LIST P));
extern MASSTOR_LIST DIPRNIB_DIRPCOM ARGS((MASSTOR_LIST F));
extern MASSTOR_LIST DIPRNIB_DIRPIB2 ARGS((MASSTOR_LIST F));
extern MASSTOR_LIST DIPRNIB_DIRPIB ARGS((MASSTOR_LIST F));
extern void BEGIN_DIPRNIB();
