#define DEFINITION_DIPRNPOL

#ifndef DEFINITION_MASSTOR
#include "MASSTOR.h"
#endif

extern CHAR DIPRNPOL_rcsid[];
extern CHAR DIPRNPOL_copyright[];
extern MASSTOR_LIST DIPRNPOL_RPABS ARGS((MASSTOR_LIST RL, MASSTOR_LIST C_1_A));
extern MASSTOR_LIST DIPRNPOL_RPCONST ARGS((MASSTOR_LIST RL, MASSTOR_LIST C_2_A));
extern MASSTOR_LIST DIPRNPOL_RPEXP ARGS((MASSTOR_LIST RL, MASSTOR_LIST C_3_A, MASSTOR_LIST NL));
extern MASSTOR_LIST DIPRNPOL_RPMON ARGS((MASSTOR_LIST RL, MASSTOR_LIST C_4_A));
extern MASSTOR_LIST DIPRNPOL_RPONE ARGS((MASSTOR_LIST RL, MASSTOR_LIST C_5_A));
extern MASSTOR_LIST DIPRNPOL_RPSIGN ARGS((MASSTOR_LIST RL, MASSTOR_LIST C_6_A));
extern void DIPRNPOL_RPLWRS ARGS((MASSTOR_LIST RL, MASSTOR_LIST C_7_A, MASSTOR_LIST V, MASSTOR_LIST S));
extern void DIPRNPOL_RPWRTS ARGS((MASSTOR_LIST RL, MASSTOR_LIST C_8_A, MASSTOR_LIST V, MASSTOR_LIST S));
extern void DIPRNPOL_RUPEGC ARGS((MASSTOR_LIST C_9_A, MASSTOR_LIST B, MASSTOR_LIST *C, MASSTOR_LIST *U, MASSTOR_LIST *V));
extern MASSTOR_LIST DIPRNPOL_RUPGCD ARGS((MASSTOR_LIST C_10_A, MASSTOR_LIST B));
extern void DIPRNPOL_RUPHEG ARGS((MASSTOR_LIST C_11_A, MASSTOR_LIST B, MASSTOR_LIST *C, MASSTOR_LIST *V));
extern MASSTOR_LIST DIPRNPOL_RUPLCM ARGS((MASSTOR_LIST C_12_A, MASSTOR_LIST B));
extern void BEGIN_DIPRNPOL();
