#define DEFINITION_DIPTOO

#ifndef DEFINITION_MASSTOR
#include "MASSTOR.h"
#endif

extern CHAR DIPTOO_rcsid[];
extern CHAR DIPTOO_copyright[];
extern MASSTOR_LIST DIPTOO_DIPDEM ARGS((MASSTOR_LIST C_1_A));
extern MASSTOR_LIST DIPTOO_DIPDEV ARGS((MASSTOR_LIST C_2_A));
extern MASSTOR_LIST DIPTOO_DIPLDM ARGS((MASSTOR_LIST C_3_A));
extern MASSTOR_LIST DIPTOO_DIPTRM ARGS((MASSTOR_LIST C_4_A));
extern MASSTOR_LIST DIPTOO_DIPTYP ARGS((MASSTOR_LIST C_5_A));
extern void DIPTOO_DIPVOP ARGS((MASSTOR_LIST P, MASSTOR_LIST V, MASSTOR_LIST *PP, MASSTOR_LIST *VP));
extern void DIPTOO_DIPVOPP ARGS((MASSTOR_LIST P, MASSTOR_LIST V, MASSTOR_LIST *PP, MASSTOR_LIST *VP, MASSTOR_LIST *PV));
extern MASSTOR_LIST DIPTOO_DMEVAD ARGS((MASSTOR_LIST C_6_A, MASSTOR_LIST E));
extern void DIPTOO_HDIFDI ARGS((MASSTOR_LIST C_7_A, MASSTOR_LIST *B, MASSTOR_LIST *FL));
extern MASSTOR_LIST DIPTOO_INVPERM ARGS((MASSTOR_LIST perm));
extern MASSTOR_LIST DIPTOO_LBLXCO ARGS((MASSTOR_LIST U, MASSTOR_LIST V));
extern BOOLEAN DIPTOO_LFCHECK ARGS((MASSTOR_LIST L, MASSTOR_LIST f));
extern MASSTOR_LIST DIPTOO_PTERM ARGS((MASSTOR_LIST RL, MASSTOR_LIST C_8_A));
extern MASSTOR_LIST DIPTOO_PTYP ARGS((MASSTOR_LIST RL, MASSTOR_LIST C_9_A));
extern MASSTOR_LIST DIPTOO_PVDEMA ARGS((MASSTOR_LIST C_10_A));
extern void BEGIN_DIPTOO();
