#define DEFINITION_GSYMFURN

#ifndef DEFINITION_MASSTOR
#include "MASSTOR.h"
#endif

#ifndef DEFINITION_MASELEM
#include "MASELEM.h"
#endif

extern CHAR GSYMFURN_rcsid[];
extern CHAR GSYMFURN_copyright[];
extern MASSTOR_LIST GSYMFURN_GRNORP ARGS((MASSTOR_LIST PG, MASSTOR_LIST MO));
extern MASSTOR_LIST GSYMFURN_GRNOPL ARGS((MASSTOR_LIST PG, MASSTOR_LIST ML));
extern void GSYMFURN_GRNCUT ARGS((MASSTOR_LIST PG, MASSTOR_LIST POL, MASSTOR_LIST *POL_1, MASSTOR_LIST *POL_2));
extern MASSTOR_LIST GSYMFURN_GRNCHK ARGS((MASSTOR_LIST PG, MASSTOR_LIST BASE, MASSTOR_LIST POL));
extern void GSYMFURN_GRNCHKBAS ARGS((MASSTOR_LIST *BASE, MASSTOR_LIST *POL));
extern void GSYMFURN_GRNRED ARGS((MASSTOR_LIST PG, MASSTOR_LIST POL, MASSTOR_LIST *BASE, MASSTOR_LIST *BASE_POL, MASSTOR_LIST *REM_POL));
extern MASSTOR_LIST GSYMFURN_GRNBAS ARGS((MASSTOR_LIST PG));
extern MASSTOR_LIST GSYMFURN_GRNGGB ARGS((MASSTOR_LIST PG));
extern void BEGIN_GSYMFURN();
