#define DEFINITION_GSYMINP

#ifndef DEFINITION_MASSTOR
#include "MASSTOR.h"
#endif

extern CHAR GSYMINP_rcsid[];
extern CHAR GSYMINP_copyright[];
extern MASSTOR_LIST GSYMINP_GSDREAD ARGS(());
extern MASSTOR_LIST GSYMINP_GSPREAD ARGS(());
extern MASSTOR_LIST GSYMINP_GSRDREAD ARGS(());
extern MASSTOR_LIST GSYMINP_GSRREAD ARGS(());
extern void BEGIN_GSYMINP();
