#define DEFINITION_LINALG

#ifndef DEFINITION_MASSTOR
#include "MASSTOR.h"
#endif

extern CHAR LINALG_rcsid[];
extern CHAR LINALG_copyright[];
extern MASSTOR_LIST LINALG_ADUM ARGS((MASSTOR_LIST D, MASSTOR_LIST n));
extern MASSTOR_LIST LINALG_ADVSPROD ARGS((MASSTOR_LIST D, MASSTOR_LIST C_1_A, MASSTOR_LIST B));
extern MASSTOR_LIST LINALG_ADVSVPROD ARGS((MASSTOR_LIST C_2_A, MASSTOR_LIST b));
extern MASSTOR_LIST LINALG_ADVVSUM ARGS((MASSTOR_LIST C_3_A, MASSTOR_LIST B));
extern MASSTOR_LIST LINALG_ADSMPROD ARGS((MASSTOR_LIST C_4_A, MASSTOR_LIST b));
extern MASSTOR_LIST LINALG_ADMSUM ARGS((MASSTOR_LIST C_5_A, MASSTOR_LIST B));
extern MASSTOR_LIST LINALG_ADMPROD ARGS((MASSTOR_LIST D, MASSTOR_LIST C_6_A, MASSTOR_LIST B));
extern void LINALG_ADVWRITE ARGS((MASSTOR_LIST C_7_A));
extern void LINALG_ADMWRITE ARGS((MASSTOR_LIST C_8_A));
extern MASSTOR_LIST LINALG_ADMTRACE ARGS((MASSTOR_LIST D, MASSTOR_LIST C_9_A));
extern MASSTOR_LIST LINALG_ADMPTRACE ARGS((MASSTOR_LIST D, MASSTOR_LIST C_10_A, MASSTOR_LIST B));
extern MASSTOR_LIST LINALG_ADCHARPOL ARGS((MASSTOR_LIST D, MASSTOR_LIST Q));
extern MASSTOR_LIST LINALG_ADSIG ARGS((MASSTOR_LIST D, MASSTOR_LIST Q));
extern MASSTOR_LIST LINALG_IMTRACE ARGS((MASSTOR_LIST C_11_A));
extern MASSTOR_LIST LINALG_IMPTRACE ARGS((MASSTOR_LIST C_12_A, MASSTOR_LIST B));
extern MASSTOR_LIST LINALG_ICHARPOL ARGS((MASSTOR_LIST Q));
extern MASSTOR_LIST LINALG_ISIG ARGS((MASSTOR_LIST Q));
extern MASSTOR_LIST LINALG_IMRTPROD ARGS((MASSTOR_LIST C_13_A, MASSTOR_LIST B));
extern void BEGIN_LINALG();
