#define DEFINITION_LISTTOOLS

#ifndef DEFINITION_MASSTOR
#include "MASSTOR.h"
#endif

extern CHAR LISTTOOLS_rcsid[];
extern CHAR LISTTOOLS_copyright[];
extern MASSTOR_LIST LISTTOOLS_CLISTFA ARGS((MASSTOR_LIST atom));
extern MASSTOR_LIST LISTTOOLS_LIST6 ARGS((MASSTOR_LIST a1, MASSTOR_LIST a2, MASSTOR_LIST a3, MASSTOR_LIST a4, MASSTOR_LIST a5, MASSTOR_LIST a6));
extern MASSTOR_LIST LISTTOOLS_LPAIRS ARGS((MASSTOR_LIST L));
extern MASSTOR_LIST LISTTOOLS_LSRCHQ ARGS((MASSTOR_LIST a, MASSTOR_LIST L));
extern MASSTOR_LIST LISTTOOLS_UPCASE ARGS((MASSTOR_LIST clist));
extern void BEGIN_LISTTOOLS();
