#define DEFINITION_MASBIOS

#ifndef DEFINITION_MASELEM
#include "MASELEM.h"
#endif

#ifndef DEFINITION_MASSTOR
#include "MASSTOR.h"
#endif

extern MASELEM_GAMMAINT MASBIOS_CHI;
extern CHAR MASBIOS_rcsid[];
extern CHAR MASBIOS_copyright[];
#define MASBIOS_termkind	1
#define MASBIOS_diskkind	2
#define MASBIOS_ramkind	3
#define MASBIOS_winkind	4
#define MASBIOS_nulkind	5
#define MASBIOS_grakind	6
extern void MASBIOS_BKSP ARGS(());
extern void MASBIOS_BLINES ARGS((MASELEM_GAMMAINT N));
extern MASELEM_GAMMAINT MASBIOS_CREAD ARGS(());
extern MASELEM_GAMMAINT MASBIOS_CREADB ARGS(());
extern void MASBIOS_CWRITE ARGS((MASELEM_GAMMAINT C));
extern void MASBIOS_CloseBIOS ARGS(());
extern MASELEM_GAMMAINT MASBIOS_CUNIT ARGS((CHAR S[], LONGCARD ));
extern void MASBIOS_DIBUFF ARGS(());
extern BOOLEAN MASBIOS_DIGIT ARGS((MASELEM_GAMMAINT C));
extern MASELEM_GAMMAINT MASBIOS_GREAD ARGS(());
extern void MASBIOS_GWRITE ARGS((MASELEM_GAMMAINT a));
extern BOOLEAN MASBIOS_LETTER ARGS((MASELEM_GAMMAINT C));
extern MASSTOR_LIST MASBIOS_LISTS ARGS((CHAR S[], LONGCARD ));
extern void MASBIOS_SLIST ARGS((MASSTOR_LIST C_1_A, CHAR S[], LONGCARD ));
extern CHAR MASBIOS_MASCHR ARGS((MASELEM_GAMMAINT C));
extern MASELEM_GAMMAINT MASBIOS_MASORD ARGS((CHAR C));
extern MASELEM_GAMMAINT MASBIOS_MASORDI ARGS((MASELEM_GAMMAINT C));
extern void MASBIOS_SILINE ARGS((MASELEM_GAMMAINT *S, MASELEM_GAMMAINT *L, MASELEM_GAMMAINT *R));
extern MASELEM_GAMMAINT MASBIOS_SIUNIT ARGS((CHAR S[], LONGCARD ));
extern void MASBIOS_SOLINE ARGS((MASELEM_GAMMAINT *S, MASELEM_GAMMAINT *L, MASELEM_GAMMAINT *R));
extern MASELEM_GAMMAINT MASBIOS_SOUNIT ARGS((CHAR S[], LONGCARD ));
extern void MASBIOS_Summary ARGS(());
extern void MASBIOS_StorSummary ARGS(());
extern void MASBIOS_SWRITE ARGS((CHAR S[], LONGCARD ));
extern void MASBIOS_TAB ARGS((MASELEM_GAMMAINT n));
extern INTEGER MASBIOS_IStreamKind ARGS(());
extern INTEGER MASBIOS_OStreamKind ARGS(());
extern INTEGER MASBIOS_EStreamKind ARGS(());
extern void BEGIN_MASBIOS();
