#define DEFINITION_MASCOMB

#ifndef DEFINITION_MASSTOR
#include "MASSTOR.h"
#endif

extern CHAR MASCOMB_rcsid[];
extern CHAR MASCOMB_copyright[];
extern MASSTOR_LIST MASCOMB_INVPERM ARGS((MASSTOR_LIST perm));
extern MASSTOR_LIST MASCOMB_PVFLISTS ARGS((MASSTOR_LIST list1, MASSTOR_LIST list2));
extern void BEGIN_MASCOMB();
