#define DEFINITION_MASELEM

typedef LONGINT MASELEM_GAMMAINT;
typedef MASELEM_GAMMAINT MASELEM_LIST;
extern CHAR MASELEM_rcsid[];
extern CHAR MASELEM_copyright[];
extern MASELEM_GAMMAINT MASELEM_MASABS ARGS((MASELEM_GAMMAINT a));
extern BOOLEAN MASELEM_MASEVEN ARGS((MASELEM_GAMMAINT a));
extern MASELEM_GAMMAINT MASELEM_MASEXP ARGS((MASELEM_GAMMAINT a, MASELEM_GAMMAINT b));
extern MASELEM_GAMMAINT MASELEM_MASMAX ARGS((MASELEM_GAMMAINT a, MASELEM_GAMMAINT b));
extern MASELEM_GAMMAINT MASELEM_MASMIN ARGS((MASELEM_GAMMAINT a, MASELEM_GAMMAINT b));
extern BOOLEAN MASELEM_MASODD ARGS((MASELEM_GAMMAINT a));
extern void MASELEM_MASQREM ARGS((MASELEM_GAMMAINT a, MASELEM_GAMMAINT b, MASELEM_GAMMAINT *q, MASELEM_GAMMAINT *r));
extern MASELEM_GAMMAINT MASELEM_MASREM ARGS((MASELEM_GAMMAINT a, MASELEM_GAMMAINT b));
extern MASELEM_GAMMAINT MASELEM_MASSIGN ARGS((MASELEM_GAMMAINT a));
extern void BEGIN_MASELEM();
