#define DEFINITION_MASFF

#ifndef DEFINITION_MASSTOR
#include "MASSTOR.h"
#endif

extern CHAR MASFF_rcsid[];
extern CHAR MASFF_copyright[];
extern MASSTOR_LIST MASFF_FFCOMP ARGS((MASSTOR_LIST R, MASSTOR_LIST S));
extern MASSTOR_LIST MASFF_FFDIF ARGS((MASSTOR_LIST p, MASSTOR_LIST M, MASSTOR_LIST AL, MASSTOR_LIST BL));
extern MASSTOR_LIST MASFF_FFEXP ARGS((MASSTOR_LIST p, MASSTOR_LIST M, MASSTOR_LIST C_1_A, MASSTOR_LIST NL));
extern MASSTOR_LIST MASFF_FFFINT ARGS((MASSTOR_LIST p, MASSTOR_LIST M, MASSTOR_LIST C_2_A));
extern MASSTOR_LIST MASFF_FFHOM ARGS((MASSTOR_LIST p, MASSTOR_LIST M, MASSTOR_LIST C_3_A));
extern MASSTOR_LIST MASFF_FFINV ARGS((MASSTOR_LIST p, MASSTOR_LIST M, MASSTOR_LIST AL));
extern MASSTOR_LIST MASFF_FFNEG ARGS((MASSTOR_LIST p, MASSTOR_LIST M, MASSTOR_LIST AL));
extern MASSTOR_LIST MASFF_FFONE ARGS((MASSTOR_LIST R));
extern MASSTOR_LIST MASFF_FFPROD ARGS((MASSTOR_LIST p, MASSTOR_LIST M, MASSTOR_LIST AL, MASSTOR_LIST BL));
extern MASSTOR_LIST MASFF_FFQ ARGS((MASSTOR_LIST p, MASSTOR_LIST M, MASSTOR_LIST AL, MASSTOR_LIST BL));
extern MASSTOR_LIST MASFF_FFRAND ARGS((MASSTOR_LIST p, MASSTOR_LIST M, MASSTOR_LIST NL));
extern MASSTOR_LIST MASFF_FFREAD ARGS((MASSTOR_LIST V));
extern MASSTOR_LIST MASFF_FFSUM ARGS((MASSTOR_LIST p, MASSTOR_LIST M, MASSTOR_LIST AL, MASSTOR_LIST BL));
extern void MASFF_FFWRITE ARGS((MASSTOR_LIST R, MASSTOR_LIST V));
extern void BEGIN_MASFF();
