#define DEFINITION_MASF

#ifndef DEFINITION_MASELEM
#include "MASELEM.h"
#endif

#ifndef DEFINITION_MASSTOR
#include "MASSTOR.h"
#endif

typedef REAL MASF_MFLOAT;
extern MASF_MFLOAT MASF_FBETA;
extern MASF_MFLOAT MASF_FBETAH;
extern MASELEM_GAMMAINT MASF_BETAH;
extern MASSTOR_LIST MASF_IBETA;
extern CHAR MASF_rcsid[];
extern CHAR MASF_copyright[];
extern MASF_MFLOAT MASF_FFGI ARGS((MASELEM_GAMMAINT N));
extern MASSTOR_LIST MASF_IFF ARGS((MASF_MFLOAT F));
extern MASF_MFLOAT MASF_FEXP ARGS((MASF_MFLOAT F, MASELEM_GAMMAINT N));
extern MASF_MFLOAT MASF_FLOG10 ARGS((MASF_MFLOAT F));
extern MASF_MFLOAT MASF_FFINT ARGS((MASSTOR_LIST N));
extern MASF_MFLOAT MASF_FFRN ARGS((MASSTOR_LIST C_1_A));
extern MASSTOR_LIST MASF_RNFF ARGS((MASF_MFLOAT F));
extern MASSTOR_LIST MASF_SIN ARGS((MASSTOR_LIST C_2_A));
extern MASSTOR_LIST MASF_COS ARGS((MASSTOR_LIST C_3_A));
extern MASSTOR_LIST MASF_TAN ARGS((MASSTOR_LIST C_4_A));
extern MASSTOR_LIST MASF_ARCTAN ARGS((MASSTOR_LIST C_5_A));
extern MASSTOR_LIST MASF_EXPF ARGS((MASSTOR_LIST C_6_A));
extern MASSTOR_LIST MASF_LN ARGS((MASSTOR_LIST C_7_A));
extern MASSTOR_LIST MASF_LOG ARGS((MASSTOR_LIST C_8_A));
extern MASSTOR_LIST MASF_SQRT ARGS((MASSTOR_LIST C_9_A));
extern void BEGIN_MASF();
