#define DEFINITION_MASLISP

#ifndef DEFINITION_MASSTOR
#include "MASSTOR.h"
#endif

#define MASLISP_FEXPR	2
#define MASLISP_MACRO	3
#define MASLISP_GENERIC	4
extern MASSTOR_LIST MASLISP_TDEF, MASLISP_DEFAULT, MASLISP_ARROW, MASLISP_ENV, MASLISP_NULL, MASLISP_WT, MASLISP_SCHLUSS, MASLISP_schluss, MASLISP_TINFO, MASLISP_EQS, MASLISP_NEQS, MASLISP_GTS, MASLISP_LTS, MASLISP_GEQ, MASLISP_LEQ, MASLISP_NOTS, MASLISP_UND, MASLISP_ODER, MASLISP_ADD, MASLISP_SUB, MASLISP_MUL, MASLISP_QUOT, MASLISP_REM, MASLISP_POW, MASLISP_QUOTE, MASLISP_SETQ, MASLISP_COND, MASLISP_LISTX, MASLISP_ASSIGN, MASLISP_READ, MASLISP_WRITE, MASLISP_DECREAD, MASLISP_DECWRITE, MASLISP_PROGN, MASLISP_VARS, MASLISP_IFS, MASLISP_WHL, MASLISP_RPT, MASLISP_STRNG, MASLISP_DE, MASLISP_DF, MASLISP_DM, MASLISP_DG, MASLISP_PROGA, MASLISP_GTO, MASLISP_LBEL, MASLISP_SETAV, MASLISP_ARY, MASLISP_ATM, MASLISP_RTN, MASLISP_ANY, MASLISP_UNIT, MASLISP_EXPOS, MASLISP_SPEC, MASLISP_SORT, MASLISP_SIG, MASLISP_IMPRT, MASLISP_IMPL, MASLISP_MODEL, MASLISP_MAP, MASLISP_AXIOM, MASLISP_RULE, MASLISP_WHEN, MASLISP_LAMBDA, MASLISP_FLAMBDA, MASLISP_MLAMBDA, MASLISP_GLAMBDA;
extern BOOLEAN MASLISP_trace;
extern BOOLEAN MASLISP_stricttyping;
extern MASSTOR_LIST MASLISP_REP, MASLISP_FER, MASLISP_FERx, MASLISP_FEL, MASLISP_FELx, MASLISP_CONVVAL, MASLISP_CONVDES;
extern CHAR MASLISP_rcsid[];
extern CHAR MASLISP_copyright[];
extern MASSTOR_LIST MASLISP_ECENV ARGS((MASSTOR_LIST ENV));
extern MASSTOR_LIST MASLISP_DCENV ARGS((MASSTOR_LIST E));
extern void MASLISP_SETV ARGS((MASSTOR_LIST V, MASSTOR_LIST C_1_A, MASSTOR_LIST *ENV));
extern BOOLEAN MASLISP_EXTENDENV ARGS((MASSTOR_LIST C_2_A, MASSTOR_LIST X, MASSTOR_LIST *ENV));
extern void MASLISP_COPYTOENV ARGS((MASSTOR_LIST V, MASSTOR_LIST EP, MASSTOR_LIST *ENV));
extern BOOLEAN MASLISP_SPECIALFORM ARGS((MASSTOR_LIST S));
extern BOOLEAN MASLISP_LAMBDAP ARGS((MASSTOR_LIST S));
extern BOOLEAN MASLISP_SEXPRP ARGS((MASSTOR_LIST X));
extern MASSTOR_LIST MASLISP_DEFE ARGS((MASSTOR_LIST X, MASSTOR_LIST *ENV));
extern MASSTOR_LIST MASLISP_DEFF ARGS((MASSTOR_LIST X, MASSTOR_LIST *ENV));
extern MASSTOR_LIST MASLISP_DEFM ARGS((MASSTOR_LIST X, MASSTOR_LIST *ENV));
extern MASSTOR_LIST MASLISP_DEFMAP ARGS((MASSTOR_LIST X, MASSTOR_LIST *ENV));
extern MASSTOR_LIST MASLISP_DEFPROC ARGS((MASSTOR_LIST X, MASSTOR_LIST *ENV));
extern MASSTOR_LIST MASLISP_DEFRULE ARGS((MASSTOR_LIST X, MASSTOR_LIST *ENV));
extern MASSTOR_LIST MASLISP_DSPEC ARGS((MASSTOR_LIST X, MASSTOR_LIST *ENV));
extern MASSTOR_LIST MASLISP_DMIA ARGS((MASSTOR_LIST X, MASSTOR_LIST *ENV));
extern MASSTOR_LIST MASLISP_TYPEOF ARGS((MASSTOR_LIST X));
extern MASSTOR_LIST MASLISP_TAG ARGS((MASSTOR_LIST V, MASSTOR_LIST T));
extern MASSTOR_LIST MASLISP_VALOFTAG ARGS((MASSTOR_LIST L));
extern MASSTOR_LIST MASLISP_TYPOFTAG ARGS((MASSTOR_LIST L));
extern MASSTOR_LIST MASLISP_DECOFTAG ARGS((MASSTOR_LIST L));
extern MASSTOR_LIST MASLISP_GENPL ARGS((MASSTOR_LIST P, MASSTOR_LIST V, MASSTOR_LIST T, MASSTOR_LIST D));
extern MASSTOR_LIST MASLISP_GENTE ARGS((MASSTOR_LIST Z, MASSTOR_LIST N, MASSTOR_LIST D));
extern void BEGIN_MASLISP();
