#include "SYSTEM_.h"

#ifndef DEFINITION_MASLISPU
#include "MASLISPU.h"
#endif

#ifndef DEFINITION_LINALGRN
#include "LINALGRN.h"
#endif

#ifndef DEFINITION_LINALGI
#include "LINALGI.h"
#endif

#ifndef DEFINITION_SACLDIO
#include "SACLDIO.h"
#endif

#ifndef DEFINITION_MASLOADL
#include "MASLOADL.h"
#endif

CHAR MASLOADL_rcsid [] = "$Id: MASLOADL.md,v 1.1 1992/01/22 15:11:54 kredel Exp $";
CHAR MASLOADL_copyright [] = "Copyright (c) 1989 - 1992 Universitaet Passau";

static CHAR rcsidi [] = "$Id: MASLOADL.mi,v 1.3 1992/10/15 16:30:36 kredel Exp $";
static CHAR copyrighti [] = "Copyright (c) 1989 - 1992 Universitaet Passau";


void MASLOADL_InitExternalsL
# ifdef __STDC__
()
# else
()
# endif
{
  MASLISPU_Compiledf1(LINALGRN_MDIM, "MDIM", 4L);
  MASLISPU_Compiledf1(LINALGRN_MTRANS, "MTRANS", 6L);
  MASLISPU_Compiledf2(LINALGRN_VEL, "VEL", 3L);
  MASLISPU_Compiledf3(LINALGRN_MGET, "MGET", 4L);
  MASLISPU_Compiledf4(LINALGRN_MSET, "MSET", 4L);
  MASLISPU_Compiledf3(LINALGRN_MMINOR, "MMINOR", 6L);
  MASLISPU_Compiledf1(LINALGRN_MRANG, "MRANG", 5L);
  MASLISPU_Compiledf2(LINALGRN_RNMHILBERT, "RNMHILBERT", 10L);
  MASLISPU_Compiledf2(LINALGRN_RNUM, "RNUM", 4L);
  MASLISPU_Compiledp2(LINALGRN_RNVWRITE, "RNVWRITE", 8L);
  MASLISPU_Compiledf0(LINALGRN_RNVREAD, "RNVREAD", 7L);
  MASLISPU_Compiledf1(LINALGRN_RNVMAX, "RNVMAX", 6L);
  MASLISPU_Compiledf1(LINALGRN_RNVSSUM, "RNVSSUM", 7L);
  MASLISPU_Compiledf4(LINALGRN_RNVLC, "RNVLC", 5L);
  MASLISPU_Compiledf1(LINALGRN_RNVFIV, "RNVFIV", 6L);
  MASLISPU_Compiledf1(LINALGRN_RNVQF, "RNVQF", 5L);
  MASLISPU_Compiledf2(LINALGRN_RNVQ, "RNVQ", 4L);
  MASLISPU_Compiledf2(LINALGRN_RNVSPROD, "RNVSPROD", 8L);
  MASLISPU_Compiledf2(LINALGRN_RNSVPROD, "RNSVPROD", 8L);
  MASLISPU_Compiledf2(LINALGRN_RNVVSUM, "RNVVSUM", 7L);
  MASLISPU_Compiledf2(LINALGRN_RNVSVSUM, "RNVSVSUM", 8L);
  MASLISPU_Compiledf2(LINALGRN_RNVSVPROD, "RNVSVPROD", 9L);
  MASLISPU_Compiledf2(LINALGRN_RNVVPROD, "RNVVPROD", 8L);
  MASLISPU_Compiledf2(LINALGRN_RNVDIF, "RNVDIF", 6L);
  MASLISPU_Compiledf1(LINALGRN_RNMMAX, "RNMMAX", 6L);
  MASLISPU_Compiledp2(LINALGRN_RNMWRITE, "RNMWRITE", 8L);
  MASLISPU_Compiledf0(LINALGRN_RNMREAD, "RNMREAD", 7L);
  MASLISPU_Compiledf1(LINALGRN_RNMFIM, "RNMFIM", 6L);
  MASLISPU_Compiledf2(LINALGRN_RNMPROD, "RNMPROD", 7L);
  MASLISPU_Compiledf2(LINALGRN_RNMSUM, "RNMSUM", 6L);
  MASLISPU_Compiledf2(LINALGRN_RNSMPROD, "RNSMPROD", 8L);
  MASLISPU_Compiledf2(LINALGRN_RNMDIF, "RNMDIF", 6L);
  MASLISPU_Compiledf1(LINALGRN_RNMGE, "RNMGE", 5L);
  MASLISPU_Compiledf1(LINALGRN_RNMDET, "RNMDET", 6L);
  MASLISPU_Compiledf1(LINALGRN_RNMDETL, "RNMDETL", 7L);
  MASLISPU_Compiledp1v2(LINALGRN_RNMGELUD, "RNMGELUD", 8L);
  MASLISPU_Compiledf2(LINALGRN_RNMLT, "RNMLT", 5L);
  MASLISPU_Compiledf2(LINALGRN_RNMUT, "RNMUT", 5L);
  MASLISPU_Compiledf3(LINALGRN_RNMSDS, "RNMSDS", 6L);
  MASLISPU_Compiledf1(LINALGRN_RNMINV, "RNMINV", 6L);
  MASLISPU_Compiledf1(LINALGRN_RNMUNS, "RNMUNS", 6L);
  MASLISPU_Compiledf2(LINALGI_IUM, "IUM", 3L);
  MASLISPU_Compiledp1(LINALGI_IVWRITE, "IVWRITE", 7L);
  MASLISPU_Compiledf2(LINALGI_IKM, "IKM", 3L);
  MASLISPU_Compiledf4(LINALGI_IVLC, "IVLC", 4L);
  MASLISPU_Compiledf2(LINALGI_IVSQ, "IVSQ", 4L);
  MASLISPU_Compiledf1(LINALGI_IVMAX, "IVMAX", 5L);
  MASLISPU_Compiledf1(LINALGI_IVSSUM, "IVSSUM", 6L);
  MASLISPU_Compiledf2(LINALGI_IVVDIF, "IVVDIF", 6L);
  MASLISPU_Compiledf2(LINALGI_IVVSUM, "IVVSUM", 6L);
  MASLISPU_Compiledf2(LINALGI_IVSVSUM, "IVSVSUM", 7L);
  MASLISPU_Compiledf2(LINALGI_IVSVPROD, "IVSVPROD", 8L);
  MASLISPU_Compiledf2(LINALGI_IVVPROD, "IVVPROD", 7L);
  MASLISPU_Compiledf2(LINALGI_IVSPROD, "IVSPROD", 7L);
  MASLISPU_Compiledp2v2(LINALGI_IVFRNV1, "IVFRNV1", 7L);
  MASLISPU_Compiledf1(LINALGI_IVFRNV, "IVFRNV", 6L);
  MASLISPU_Compiledp1(LINALGI_IMWRITE, "IMWRITE", 7L);
  MASLISPU_Compiledf1(LINALGI_IMMAX, "IMMAX", 5L);
  MASLISPU_Compiledf2(LINALGI_IMPROD, "IMPROD", 6L);
  MASLISPU_Compiledf2(LINALGI_IMSUM, "IMSUM", 5L);
  MASLISPU_Compiledf2(LINALGI_ISMPROD, "ISMPROD", 7L);
  MASLISPU_Compiledf2(LINALGI_IMDIF, "IMDIF", 5L);
  MASLISPU_Compiledp2v2(LINALGI_IMFRNM1, "IMFRNM1", 7L);
  MASLISPU_Compiledf1(LINALGI_IMFRNM, "IMFRNM", 6L);
  MASLISPU_Compiledf1(LINALGI_IMGE, "IMGE", 4L);
  MASLISPU_Compiledf1(LINALGI_IMDET, "IMDET", 5L);
  MASLISPU_Compiledf1(LINALGI_IMDETL, "IMDETL", 6L);
  MASLISPU_Compiledp1v2(LINALGI_IMGELUD, "IMGELUD", 7L);
  MASLISPU_Compiledf2(LINALGI_IMLT, "IMLT", 4L);
  MASLISPU_Compiledf2(LINALGI_IMUT, "IMUT", 4L);
  MASLISPU_Compiledf3(LINALGI_IMSDS, "IMSDS", 5L);
  MASLISPU_Compiledf1(LINALGI_RNMINVI, "RNMINVI", 7L);
  MASLISPU_Compiledf1(LINALGI_IMUNS, "IMUNS", 5L);
  MASLISPU_Compiledf2(SACLDIO_MAIPDE, "MAIPDE", 6L);
}

void BEGIN_MASLOADL()
{
  static BOOLEAN has_been_called = FALSE;

  if (!has_been_called) {
    has_been_called = TRUE;

    BEGIN_MASLISPU();
    BEGIN_LINALGRN();
    BEGIN_LINALGI();
    BEGIN_SACLDIO();

  }
}
