#include "SYSTEM_.h"

#ifndef DEFINITION_MASSTOR
#include "MASSTOR.h"
#endif

#ifndef DEFINITION_MASERR
#include "MASERR.h"
#endif

#ifndef DEFINITION_MASBIOS
#include "MASBIOS.h"
#endif

#ifndef DEFINITION_MASBIOSU
#include "MASBIOSU.h"
#endif

#ifndef DEFINITION_SACLIST
#include "SACLIST.h"
#endif

#ifndef DEFINITION_MASSYM2
#include "MASSYM2.h"
#endif

#ifndef DEFINITION_MASSYM
#include "MASSYM.h"
#endif

#ifndef DEFINITION_MASLISPU
#include "MASLISPU.h"
#endif

#ifndef DEFINITION_MASLISP
#include "MASLISP.h"
#endif

MASSTOR_LIST MASLISP_TDEF, MASLISP_DEFAULT, MASLISP_ARROW, MASLISP_ENV, MASLISP_NULL, MASLISP_WT, MASLISP_SCHLUSS, MASLISP_schluss, MASLISP_TINFO, MASLISP_EQS, MASLISP_NEQS, MASLISP_GTS, MASLISP_LTS, MASLISP_GEQ, MASLISP_LEQ, MASLISP_NOTS, MASLISP_UND, MASLISP_ODER, MASLISP_ADD, MASLISP_SUB, MASLISP_MUL, MASLISP_QUOT, MASLISP_REM, MASLISP_POW, MASLISP_QUOTE, MASLISP_SETQ, MASLISP_COND, MASLISP_LISTX, MASLISP_ASSIGN, MASLISP_READ, MASLISP_WRITE, MASLISP_DECREAD, MASLISP_DECWRITE, MASLISP_PROGN, MASLISP_VARS, MASLISP_IFS, MASLISP_WHL, MASLISP_RPT, MASLISP_STRNG, MASLISP_DE, MASLISP_DF, MASLISP_DM, MASLISP_DG, MASLISP_PROGA, MASLISP_GTO, MASLISP_LBEL, MASLISP_SETAV, MASLISP_ARY, MASLISP_ATM, MASLISP_RTN, MASLISP_ANY, MASLISP_UNIT, MASLISP_EXPOS, MASLISP_SPEC, MASLISP_SORT, MASLISP_SIG, MASLISP_IMPRT, MASLISP_IMPL, MASLISP_MODEL, MASLISP_MAP, MASLISP_AXIOM, MASLISP_RULE, MASLISP_WHEN, MASLISP_LAMBDA, MASLISP_FLAMBDA, MASLISP_MLAMBDA, MASLISP_GLAMBDA;
BOOLEAN MASLISP_trace;
BOOLEAN MASLISP_stricttyping;
MASSTOR_LIST MASLISP_REP, MASLISP_FER, MASLISP_FERx, MASLISP_FEL, MASLISP_FELx, MASLISP_CONVVAL, MASLISP_CONVDES;
CHAR MASLISP_rcsid [] = "$Id: MASLISP.md,v 1.3 1995/11/05 08:54:09 kredel Exp $";
CHAR MASLISP_copyright [] = "Copyright (c) 1989 - 1992 Universitaet Passau";

static BOOLEAN unwind;
static MASSTOR_LIST C_26_goto;
static MASSTOR_LIST PVAL, PDESC, PTYP;
static CHAR rcsidi [] = "$Id: MASLISP.mi,v 1.4 1995/11/05 08:55:36 kredel Exp $";
static CHAR copyrighti [] = "Copyright (c) 1989 - 1992 Universitaet Passau";
static void InitNames ARGS(());
static void InitLISP ARGS(());
static void InitENV ARGS(());


static void InitNames
# ifdef __STDC__
()
# else
()
# endif
{
  MASLISPU_Declare(&MASLISP_ARROW, "ARROW", 5L);
  MASLISPU_Declare(&MASLISP_ATM, "ATOM", 4L);
  MASLISPU_Declare(&MASLISP_ANY, "ANY", 3L);
  MASLISPU_Declare(&MASLISP_NULL, "NIL", 3L);
  MASLISPU_Declare(&MASLISP_WT, "T", 1L);
  MASLISPU_Declare(&PVAL, "VAL", 3L);
  MASLISPU_Declare(&PDESC, "DESC", 4L);
  MASLISPU_Declare(&PTYP, "TYPE", 4L);
  MASLISPU_Declare(&MASLISP_TDEF, "TYPEDEF", 7L);
  MASLISPU_Declare(&MASLISP_DEFAULT, "DEFAULT", 7L);
  MASLISPU_Declare(&MASLISP_LAMBDA, "LAMBDA", 6L);
  MASLISPU_Declare(&MASLISP_FLAMBDA, "FLAMBDA", 7L);
  MASLISPU_Declare(&MASLISP_MLAMBDA, "MLAMBDA", 7L);
  MASLISPU_Declare(&MASLISP_GLAMBDA, "GLAMBDA", 7L);
  MASLISPU_Declare(&MASLISP_RTN, "RETURN", 6L);
  MASLISPU_Declare(&MASLISP_FERx, "ForEachX", 8L);
  MASLISPU_Declare(&MASLISP_FELx, "ForEachY", 8L);
  MASLISPU_Declare(&MASLISP_SCHLUSS, "EXIT", 4L);
  MASSYM2_PUT(MASLISP_SCHLUSS, MASLISPU_EXTYP, MASLISP_FEXPR);
  MASLISPU_Declare(&MASLISP_schluss, "exit", 4L);
  MASSYM2_PUT(MASLISP_schluss, MASLISPU_EXTYP, MASLISP_FEXPR);
  MASLISPU_Declare(&MASLISP_QUOTE, "QUOTE", 5L);
  MASSYM2_PUT(MASLISP_QUOTE, MASLISPU_EXTYP, MASLISP_FEXPR);
  MASLISPU_Declare(&MASLISP_SETQ, "SETQ", 4L);
  MASSYM2_PUT(MASLISP_SETQ, MASLISPU_EXTYP, MASLISP_FEXPR);
  MASLISPU_Declare(&MASLISP_SETAV, "SETAV", 5L);
  MASSYM2_PUT(MASLISP_SETAV, MASLISPU_EXTYP, MASLISP_FEXPR);
  MASLISPU_Declare(&MASLISP_ASSIGN, "ASSIGN", 6L);
  MASSYM2_PUT(MASLISP_ASSIGN, MASLISPU_EXTYP, MASLISP_FEXPR);
  MASLISPU_Declare(&MASLISP_COND, "COND", 4L);
  MASSYM2_PUT(MASLISP_COND, MASLISPU_EXTYP, MASLISP_FEXPR);
  MASLISPU_Declare(&MASLISP_PROGN, "PROGN", 5L);
  MASSYM2_PUT(MASLISP_PROGN, MASLISPU_EXTYP, MASLISP_FEXPR);
  MASLISPU_Declare(&MASLISP_PROGA, "PROGA", 5L);
  MASSYM2_PUT(MASLISP_PROGA, MASLISPU_EXTYP, MASLISP_FEXPR);
  MASLISPU_Declare(&MASLISP_LBEL, "LABEL", 5L);
  MASSYM2_PUT(MASLISP_LBEL, MASLISPU_EXTYP, MASLISP_FEXPR);
  MASLISPU_Declare(&MASLISP_LISTX, "LIST", 4L);
  MASSYM2_PUT(MASLISP_LISTX, MASLISPU_EXTYP, MASLISP_FEXPR);
  MASLISPU_Declare(&MASLISP_DE, "DE", 2L);
  MASSYM2_PUT(MASLISP_DE, MASLISPU_EXTYP, MASLISP_FEXPR);
  MASLISPU_Declare(&MASLISP_DF, "DF", 2L);
  MASSYM2_PUT(MASLISP_DF, MASLISPU_EXTYP, MASLISP_FEXPR);
  MASLISPU_Declare(&MASLISP_DM, "DM", 2L);
  MASSYM2_PUT(MASLISP_DM, MASLISPU_EXTYP, MASLISP_FEXPR);
  MASLISPU_Declare(&MASLISP_DG, "DG", 2L);
  MASSYM2_PUT(MASLISP_DG, MASLISPU_EXTYP, MASLISP_FEXPR);
  MASLISPU_Declare(&MASLISP_IFS, "IF", 2L);
  MASSYM2_PUT(MASLISP_IFS, MASLISPU_EXTYP, MASLISP_FEXPR);
  MASLISPU_Declare(&MASLISP_WHL, "WHILE", 5L);
  MASSYM2_PUT(MASLISP_WHL, MASLISPU_EXTYP, MASLISP_FEXPR);
  MASLISPU_Declare(&MASLISP_RPT, "REPEAT", 6L);
  MASSYM2_PUT(MASLISP_RPT, MASLISPU_EXTYP, MASLISP_FEXPR);
  MASLISPU_Declare(&MASLISP_STRNG, "STRING", 6L);
  MASSYM2_PUT(MASLISP_STRNG, MASLISPU_EXTYP, MASLISP_FEXPR);
  MASLISPU_Declare(&MASLISP_VARS, "VAR", 3L);
  MASSYM2_PUT(MASLISP_VARS, MASLISPU_EXTYP, MASLISP_FEXPR);
  MASLISPU_Declare(&MASLISP_TINFO, "TYPEINFO", 8L);
  MASSYM2_PUT(MASLISP_TINFO, MASLISPU_EXTYP, MASLISP_FEXPR);
  MASLISPU_Declare(&MASLISP_ARY, "ARRAY", 5L);
  MASSYM2_PUT(MASLISP_ARY, MASLISPU_EXTYP, MASLISP_FEXPR);
  MASLISPU_Declare(&MASLISP_SPEC, "SPEC", 4L);
  MASSYM2_PUT(MASLISP_SPEC, MASLISPU_EXTYP, MASLISP_FEXPR);
  MASLISPU_Declare(&MASLISP_SORT, "SORT", 4L);
  MASSYM2_PUT(MASLISP_SORT, MASLISPU_EXTYP, MASLISP_FEXPR);
  MASLISPU_Declare(&MASLISP_SIG, "SIG", 3L);
  MASSYM2_PUT(MASLISP_SIG, MASLISPU_EXTYP, MASLISP_FEXPR);
  MASLISPU_Declare(&MASLISP_IMPRT, "IMPORT", 6L);
  MASSYM2_PUT(MASLISP_IMPRT, MASLISPU_EXTYP, MASLISP_FEXPR);
  MASLISPU_Declare(&MASLISP_EXPOS, "EXPOSE", 6L);
  MASSYM2_PUT(MASLISP_EXPOS, MASLISPU_EXTYP, MASLISP_FEXPR);
  MASLISPU_Declare(&MASLISP_UNIT, "UNIT", 4L);
  MASSYM2_PUT(MASLISP_UNIT, MASLISPU_EXTYP, MASLISP_FEXPR);
  MASLISPU_Declare(&MASLISP_IMPL, "IMPLEMENTATION", 14L);
  MASSYM2_PUT(MASLISP_IMPL, MASLISPU_EXTYP, MASLISP_FEXPR);
  MASLISPU_Declare(&MASLISP_MODEL, "MODEL", 5L);
  MASSYM2_PUT(MASLISP_MODEL, MASLISPU_EXTYP, MASLISP_FEXPR);
  MASLISPU_Declare(&MASLISP_MAP, "MAP", 3L);
  MASSYM2_PUT(MASLISP_MAP, MASLISPU_EXTYP, MASLISP_FEXPR);
  MASLISPU_Declare(&MASLISP_AXIOM, "AXIOMS", 6L);
  MASSYM2_PUT(MASLISP_AXIOM, MASLISPU_EXTYP, MASLISP_FEXPR);
  MASLISPU_Declare(&MASLISP_RULE, "RULE", 4L);
  MASSYM2_PUT(MASLISP_RULE, MASLISPU_EXTYP, MASLISP_FEXPR);
  MASLISPU_Declare(&MASLISP_WHEN, "WHEN", 4L);
  MASSYM2_PUT(MASLISP_WHEN, MASLISPU_EXTYP, MASLISP_FEXPR);
  MASLISPU_Declare(&MASLISP_REP, "REP", 3L);
  MASSYM2_PUT(MASLISP_REP, MASLISPU_EXTYP, MASLISP_FEXPR);
  MASLISPU_Declare(&MASLISP_EQS, "EQ", 2L);
  MASSYM2_PUT(MASLISP_EQS, MASLISPU_EXTYP, MASLISPU_EXPR);
  MASLISPU_Declare(&MASLISP_NEQS, "NE", 2L);
  MASSYM2_PUT(MASLISP_NEQS, MASLISPU_EXTYP, MASLISPU_EXPR);
  MASLISPU_Declare(&MASLISP_GTS, "GT", 2L);
  MASSYM2_PUT(MASLISP_GTS, MASLISPU_EXTYP, MASLISPU_EXPR);
  MASLISPU_Declare(&MASLISP_LTS, "LT", 2L);
  MASSYM2_PUT(MASLISP_LTS, MASLISPU_EXTYP, MASLISPU_EXPR);
  MASLISPU_Declare(&MASLISP_LEQ, "LEQ", 3L);
  MASSYM2_PUT(MASLISP_LEQ, MASLISPU_EXTYP, MASLISPU_EXPR);
  MASLISPU_Declare(&MASLISP_GEQ, "GEQ", 3L);
  MASSYM2_PUT(MASLISP_GEQ, MASLISPU_EXTYP, MASLISPU_EXPR);
  MASLISPU_Declare(&MASLISP_UND, "AND", 3L);
  MASSYM2_PUT(MASLISP_UND, MASLISPU_EXTYP, MASLISPU_EXPR);
  MASLISPU_Declare(&MASLISP_ODER, "OR", 2L);
  MASSYM2_PUT(MASLISP_ODER, MASLISPU_EXTYP, MASLISPU_EXPR);
  MASLISPU_Declare(&MASLISP_NOTS, "NOT", 3L);
  MASSYM2_PUT(MASLISP_NOTS, MASLISPU_EXTYP, MASLISPU_EXPR);
  MASLISPU_Declare(&MASLISP_ADD, "ADD", 3L);
  MASSYM2_PUT(MASLISP_ADD, MASLISPU_EXTYP, MASLISPU_EXPR);
  MASLISPU_Declare(&MASLISP_SUB, "SUB", 3L);
  MASSYM2_PUT(MASLISP_SUB, MASLISPU_EXTYP, MASLISPU_EXPR);
  MASLISPU_Declare(&MASLISP_MUL, "MUL", 3L);
  MASSYM2_PUT(MASLISP_MUL, MASLISPU_EXTYP, MASLISPU_EXPR);
  MASLISPU_Declare(&MASLISP_QUOT, "QUOT", 4L);
  MASSYM2_PUT(MASLISP_QUOT, MASLISPU_EXTYP, MASLISPU_EXPR);
  MASLISPU_Declare(&MASLISP_REM, "REM", 3L);
  MASSYM2_PUT(MASLISP_REM, MASLISPU_EXTYP, MASLISPU_EXPR);
  MASLISPU_Declare(&MASLISP_RTN, "RETURN", 6L);
  MASSYM2_PUT(MASLISP_RTN, MASLISPU_EXTYP, MASLISPU_EXPR);
  MASLISPU_Declare(&MASLISP_GTO, "GOTO", 4L);
  MASSYM2_PUT(MASLISP_GTO, MASLISPU_EXTYP, MASLISPU_EXPR);
  MASLISPU_Declare(&MASLISP_FER, "ForEachinRep", 12L);
  MASSYM2_PUT(MASLISP_FER, MASLISPU_EXTYP, MASLISPU_EXPR);
  MASLISPU_Declare(&MASLISP_FEL, "ForEachinList", 13L);
  MASSYM2_PUT(MASLISP_FEL, MASLISPU_EXTYP, MASLISPU_EXPR);
  MASLISPU_Declare(&MASLISP_CONVVAL, "CONVVAL", 7L);
  MASSYM2_PUT(MASLISP_CONVVAL, MASLISPU_EXTYP, MASLISPU_EXPR);
  MASLISPU_Declare(&MASLISP_CONVDES, "CONVDES", 7L);
  MASSYM2_PUT(MASLISP_CONVDES, MASLISPU_EXTYP, MASLISPU_EXPR);
  MASLISPU_Declare(&MASLISP_READ, "READ", 4L);
  MASLISPU_Declare(&MASLISP_WRITE, "WRITE", 5L);
  MASLISPU_Declare(&MASLISP_DECREAD, "DECREAD", 7L);
  MASLISPU_Declare(&MASLISP_DECWRITE, "DECWRITE", 8L);
}

static void InitLISP
# ifdef __STDC__
()
# else
()
# endif
{
  InitNames();
  InitENV();
  MASLISPU_Compiledp0(InitENV, "NEW", 3L);
  MASLISPU_Declare(&MASLISP_POW, "POW", 3L);
}

static void InitENV
# ifdef __STDC__
()
# else
()
# endif
{
  MASLISP_ENV = MASSTOR_SIL;
  MASSTOR_LISTVAR(&MASLISP_ENV);
  MASLISP_ENV = SACLIST_COMP2(MASLISP_NULL, MASSTOR_SIL, MASLISP_ENV);
  unwind = FALSE;
  MASLISP_stricttyping = FALSE;
  MASLISP_trace = FALSE;
}

MASSTOR_LIST MASLISP_ECENV
# ifdef __STDC__
(MASSTOR_LIST ENV)
# else
(ENV)
MASSTOR_LIST ENV;
# endif
{
  return SACLIST_LIST2(MASSYM_NOSHOW, ENV);
}

MASSTOR_LIST MASLISP_DCENV
# ifdef __STDC__
(MASSTOR_LIST E)
# else
(E)
MASSTOR_LIST E;
# endif
{
  return SACLIST_SECOND(E);
}

void MASLISP_SETV
# ifdef __STDC__
(MASSTOR_LIST V, MASSTOR_LIST C_30_A, MASSTOR_LIST *ENV)
# else
(V, C_30_A, ENV)
MASSTOR_LIST V, C_30_A;
MASSTOR_LIST *ENV;
# endif
{
  MASSTOR_LIST EP, Z, t, n;

  if (!MASSYM2_SYMBOL(V)) {
    MASSYM_UWRIT1(V);
    MASBIOS_SWRITE(":=", 2L);
    MASSYM_UWRITE(C_30_A);
    MASERR_ERROR(MASERR_severe, "SETV: invalid as variable.", 26L);
    return;
  }
  EP = MASSYM2_ASSOC(V, *ENV);
  if (EP != MASSTOR_SIL) {
    MASSTOR_SFIRST(EP, C_30_A);
  } else {
    *ENV = SACLIST_COMP2(V, C_30_A, *ENV);
  }
}

BOOLEAN MASLISP_EXTENDENV
# ifdef __STDC__
(MASSTOR_LIST C_29_A, MASSTOR_LIST X, MASSTOR_LIST *ENV)
# else
(C_29_A, X, ENV)
MASSTOR_LIST C_29_A, X;
MASSTOR_LIST *ENV;
# endif
{
  MASSTOR_LIST XP, AP, Y, Z, B;

  Z = *ENV;
  XP = X;
  AP = C_29_A;
  while (AP != MASSTOR_SIL && XP != MASSTOR_SIL) {
    MASSTOR_ADV(AP, &B, &AP);
    MASSTOR_ADV(XP, &Y, &XP);
    Z = SACLIST_COMP2(B, Y, Z);
  }
  if (AP != MASSTOR_SIL || XP != MASSTOR_SIL) {
    MASSYM_UWRITE(AP);
    MASSYM_UWRITE(XP);
    MASERR_ERROR(MASERR_severe, "EXTENDENV: argument number mismatch.", 36L);
    return FALSE;
  }
  *ENV = Z;
  return TRUE;
}

void MASLISP_COPYTOENV
# ifdef __STDC__
(MASSTOR_LIST V, MASSTOR_LIST EP, MASSTOR_LIST *ENV)
# else
(V, EP, ENV)
MASSTOR_LIST V, EP;
MASSTOR_LIST *ENV;
# endif
{
  MASSTOR_LIST D, v;

  if (MASLISP_trace) {
    MASBIOS_SWRITE("IMP/EXP:   ", 11L);
    MASSYM_UWRITE(V);
    MASBIOS_SWRITE("COPYTOENV: ", 11L);
  }
  while (V != MASSTOR_SIL) {
    MASSTOR_ADV(V, &v, &V);
    D = MASSYM2_ASSOC(v, EP);
    if (D != MASSTOR_SIL) {
      D = MASSTOR_FIRST(D);
      if (MASLISP_trace) {
        MASSYM_UWRIT1(v);
        MASBIOS_SWRITE(" ", 1L);
      }
      MASLISP_SETV(v, D, ENV);
    }
  }
  if (MASLISP_trace) {
    MASBIOS_BLINES(0);
  }
}

BOOLEAN MASLISP_SPECIALFORM
# ifdef __STDC__
(MASSTOR_LIST S)
# else
(S)
MASSTOR_LIST S;
# endif
{
  BOOLEAN t;
  MASSTOR_LIST F, Y;

  t = FALSE;
  if (MASSYM_ELEMP(S)) {
    return t;
  }
  if (MASSYM2_SYMBOL(S)) {
    Y = MASSYM2_GET(S, MASLISPU_EXTYP);
    if (Y == MASLISP_FEXPR || Y == MASLISP_MACRO) {
      t = TRUE;
    }
    return t;
  }
  F = MASSTOR_FIRST(S);
  if (F == MASLISP_FLAMBDA) {
    return TRUE;
  }
  if (F == MASLISP_MLAMBDA) {
    return TRUE;
  }
  return t;
}

BOOLEAN MASLISP_LAMBDAP
# ifdef __STDC__
(MASSTOR_LIST S)
# else
(S)
MASSTOR_LIST S;
# endif
{
  BOOLEAN t;

  t = FALSE;
  if (MASSYM_ELEMP(S)) {
    return FALSE;
  }
  if (!MASSYM2_SYMBOL(S)) {
    return FALSE;
  }
  t = TRUE;
  if (S == MASLISP_LAMBDA) {
    return t;
  }
  if (S == MASLISP_FLAMBDA) {
    return t;
  }
  if (S == MASLISP_MLAMBDA) {
    return t;
  }
  if (S == MASLISP_GLAMBDA) {
    return t;
  }
  return FALSE;
}

BOOLEAN MASLISP_SEXPRP
# ifdef __STDC__
(MASSTOR_LIST X)
# else
(X)
MASSTOR_LIST X;
# endif
{
  MASSTOR_LIST T, Y;

  if (MASSYM_ELEMP(X)) {
    return FALSE;
  }
  Y = MASSTOR_FIRST(X);
  if (MASSYM2_SYMBOL(Y)) {
    T = MASSYM2_GET(Y, MASLISPU_EXTYP);
    if (T != MASSTOR_SIL) {
      return TRUE;
    }
    return FALSE;
  }
  if (MASLISP_LAMBDAP(MASSTOR_FIRST(Y))) {
    return TRUE;
  }
  return FALSE;
}

MASSTOR_LIST MASLISP_DEFE
# ifdef __STDC__
(MASSTOR_LIST X, MASSTOR_LIST *ENV)
# else
(X, ENV)
MASSTOR_LIST X;
MASSTOR_LIST *ENV;
# endif
{
  MASSTOR_LIST XP, Y, Z;

  Z = X;
  if (X == MASSTOR_SIL) {
    return MASSTOR_SIL;
  }
  MASSTOR_ADV(X, &Y, &XP);
  if (!MASSYM2_SYMBOL(Y)) {
    MASSYM_UWRITE(Y);
    MASERR_ERROR(MASERR_severe, "DEFE: invalid as function name.", 31L);
    return MASSTOR_SIL;
  }
  MASSYM2_PUT(Y, MASLISPU_EXTYP, MASLISPU_EXPR);
  Z = MASSTOR_COMP(MASLISP_LAMBDA, XP);
  MASLISP_SETV(Y, Z, ENV);
  return Y;
}

MASSTOR_LIST MASLISP_DEFF
# ifdef __STDC__
(MASSTOR_LIST X, MASSTOR_LIST *ENV)
# else
(X, ENV)
MASSTOR_LIST X;
MASSTOR_LIST *ENV;
# endif
{
  MASSTOR_LIST XP, Y, Z;

  if (X == MASSTOR_SIL) {
    return MASSTOR_SIL;
  }
  MASSTOR_ADV(X, &Y, &XP);
  if (!MASSYM2_SYMBOL(Y)) {
    MASSYM_UWRITE(Y);
    MASERR_ERROR(MASERR_severe, "DEFF: invalid as function name.", 31L);
    return MASSTOR_SIL;
  }
  MASSYM2_PUT(Y, MASLISPU_EXTYP, MASLISPU_EXPR);
  Z = MASSTOR_COMP(MASLISP_FLAMBDA, XP);
  MASLISP_SETV(Y, Z, ENV);
  return Y;
}

MASSTOR_LIST MASLISP_DEFM
# ifdef __STDC__
(MASSTOR_LIST X, MASSTOR_LIST *ENV)
# else
(X, ENV)
MASSTOR_LIST X;
MASSTOR_LIST *ENV;
# endif
{
  MASSTOR_LIST XP, Y, Z;

  if (X == MASSTOR_SIL) {
    return MASSTOR_SIL;
  }
  MASSTOR_ADV(X, &Y, &XP);
  if (!MASSYM2_SYMBOL(Y)) {
    MASSYM_UWRITE(Y);
    MASERR_ERROR(MASERR_severe, "DEFM: invalid as function name.", 31L);
    return MASSTOR_SIL;
  }
  MASSYM2_PUT(Y, MASLISPU_EXTYP, MASLISP_MACRO);
  Z = MASSTOR_COMP(MASLISP_MLAMBDA, XP);
  MASLISP_SETV(Y, Z, ENV);
  return Y;
}

MASSTOR_LIST MASLISP_DEFMAP
# ifdef __STDC__
(MASSTOR_LIST X, MASSTOR_LIST *ENV)
# else
(X, ENV)
MASSTOR_LIST X;
MASSTOR_LIST *ENV;
# endif
{
  MASSTOR_LIST MP, XP, Y, Z, L, R, M, I, IP, E, N;

  if (X == MASSTOR_SIL) {
    return MASSTOR_SIL;
  }
  MASSTOR_ADV(X, &L, &XP);
  MASSTOR_ADV(L, &Y, &L);
  L = MASSTOR_FIRST(L);
  if (!MASSYM2_SYMBOL(Y)) {
    MASSYM_UWRITE(Y);
    MASERR_ERROR(MASERR_severe, "DEFMAP: invalid as function name.", 33L);
    return MASSTOR_SIL;
  }
  IP = MASSTOR_SIL;
  Z = MASSYM2_ASSOC(Y, *ENV);
  if (Z != MASSTOR_SIL) {
    Z = MASSTOR_FIRST(Z);
    if (Z != MASSTOR_SIL) {
      if (MASSTOR_FIRST(Z) == MASLISP_GLAMBDA) {
        Z = MASSTOR_RED(Z);
      } else if (MASLISP_LAMBDAP(MASSTOR_FIRST(Z))) {
        IP = SACLIST_LIST2(Z, MASLISP_ECENV(*ENV));
        Z = MASSTOR_SIL;
      } else {
        Z = MASSTOR_SIL;
        MASSYM_UWRITE(Y);
        MASERR_ERROR(MASERR_severe, "DEFMAP: variable defined generic.", 33L);
      }
    }
  }
  if (Z == MASSTOR_SIL) {
    N = Y;
    M = MASSTOR_SIL;
    I = IP;
    E = MASSTOR_SIL;
    MASSYM2_PUT(Y, MASLISPU_EXTYP, MASLISP_GENERIC);
  } else {
    SACLIST_FIRST4(Z, &N, &M, &I, &E);
  }
  MP = MASSYM2_ASSOCQ(L, M);
  if (MP != MASSTOR_SIL) {
    MASSTOR_SFIRST(MP, XP);
  } else {
    XP = SACLIST_LIST2(L, XP);
    M = SACLIST_CCONC(M, XP);
  }
  Z = SACLIST_LIST4(N, M, I, E);
  Z = MASSTOR_COMP(MASLISP_GLAMBDA, Z);
  MASLISP_SETV(Y, Z, ENV);
  return Y;
}

MASSTOR_LIST MASLISP_DEFPROC
# ifdef __STDC__
(MASSTOR_LIST X, MASSTOR_LIST *ENV)
# else
(X, ENV)
MASSTOR_LIST X;
MASSTOR_LIST *ENV;
# endif
{
  MASSTOR_LIST XP, Y, Z, M, I, IP, E, N;

  if (X == MASSTOR_SIL) {
    return MASSTOR_SIL;
  }
  MASSTOR_ADV(X, &Y, &XP);
  if (!MASSYM2_SYMBOL(Y)) {
    MASSYM_UWRITE(Y);
    MASERR_ERROR(MASERR_severe, "DEFPROC: invalid as function name.", 34L);
    return MASSTOR_SIL;
  }
  IP = MASSTOR_SIL;
  Z = MASSYM2_ASSOC(Y, *ENV);
  if (Z != MASSTOR_SIL) {
    Z = MASSTOR_FIRST(Z);
    if (Z != MASSTOR_SIL) {
      if (MASSTOR_FIRST(Z) == MASLISP_GLAMBDA) {
        Z = MASSTOR_RED(Z);
      } else if (MASLISP_LAMBDAP(MASSTOR_FIRST(Z))) {
        IP = SACLIST_LIST2(Z, MASLISP_ECENV(*ENV));
        Z = MASSTOR_SIL;
      } else {
        Z = MASSTOR_SIL;
        MASSYM_UWRITE(Y);
        MASERR_ERROR(MASERR_severe, "DEFPROC: variable defined generic.", 34L);
      }
    }
  }
  if (Z == MASSTOR_SIL) {
    N = Y;
    M = MASSTOR_SIL;
    I = IP;
    E = MASSTOR_SIL;
    MASSYM2_PUT(Y, MASLISPU_EXTYP, MASLISP_GENERIC);
  } else {
    SACLIST_FIRST4(Z, &N, &M, &I, &E);
  }
  XP = MASSTOR_COMP(MASLISP_LAMBDA, XP);
  I = SACLIST_LIST2(XP, MASLISP_ECENV(*ENV));
  Z = SACLIST_LIST4(N, M, I, E);
  Z = MASSTOR_COMP(MASLISP_GLAMBDA, Z);
  MASLISP_SETV(Y, Z, ENV);
  return Y;
}

MASSTOR_LIST MASLISP_DEFRULE
# ifdef __STDC__
(MASSTOR_LIST X, MASSTOR_LIST *ENV)
# else
(X, ENV)
MASSTOR_LIST X;
MASSTOR_LIST *ENV;
# endif
{
  MASSTOR_LIST XP, Y, Z, M, I, IP, E, N, L, R;

  if (X == MASSTOR_SIL) {
    return MASSTOR_SIL;
  }
  MASSTOR_ADV(X, &L, &XP);
  Y = MASSTOR_FIRST(L);
  if (MASSYM_ATOM(Y)) {
    MASSYM_UWRITE(Y);
    MASERR_ERROR(MASERR_severe, "DEFRULE: atom invalid as function name.", 39L);
    return MASSTOR_SIL;
  }
  IP = MASSTOR_SIL;
  Z = MASSYM2_ASSOC(Y, *ENV);
  if (Z != MASSTOR_SIL) {
    Z = MASSTOR_FIRST(Z);
    if (Z != MASSTOR_SIL) {
      if (MASSTOR_FIRST(Z) == MASLISP_GLAMBDA) {
        Z = MASSTOR_RED(Z);
      } else if (MASLISP_LAMBDAP(MASSTOR_FIRST(Z))) {
        IP = SACLIST_LIST2(Z, MASLISP_ECENV(*ENV));
        Z = MASSTOR_SIL;
      } else {
        Z = MASSTOR_SIL;
        MASSYM_UWRITE(Y);
        MASERR_ERROR(MASERR_severe, "DEFRULE: variable defined generic.", 34L);
      }
    }
  }
  if (Z == MASSTOR_SIL) {
    N = Y;
    M = MASSTOR_SIL;
    I = IP;
    E = MASSTOR_SIL;
    MASSYM2_PUT(Y, MASLISPU_EXTYP, MASLISP_GENERIC);
  } else {
    SACLIST_FIRST4(Z, &N, &M, &I, &E);
  }
  E = SACLIST_CCONC(E, MASSTOR_LIST1(X));
  Z = SACLIST_LIST4(N, M, I, E);
  Z = MASSTOR_COMP(MASLISP_GLAMBDA, Z);
  MASLISP_SETV(Y, Z, ENV);
  return Y;
}

MASSTOR_LIST MASLISP_DSPEC
# ifdef __STDC__
(MASSTOR_LIST X, MASSTOR_LIST *ENV)
# else
(X, ENV)
MASSTOR_LIST X;
MASSTOR_LIST *ENV;
# endif
{
  MASSTOR_LIST XP, Y, Z;

  if (X == MASSTOR_SIL) {
    return MASSTOR_SIL;
  }
  MASSTOR_ADV(X, &Y, &XP);
  if (!MASSYM2_SYMBOL(Y)) {
    MASSYM_UWRITE(Y);
    MASERR_ERROR(MASERR_severe, "DSPEC: invalid as unit name.", 28L);
    return MASSTOR_SIL;
  }
  MASSYM2_PUT(Y, MASLISPU_EXTYP, MASLISP_FEXPR);
  Z = SACLIST_COMP2(MASLISP_SPEC, Y, XP);
  Z = SACLIST_LIST4(MASLISP_UNIT, Y, MASSTOR_FIRST(XP), Z);
  MASLISP_SETV(Y, Z, ENV);
  return Y;
}

MASSTOR_LIST MASLISP_DMIA
# ifdef __STDC__
(MASSTOR_LIST X, MASSTOR_LIST *ENV)
# else
(X, ENV)
MASSTOR_LIST X;
MASSTOR_LIST *ENV;
# endif
{
  MASSTOR_LIST XPP, XP, Y, Z, W, T;

  if (X == MASSTOR_SIL) {
    return MASSTOR_SIL;
  }
  SACLIST_ADV2(X, &T, &Y, &XP);
  if (!MASSYM2_SYMBOL(Y)) {
    MASSYM_UWRITE(Y);
    MASERR_ERROR(MASERR_severe, "DMIA: invalid as unit name.", 27L);
    return MASSTOR_SIL;
  }
  W = MASSYM2_ASSOC(Y, *ENV);
  if (W == MASSTOR_SIL) {
    MASSYM_UWRITE(Y);
    MASERR_ERROR(MASERR_severe, "DMIA: no specification defined.", 31L);
    return MASSTOR_SIL;
  }
  W = MASSTOR_FIRST(W);
  if (MASSTOR_FIRST(W) != MASLISP_UNIT) {
    MASSYM_UWRITE(Y);
    MASERR_ERROR(MASERR_severe, "DMIA: no unit defined.", 22L);
    return MASSTOR_SIL;
  }
  Z = MASSTOR_LIST1(X);
  Z = SACLIST_CONC(W, Z);
  return Y;
}

MASSTOR_LIST MASLISP_TYPEOF
# ifdef __STDC__
(MASSTOR_LIST X)
# else
(X)
MASSTOR_LIST X;
# endif
{
  MASSTOR_LIST D, DS, XP, x, y, xs, d, XS, Y, YS, W, C_28_A;

  Y = MASSTOR_SIL;
  D = MASSTOR_SIL;
  if (MASSYM_ATOM(X)) {
    XS = MASSTOR_LIST1(X);
    Y = MASLISP_ATM;
    return SACLIST_LIST3(XS, Y, D);
  }
  if (MASSYM2_SYMBOL(X)) {
    Y = MASSTOR_SIL;
    D = MASSTOR_SIL;
    Y = MASSYM2_GET(X, MASLISP_SORT);
    if (Y != MASSTOR_SIL) {
      return SACLIST_LIST3(MASSTOR_SIL, X, D);
    }
    Y = MASSYM2_GET(X, MASLISP_TDEF);
    if (Y > MASSTOR_SIL && !MASSYM2_SYMBOL(Y)) {
      SACLIST_FIRST2(Y, &Y, &D);
    }
    X = MASSTOR_LIST1(X);
    if (Y != MASSTOR_SIL) {
      Y = MASSTOR_LIST1(Y);
    }
    if (D != MASSTOR_SIL) {
      D = MASSTOR_LIST1(D);
    }
    return SACLIST_LIST3(X, Y, D);
  }
  if (MASSTOR_FIRST(X) == MASLISP_TINFO) {
    XS = MASLISP_VALOFTAG(X);
    Y = MASLISP_TYPOFTAG(X);
    D = MASLISP_DECOFTAG(X);
    XS = MASSTOR_LIST1(XS);
    if (Y != MASSTOR_SIL) {
      Y = MASSTOR_LIST1(Y);
    }
    if (D != MASSTOR_SIL) {
      D = MASSTOR_LIST1(D);
    }
    return SACLIST_LIST3(XS, Y, D);
  }
  if (MASSYM2_GET(MASSTOR_FIRST(X), MASLISP_SORT) != MASSTOR_SIL) {
    SACLIST_FIRST2(X, &X, &D);
    if (X != MASSTOR_SIL) {
      X = MASSTOR_LIST1(X);
    }
    if (D != MASSTOR_SIL) {
      D = MASSTOR_LIST1(D);
    }
    return SACLIST_LIST3(MASSTOR_SIL, X, D);
  }
  C_28_A = MASSYM2_GET(MASSTOR_FIRST(X), MASLISP_ARROW);
  if (C_28_A != MASSTOR_SIL) {
    XS = X;
    D = MASSTOR_SIL;
    SACLIST_FIRST3(C_28_A, &x, &y, &Y);
    if (Y != MASSTOR_SIL) {
      Y = MASSTOR_FIRST(Y);
    }
    XS = MASSTOR_LIST1(XS);
    if (Y != MASSTOR_SIL) {
      Y = MASSTOR_LIST1(Y);
    }
    if (D != MASSTOR_SIL) {
      D = MASSTOR_LIST1(D);
    }
    return SACLIST_LIST3(XS, Y, D);
  }
  XP = X;
  XS = MASSTOR_SIL;
  while (XP != MASSTOR_SIL) {
    MASSTOR_ADV(XP, &x, &XP);
    W = MASLISP_TYPEOF(x);
    SACLIST_FIRST3(W, &xs, &y, &d);
    XS = SACLIST_CCONC(XS, xs);
    Y = SACLIST_CCONC(Y, y);
    D = SACLIST_CCONC(D, d);
  }
  return SACLIST_LIST3(XS, Y, D);
}

MASSTOR_LIST MASLISP_TAG
# ifdef __STDC__
(MASSTOR_LIST V, MASSTOR_LIST T)
# else
(V, T)
MASSTOR_LIST V, T;
# endif
{
  MASSTOR_LIST O;

  if (MASSYM_ELEMP(T)) {
    MASSYM_UWRITE(T);
    MASERR_ERROR(MASERR_severe, "TAG: invalid as type indicator.", 31L);
    return MASSTOR_SIL;
  }
  O = SACLIST_LIST3(MASLISP_TINFO, V, T);
  return O;
}

MASSTOR_LIST MASLISP_VALOFTAG
# ifdef __STDC__
(MASSTOR_LIST L)
# else
(L)
MASSTOR_LIST L;
# endif
{
  if (MASSYM_ATOM(L)) {
    return L;
  }
  if (MASSTOR_FIRST(L) != MASLISP_TINFO) {
    return L;
  }
  return SACLIST_SECOND(L);
}

MASSTOR_LIST MASLISP_TYPOFTAG
# ifdef __STDC__
(MASSTOR_LIST L)
# else
(L)
MASSTOR_LIST L;
# endif
{
  MASSTOR_LIST T;

  if (MASSYM_ATOM(L)) {
    return MASSTOR_SIL;
  }
  if (MASSTOR_FIRST(L) != MASLISP_TINFO) {
    return MASSTOR_SIL;
  }
  T = SACLIST_THIRD(L);
  T = MASSTOR_FIRST(T);
  return T;
}

MASSTOR_LIST MASLISP_DECOFTAG
# ifdef __STDC__
(MASSTOR_LIST L)
# else
(L)
MASSTOR_LIST L;
# endif
{
  MASSTOR_LIST D, T;

  if (MASSYM_ATOM(L)) {
    return MASSTOR_SIL;
  }
  if (MASSTOR_FIRST(L) != MASLISP_TINFO) {
    return MASSTOR_SIL;
  }
  T = SACLIST_THIRD(L);
  T = MASSTOR_RED(T);
  if (T != MASSTOR_SIL) {
    D = MASSTOR_FIRST(T);
  } else {
    D = MASSTOR_SIL;
  }
  return D;
}

MASSTOR_LIST MASLISP_GENPL
# ifdef __STDC__
(MASSTOR_LIST P, MASSTOR_LIST V, MASSTOR_LIST T, MASSTOR_LIST D)
# else
(P, V, T, D)
MASSTOR_LIST P, V, T, D;
# endif
{
  MASSTOR_LIST L, p, x;

  L = MASSTOR_SIL;
  while (P != MASSTOR_SIL) {
    MASSTOR_ADV(P, &p, &P);
    if (p == PVAL) {
      MASSTOR_ADV(V, &x, &V);
      L = MASSTOR_COMP(x, L);
    } else if (p == PDESC) {
      MASSTOR_ADV(D, &x, &D);
      L = MASSTOR_COMP(x, L);
    } else if (p == PTYP) {
      MASSTOR_ADV(T, &x, &T);
      L = MASSTOR_COMP(x, L);
    } else {
      MASSYM_UWRITE(p);
      MASERR_ERROR(MASERR_severe, "GENPL: invalid pattern skipped.", 31L);
    }
  }
  L = MASSTOR_INV(L);
  return L;
}

MASSTOR_LIST MASLISP_GENTE
# ifdef __STDC__
(MASSTOR_LIST Z, MASSTOR_LIST N, MASSTOR_LIST D)
# else
(Z, N, D)
MASSTOR_LIST Z, N, D;
# endif
{
  MASSTOR_LIST C_27_A;

  C_27_A = MASSYM2_GET(N, MASLISP_ARROW);
  if (C_27_A == MASSTOR_SIL) {
    MASSYM_UWRITE(N);
    MASERR_ERROR(MASERR_severe, "GENTE: no signature defined.", 28L);
    return Z;
  }
  C_27_A = SACLIST_THIRD(C_27_A);
  if (C_27_A == MASSTOR_SIL) {
    return Z;
  }
  if (MASSTOR_RED(C_27_A) == MASSTOR_SIL) {
    C_27_A = MASSTOR_FIRST(C_27_A);
  }
  if (C_27_A == MASSTOR_SIL) {
    return Z;
  }
  C_27_A = SACLIST_LIST2(C_27_A, D);
  Z = MASLISP_TAG(Z, C_27_A);
  Z = MASSTOR_COMP(MASLISP_LISTX, Z);
  return Z;
}

void BEGIN_MASLISP()
{
  static BOOLEAN has_been_called = FALSE;

  if (!has_been_called) {
    has_been_called = TRUE;

    BEGIN_MASSTOR();
    BEGIN_MASSTOR();
    BEGIN_MASERR();
    BEGIN_MASBIOS();
    BEGIN_MASBIOSU();
    BEGIN_SACLIST();
    BEGIN_MASSYM2();
    BEGIN_MASSYM();
    BEGIN_MASLISPU();

    InitLISP();
  }
}
