#define DEFINITION_MASLOG

#ifndef DEFINITION_MASSTOR
#include "MASSTOR.h"
#endif

#ifndef DEFINITION_MASLISPU
#include "MASLISPU.h"
#endif

#ifndef DEFINITION_MLOGBASE
#include "MLOGBASE.h"
#endif

extern CHAR MASLOG_rcsid[];
extern CHAR MASLOG_copyright[];
extern MASSTOR_LIST MASLOG_FORMKPOS ARGS((MASSTOR_LIST phi, MASSTOR_LIST pref, MASLISPU_PROCF1 bbmkneg));
extern MASSTOR_LIST MASLOG_FORMKDNF ARGS((MASSTOR_LIST phi, MASLISPU_PROCF1 bbmkneg));
extern MASSTOR_LIST MASLOG_FORMKCNF ARGS((MASSTOR_LIST phi, MASLISPU_PROCF1 bbmkneg));
extern MASSTOR_LIST MASLOG_FORMKPRENEX ARGS((MASSTOR_LIST phi, MASSTOR_LIST pref));
extern MASSTOR_LIST MASLOG_FORMKPRENEXI ARGS((MASSTOR_LIST phi, MASSTOR_LIST pref));
extern MASSTOR_LIST MASLOG_FORMKPRENEX1 ARGS((MASSTOR_LIST phi));
extern MASSTOR_LIST MASLOG_FORIMQB ARGS((MASSTOR_LIST phi));
extern MASSTOR_LIST MASLOG_FORSUBSTVAR ARGS((MASSTOR_LIST phi, MASSTOR_LIST old, MASSTOR_LIST new, MASLISPU_PROCF3 bbsubstvar));
extern MASSTOR_LIST MASLOG_FORMKVD ARGS((MASSTOR_LIST formula, MASLISPU_PROCF3 bbsubstvar, MASLISPU_PROCF1 bblsvars));
extern MASSTOR_LIST MASLOG_FORSMPL ARGS((MASSTOR_LIST phi, MASLISPU_PROCF1 bbsmpl, MASLISPU_PROCF1 bbmkneg));
extern MASSTOR_LIST MASLOG_FORSIMPLIFY ARGS((MASSTOR_LIST phi, MASLISPU_PROCF1 smart, MASLISPU_PROCF1 bbsmpl, MASLISPU_PROCF1 bbmkneg));
extern MASSTOR_LIST MASLOG_FORSIMPLIFYP ARGS((MASSTOR_LIST phi, MASSTOR_LIST maxlevel, MASLISPU_PROCF1 smart, MASLISPU_PROCF1 bbsmpl, MASLISPU_PROCF1 bbmkneg));
extern MASSTOR_LIST MASLOG_FORPREPQE ARGS((MASSTOR_LIST phi, MASLISPU_PROCF1 bbmkneg));
extern MASSTOR_LIST MASLOG_FORELIMXOPS ARGS((MASSTOR_LIST phi, MASSTOR_LIST pref));
extern MASSTOR_LIST MASLOG_FORREPAFS ARGS((MASSTOR_LIST phi, MASSTOR_LIST rep));
extern MASSTOR_LIST MASLOG_FORAPPLYAT ARGS((MASSTOR_LIST phi, MASLISPU_PROCF1 dosomething));
extern MASSTOR_LIST MASLOG_FORAPPLYATF2 ARGS((MASSTOR_LIST phi, MASSTOR_LIST param1, MASLISPU_PROCF2 dosomething));
extern MASSTOR_LIST MASLOG_FORCOUNTAF ARGS((MASSTOR_LIST phi));
extern BOOLEAN MASLOG_FORCONTBDVAR ARGS((MASSTOR_LIST phi, MASSTOR_LIST svar));
extern BOOLEAN MASLOG_FORCONTVAR ARGS((MASSTOR_LIST phi, MASSTOR_LIST svar, MLOGBASE_PROCFB2 bbcontvar));
extern void BEGIN_MASLOG();
