#define DEFINITION_MASO

#ifndef DEFINITION_MASSTOR
#include "MASSTOR.h"
#endif

extern CHAR MASO_rcsid[];
extern CHAR MASO_copyright[];
extern MASSTOR_LIST MASO_OABS ARGS((MASSTOR_LIST R));
extern MASSTOR_LIST MASO_OCON ARGS((MASSTOR_LIST R));
extern MASSTOR_LIST MASO_OCOMP ARGS((MASSTOR_LIST R, MASSTOR_LIST S));
extern MASSTOR_LIST MASO_ODIF ARGS((MASSTOR_LIST R, MASSTOR_LIST S));
extern MASSTOR_LIST MASO_ODREAD ARGS(());
extern void MASO_ODWRITE ARGS((MASSTOR_LIST R, MASSTOR_LIST NL));
extern MASSTOR_LIST MASO_OEXP ARGS((MASSTOR_LIST C_1_A, MASSTOR_LIST NL));
extern MASSTOR_LIST MASO_OIM ARGS((MASSTOR_LIST R));
extern MASSTOR_LIST MASO_OINT ARGS((MASSTOR_LIST C_2_A));
extern MASSTOR_LIST MASO_ORE ARGS((MASSTOR_LIST R));
extern MASSTOR_LIST MASO_ORN ARGS((MASSTOR_LIST C_3_A));
extern MASSTOR_LIST MASO_ORNP ARGS((MASSTOR_LIST C_4_A, MASSTOR_LIST B));
extern MASSTOR_LIST MASO_ONINV ARGS((MASSTOR_LIST R));
extern MASSTOR_LIST MASO_ONEG ARGS((MASSTOR_LIST R));
extern MASSTOR_LIST MASO_OONE ARGS((MASSTOR_LIST R));
extern MASSTOR_LIST MASO_OPROD ARGS((MASSTOR_LIST R, MASSTOR_LIST S));
extern MASSTOR_LIST MASO_OQ ARGS((MASSTOR_LIST R, MASSTOR_LIST S));
extern MASSTOR_LIST MASO_ORAND ARGS((MASSTOR_LIST NL));
extern MASSTOR_LIST MASO_ONREAD ARGS(());
extern MASSTOR_LIST MASO_OSUM ARGS((MASSTOR_LIST R, MASSTOR_LIST S));
extern void MASO_ONWRITE ARGS((MASSTOR_LIST R));
extern void BEGIN_MASO();
