#define DEFINITION_MASPGCD

#ifndef DEFINITION_MASSTOR
#include "MASSTOR.h"
#endif

extern CHAR MASPGCD_rcsid[];
extern CHAR MASPGCD_copyright[];
extern MASSTOR_LIST MASPGCD_IPSFF ARGS((MASSTOR_LIST r, MASSTOR_LIST f));
extern MASSTOR_LIST MASPGCD_IPFLMER ARGS((MASSTOR_LIST r, MASSTOR_LIST F1, MASSTOR_LIST F2));
extern void BEGIN_MASPGCD();
