#define DEFINITION_MASQ

#ifndef DEFINITION_MASSTOR
#include "MASSTOR.h"
#endif

extern CHAR MASQ_rcsid[];
extern CHAR MASQ_copyright[];
extern MASSTOR_LIST MASQ_QABS ARGS((MASSTOR_LIST R));
extern MASSTOR_LIST MASQ_QCON ARGS((MASSTOR_LIST R));
extern MASSTOR_LIST MASQ_QCOMP ARGS((MASSTOR_LIST R, MASSTOR_LIST S));
extern MASSTOR_LIST MASQ_QDIF ARGS((MASSTOR_LIST R, MASSTOR_LIST S));
extern MASSTOR_LIST MASQ_QDREAD ARGS(());
extern void MASQ_QDWRITE ARGS((MASSTOR_LIST R, MASSTOR_LIST NL));
extern MASSTOR_LIST MASQ_QEXP ARGS((MASSTOR_LIST C_1_A, MASSTOR_LIST NL));
extern MASSTOR_LIST MASQ_QIMi ARGS((MASSTOR_LIST R));
extern MASSTOR_LIST MASQ_QIMj ARGS((MASSTOR_LIST R));
extern MASSTOR_LIST MASQ_QIMk ARGS((MASSTOR_LIST R));
extern MASSTOR_LIST MASQ_QINT ARGS((MASSTOR_LIST C_2_A));
extern MASSTOR_LIST MASQ_QRE ARGS((MASSTOR_LIST R));
extern MASSTOR_LIST MASQ_QRN ARGS((MASSTOR_LIST C_3_A));
extern MASSTOR_LIST MASQ_QRN4 ARGS((MASSTOR_LIST C_4_A, MASSTOR_LIST B, MASSTOR_LIST C, MASSTOR_LIST D));
extern MASSTOR_LIST MASQ_QINV ARGS((MASSTOR_LIST R));
extern MASSTOR_LIST MASQ_QNEG ARGS((MASSTOR_LIST R));
extern MASSTOR_LIST MASQ_QONE ARGS((MASSTOR_LIST R));
extern MASSTOR_LIST MASQ_QPROD ARGS((MASSTOR_LIST R, MASSTOR_LIST S));
extern MASSTOR_LIST MASQ_QQ ARGS((MASSTOR_LIST R, MASSTOR_LIST S));
extern MASSTOR_LIST MASQ_QRAND ARGS((MASSTOR_LIST NL));
extern MASSTOR_LIST MASQ_QNREAD ARGS(());
extern MASSTOR_LIST MASQ_QSUM ARGS((MASSTOR_LIST R, MASSTOR_LIST S));
extern void MASQ_QNWRITE ARGS((MASSTOR_LIST R));
extern void BEGIN_MASQ();
