#define DEFINITION_MASREP

#ifndef DEFINITION_MASSTOR
#include "MASSTOR.h"
#endif

extern CHAR MASREP_rcsid[];
extern CHAR MASREP_copyright[];
extern MASSTOR_LIST MASREP_NewRep ARGS(());
extern void MASREP_SetRep ARGS((MASSTOR_LIST n, MASSTOR_LIST e, MASSTOR_LIST r));
extern MASSTOR_LIST MASREP_GetRep ARGS((MASSTOR_LIST n, MASSTOR_LIST r));
extern MASSTOR_LIST MASREP_CopyRep ARGS((MASSTOR_LIST r));
extern MASSTOR_LIST MASREP_StepRep ARGS((MASSTOR_LIST r));
extern MASSTOR_LIST MASREP_ForEachinRep ARGS((MASSTOR_LIST r, MASSTOR_LIST f, MASSTOR_LIST E));
extern MASSTOR_LIST MASREP_FullRep ARGS((MASSTOR_LIST r));
extern MASSTOR_LIST MASREP_ForEachinList ARGS((MASSTOR_LIST r, MASSTOR_LIST f, MASSTOR_LIST E));
extern void BEGIN_MASREP();
