#define DEFINITION_MASRN

#ifndef DEFINITION_MASSTOR
#include "MASSTOR.h"
#endif

extern CHAR MASRN_rcsid[];
extern CHAR MASRN_copyright[];
extern MASSTOR_LIST MASRN_RNDRD ARGS(());
extern void MASRN_RNDWR ARGS((MASSTOR_LIST R, MASSTOR_LIST NL));
extern void MASRN_RNDWRS ARGS((MASSTOR_LIST C_1_A, MASSTOR_LIST S));
extern MASSTOR_LIST MASRN_RNEXP ARGS((MASSTOR_LIST C_2_A, MASSTOR_LIST NL));
extern MASSTOR_LIST MASRN_RNMAX ARGS((MASSTOR_LIST AL, MASSTOR_LIST BL));
extern MASSTOR_LIST MASRN_RNONE ARGS((MASSTOR_LIST R));
extern void BEGIN_MASRN();
