#define DEFINITION_MASSET

#ifndef DEFINITION_MASSTOR
#include "MASSTOR.h"
#endif

#define MASSET_subset	0
#define MASSET_superset	1
#define MASSET_setequal	2
#define MASSET_setnorel	3
typedef unsigned char MASSET_SetRel;
extern CHAR MASSET_rcsid[];
extern CHAR MASSET_copyright[];
extern MASSTOR_LIST MASSET_SetAdd ARGS((MASSTOR_LIST e, MASSTOR_LIST S));
extern MASSTOR_LIST MASSET_SetAddQ ARGS((MASSTOR_LIST e, MASSTOR_LIST S));
extern MASSTOR_LIST MASSET_SetUnion ARGS((MASSTOR_LIST S1, MASSTOR_LIST S2));
extern MASSTOR_LIST MASSET_SetUnionQ ARGS((MASSTOR_LIST S1, MASSTOR_LIST S2));
extern BOOLEAN MASSET_SetElementP ARGS((MASSTOR_LIST e, MASSTOR_LIST S));
extern BOOLEAN MASSET_SetElementPQ ARGS((MASSTOR_LIST e, MASSTOR_LIST S));
extern MASSTOR_LIST MASSET_SetMinus ARGS((MASSTOR_LIST e, MASSTOR_LIST S));
extern MASSTOR_LIST MASSET_SetMinusQ ARGS((MASSTOR_LIST e, MASSTOR_LIST S));
extern MASSTOR_LIST MASSET_SetMinusC ARGS((MASSTOR_LIST e, MASSTOR_LIST S));
extern MASSTOR_LIST MASSET_SetMinusCQ ARGS((MASSTOR_LIST e, MASSTOR_LIST S));
extern MASSTOR_LIST MASSET_SetComplement ARGS((MASSTOR_LIST S1, MASSTOR_LIST S2));
extern MASSTOR_LIST MASSET_SetComplementQ ARGS((MASSTOR_LIST S1, MASSTOR_LIST S2));
extern void BEGIN_MASSET();
