#define DEFINITION_MASSPEC

#ifndef DEFINITION_MASSTOR
#include "MASSTOR.h"
#endif

extern CHAR MASSPEC_rcsid[];
extern CHAR MASSPEC_copyright[];
extern MASSTOR_LIST MASSPEC_EVALUATE ARGS((MASSTOR_LIST X, MASSTOR_LIST *ENV));
extern void BEGIN_MASSPEC();
