#define DEFINITION_MASSYM2

#ifndef DEFINITION_MASELEM
#include "MASELEM.h"
#endif

#ifndef DEFINITION_MASSTOR
#include "MASSTOR.h"
#endif

extern MASELEM_GAMMAINT MASSYM2_COUNT, MASSYM2_TRMAX;
extern MASSTOR_LIST MASSYM2_SYMTB;
extern MASSTOR_LIST MASSYM2_NOSHOW;
extern CHAR MASSYM2_rcsid[];
extern CHAR MASSYM2_copyright[];
extern MASSTOR_LIST MASSYM2_ACOMP ARGS((MASSTOR_LIST C_1_A, MASSTOR_LIST B));
extern MASSTOR_LIST MASSYM2_ACOMP1 ARGS((MASSTOR_LIST C_2_A, MASSTOR_LIST B));
extern MASSTOR_LIST MASSYM2_ASSOC ARGS((MASSTOR_LIST AL, MASSTOR_LIST L));
extern MASSTOR_LIST MASSYM2_ASSOCQ ARGS((MASSTOR_LIST AL, MASSTOR_LIST L));
extern MASSTOR_LIST MASSYM2_ATTRIB ARGS((MASSTOR_LIST L));
extern MASSTOR_LIST MASSYM2_EXPLOD ARGS((MASSTOR_LIST S));
extern MASSTOR_LIST MASSYM2_ENTER ARGS((MASSTOR_LIST L));
extern MASSTOR_LIST MASSYM2_GENSYM ARGS(());
extern MASSTOR_LIST MASSYM2_GET ARGS((MASSTOR_LIST S, MASSTOR_LIST AL));
extern MASSTOR_LIST MASSYM2_NAME ARGS((MASSTOR_LIST L));
extern MASSTOR_LIST MASSYM2_PACK ARGS((MASSTOR_LIST L));
extern void MASSYM2_PUT ARGS((MASSTOR_LIST S, MASSTOR_LIST AL, MASSTOR_LIST C_3_A));
extern void MASSYM2_REMPRP ARGS((MASSTOR_LIST S, MASSTOR_LIST AL));
extern MASSTOR_LIST MASSYM2_SMEMB ARGS((MASSTOR_LIST S, MASSTOR_LIST L));
extern MASSTOR_LIST MASSYM2_SREAD ARGS(());
extern MASSTOR_LIST MASSYM2_SREAD1 ARGS(());
extern void MASSYM2_STCNT ARGS((MASSTOR_LIST T, MASSTOR_LIST *S, MASSTOR_LIST *P));
extern MASSTOR_LIST MASSYM2_STINS ARGS((MASSTOR_LIST B));
extern MASSTOR_LIST MASSYM2_STLST ARGS((MASSTOR_LIST T));
extern MASSTOR_LIST MASSYM2_STLSTI ARGS((MASSTOR_LIST T));
extern MASSTOR_LIST MASSYM2_STSRCH ARGS((MASSTOR_LIST T, MASSTOR_LIST AP));
extern void MASSYM2_STWRT ARGS((MASSTOR_LIST T));
extern BOOLEAN MASSYM2_SYMBOL ARGS((MASSTOR_LIST AP));
extern void MASSYM2_SymSummary ARGS(());
extern void MASSYM2_SYWRIT ARGS((MASSTOR_LIST S));
extern MASSTOR_LIST MASSYM2_SUBLIS ARGS((MASSTOR_LIST L, MASSTOR_LIST C_4_A));
extern MASSTOR_LIST MASSYM2_UREAD ARGS(());
extern void MASSYM2_UWRITE ARGS((MASSTOR_LIST L));
extern void MASSYM2_UWRIT1 ARGS((MASSTOR_LIST L));
extern void BEGIN_MASSYM2();
