#define DEFINITION_MASSTOR

#ifndef DEFINITION_MASELEM
#include "MASELEM.h"
#endif

typedef MASELEM_GAMMAINT MASSTOR_LIST;
extern MASSTOR_LIST MASSTOR_BETA, MASSTOR_BETA1, MASSTOR_SIL;
extern MASELEM_GAMMAINT MASSTOR_NU, MASSTOR_GCC, MASSTOR_GCCC, MASSTOR_GCM, MASSTOR_RHO, MASSTOR_TAU, MASSTOR_TAU0;
extern CHAR MASSTOR_rcsid[];
extern CHAR MASSTOR_copyright[];
extern void MASSTOR_ADV ARGS((MASSTOR_LIST L, MASSTOR_LIST *a, MASSTOR_LIST *LP));
extern MASELEM_GAMMAINT MASSTOR_CELLS ARGS(());
extern MASELEM_GAMMAINT MASSTOR_CLOCK ARGS(());
extern MASSTOR_LIST MASSTOR_COMP ARGS((MASSTOR_LIST a, MASSTOR_LIST L));
extern MASSTOR_LIST MASSTOR_DEQUE ARGS((MASSTOR_LIST L));
extern BOOLEAN MASSTOR_EMPTYQUE ARGS((MASSTOR_LIST M));
extern void MASSTOR_ENQUE ARGS((MASSTOR_LIST a, MASSTOR_LIST L));
extern MASSTOR_LIST MASSTOR_FIRST ARGS((MASSTOR_LIST L));
extern MASSTOR_LIST MASSTOR_NEWQUE ARGS(());
extern MASSTOR_LIST MASSTOR_INV ARGS((MASSTOR_LIST L));
extern MASELEM_GAMMAINT MASSTOR_LENGTH ARGS((MASSTOR_LIST L));
extern MASSTOR_LIST MASSTOR_LIST1 ARGS((MASSTOR_LIST a));
extern void MASSTOR_LISTVAR ARGS((MASSTOR_LIST *L));
extern MASSTOR_LIST MASSTOR_RED ARGS((MASSTOR_LIST L));
extern void MASSTOR_SFIRST ARGS((MASSTOR_LIST L, MASSTOR_LIST a));
extern void MASSTOR_SRED ARGS((MASSTOR_LIST L, MASSTOR_LIST LP));
extern MASELEM_GAMMAINT MASSTOR_TIME ARGS(());
extern void BEGIN_MASSTOR();
