#define DEFINITION_MASSYM

#ifndef DEFINITION_MASSTOR
#include "MASSTOR.h"
#endif

extern MASSTOR_LIST MASSYM_NOSHOW;
extern CHAR MASSYM_rcsid[];
extern CHAR MASSYM_copyright[];
extern BOOLEAN MASSYM_ATOM ARGS((MASSTOR_LIST X));
extern BOOLEAN MASSYM_ELEMP ARGS((MASSTOR_LIST X));
extern BOOLEAN MASSYM_MEMQ ARGS((MASSTOR_LIST AL, MASSTOR_LIST L));
extern BOOLEAN MASSYM_OCCURQ ARGS((MASSTOR_LIST AL, MASSTOR_LIST L));
extern MASSTOR_LIST MASSYM_UREAD ARGS(());
extern void MASSYM_UWRITE ARGS((MASSTOR_LIST L));
extern void MASSYM_UWRIT1 ARGS((MASSTOR_LIST L));
extern BOOLEAN MASSYM_UNIFY ARGS((MASSTOR_LIST C_1_A, MASSTOR_LIST B, MASSTOR_LIST *S));
extern MASSTOR_LIST MASSYM_GENARRAY ARGS((MASSTOR_LIST C_2_A));
extern MASSTOR_LIST MASSYM_GENINDEX ARGS((MASSTOR_LIST C_3_A));
extern MASSTOR_LIST MASSYM_ARRAYDEC ARGS((MASSTOR_LIST C_4_A));
extern void BEGIN_MASSYM();
