#include "SYSTEM_.h"

#ifndef DEFINITION_MASLOG
#include "MASLOG.h"
#endif

#ifndef DEFINITION_MLOGBASE
#include "MLOGBASE.h"
#endif

#ifndef DEFINITION_MLOGIO
#include "MLOGIO.h"
#endif

#ifndef DEFINITION_MODVAR
#include "MODVAR.h"
#endif

#ifndef DEFINITION_MASLISPU
#include "MASLISPU.h"
#endif

#ifndef DEFINITION_PQBASE
#include "PQBASE.h"
#endif

#ifndef DEFINITION_RQEPRRC
#include "RQEPRRC.h"
#endif

#ifndef DEFINITION_SYSINFO
#include "SYSINFO.h"
#endif

#ifndef DEFINITION_TFORM
#include "TFORM.h"
#endif

#ifndef DEFINITION_MLMASLOG
#include "MLMASLOG.h"
#endif

CHAR MLMASLOG_rcsid [] = "$Id: MLMASLOG.md,v 1.2 1995/11/05 14:04:41 kredel Exp $";
CHAR MLMASLOG_copyright [] = "Copyright (c) 1993 Universitaet Passau";

static CHAR rcsidi [] = "$Id: MLMASLOG.mi,v 1.3 1994/11/28 21:14:31 dolzmann Exp $";
static CHAR copyrighti [] = "Copyright (c) 1993 Universitaet Passau";


void MLMASLOG_InitExternalsML
# ifdef __STDC__
()
# else
()
# endif
{
  MASLISPU_Compiledp2(MODVAR_MVSET, "MVSET", 5L);
  MASLISPU_Compiledf1(MODVAR_MVGET, "MVGET", 5L);
  MASLISPU_Compiledp1(MODVAR_MVON, "MVON", 4L);
  MASLISPU_Compiledp1(MODVAR_MVOFF, "MVOFF", 5L);
  MASLISPU_Compiledp1(MODVAR_MVHLP, "MVHLP", 5L);
  MASLISPU_Compiledf1(MODVAR_MVFLAG, "MVFLAG", 6L);
  MASLISPU_Compiledf2(MLOGBASE_FORMKFOR, "FORMKFOR", 8L);
  MASLISPU_Compiledf1(MLOGBASE_FORMKCNST, "FORMKCNST", 9L);
  MASLISPU_Compiledf2(MLOGBASE_FORMKUNOP, "FORMKUNOP", 9L);
  MASLISPU_Compiledf3(MLOGBASE_FORMKBINOP, "FORMKBINOP", 10L);
  MASLISPU_Compiledf2(MLOGBASE_FORMKVAR, "FORMKVAR", 8L);
  MASLISPU_Compiledf1(MLOGBASE_FORMKLVAR, "FORMKLVAR", 9L);
  MASLISPU_Compiledf3(MLOGBASE_FORMKQUANT, "FORMKQUANT", 10L);
  MASLISPU_Compiledf2(MASLOG_FORELIMXOPS, "FORELIMXOPS", 11L);
  MASLISPU_Compiledp1(MLOGIO_FORPPVAR, "FORPPVAR", 8L);
  MASLISPU_Compiledp1(MLOGIO_FORPPLVAR, "FORPPLVAR", 9L);
  MASLISPU_Compiledp1(MLOGIO_FORTEXWVAR, "FORTEXWVAR", 10L);
  MASLISPU_Compiledp1(MLOGIO_FORTEXWLVAR, "FORTEXWLVAR", 11L);
  MASLISPU_Compiledf0(MLOGIO_FORRDVAR, "FORRDVAR", 8L);
  MASLISPU_Compiledf0(MLOGIO_FORRDLVAR, "FORRDLVAR", 9L);
  MASLISPU_Compiledf0(MLOGIO_KEYREAD, "KEYREAD", 7L);
  MASLISPU_Compiledf0(MLOGBASE_FORVTSTORE, "FORVTSTORE", 10L);
  MASLISPU_Compiledf1(MLOGBASE_FORVTRESTORE, "FORVTRESTORE", 12L);
  MASLISPU_Compiledf1(MLOGBASE_FORVTENTER, "FORVTENTER", 10L);
  MASLISPU_Compiledf1(MLOGBASE_FORVTGET, "FORVTGET", 8L);
  MASLISPU_Compiledf1(MASLOG_FORIMQB, "FORIMQB", 7L);
  MASLISPU_Compiledf1(MASLOG_FORCOUNTAF, "FORCOUNTAF", 10L);
  MASLISPU_Compiledf2(MASLOG_FORMKPRENEX, "FORMKPRENEX", 11L);
  MASLISPU_Compiledf2(MASLOG_FORMKPRENEXI, "FORMKPRENEXI", 12L);
  MASLISPU_Compiledf1(MASLOG_FORMKPRENEX1, "FORMKPRENEX1", 12L);
  MASLISPU_Compiledf2(PQBASE_pqmkaf, "pqmkaf", 6L);
  MASLISPU_Compiledf0(PQBASE_PQPREAD, "PQPREAD", 7L);
  MASLISPU_Compiledf0(PQBASE_PQIREAD, "PQIREAD", 7L);
  MASLISPU_Compiledp1(PQBASE_PQPPRT, "PQPPRT", 6L);
  MASLISPU_Compiledp1(PQBASE_PQTEXW, "PQTEXW", 6L);
  MASLISPU_Compiledf1(PQBASE_PQMKCNF, "PQMKCNF", 7L);
  MASLISPU_Compiledf1(PQBASE_PQMKDNF, "PQMKDNF", 7L);
  MASLISPU_Compiledf1(PQBASE_PQSMPL, "PQSMPL", 6L);
  MASLISPU_Compiledp0(PQBASE_PQPRINGWR, "PQPRINGWR", 9L);
  MASLISPU_Compiledf1(PQBASE_PQPRING, "PQPRING", 7L);
  MASLISPU_Compiledf1(PQBASE_PQELIMXOPS, "PQELIMXOPS", 10L);
  MASLISPU_Compiledf2(PQBASE_PQELIMXOPS1, "PQELIMXOPS1", 11L);
  MASLISPU_Compiledf2(PQBASE_PQMKPRENEX, "PQMKPRENEX", 10L);
  MASLISPU_Compiledf1(PQBASE_PQMKPOS, "PQMKPOS", 7L);
  MASLISPU_Compiledf2(PQBASE_PQSIMPLIFYP, "PQSIMPLIFYP", 11L);
  MASLISPU_Compiledf1(PQBASE_PQMKVD, "PQMKVD", 6L);
  MASLISPU_Compiledf1(PQBASE_PQSIMPLIFY, "PQSIMPLIFY", 10L);
  MASLISPU_Compiledf1(RQEPRRC_RQEQE, "RQEQE", 5L);
  MASLISPU_Compiledf1(RQEPRRC_RQEOPTSET, "RQEOPTSET", 9L);
  MASLISPU_Compiledp0(RQEPRRC_RQEOPTWR, "RQEOPTWR", 8L);
  MASLISPU_Compiledf2(TFORM_TfNextTuple, "TfNextTuple", 11L);
  MASLISPU_Compiledf1(TFORM_TfSignChs, "TfSignChs", 9L);
  MASLISPU_Compiledf1(TFORM_TfZeroes0, "TfZeroes0", 9L);
  MASLISPU_Compiledf1(TFORM_TfZeroesI, "TfZeroes", 8L);
  MASLISPU_Compiledf1(TFORM_TfClassifyI, "TfClassify", 10L);
  MASLISPU_Compiledf1(TFORM_TfCount, "TfCount", 7L);
  MASLISPU_Compiledf2(TFORM_TfCount1, "TfCount1", 8L);
  MASLISPU_Compiledf2(TFORM_TFGENI, "TFGEN", 5L);
  MASLISPU_Compiledf1(TFORM_TFFTUPLE, "TFFTUPLE", 8L);
  MASLISPU_Compiledp1(TFORM_TFPPRT, "TFPPRT", 6L);
  MASLISPU_Compiledf1(TFORM_TfCtj, "TfCtj", 5L);
  MASLISPU_Compiledf1(TFORM_TFGENJ, "TFGENJ", 6L);
  MASLISPU_Compiledf0(TFORM_TFIREAD, "TFIREAD", 7L);
  MASLISPU_Compiledf1(TFORM_TfTypeFormula, "TfTypeFormula", 13L);
  MASLISPU_Compiledp0(TFORM_TfUseDb, "TfUseDb", 7L);
  MASLISPU_Compiledp0(TFORM_TfComputeTf, "TfComputeTf", 11L);
  MODVAR_MVDeclareB(&SYSINFO_Cells, "SysinfoCells", 12L, "Determines whether the cell statistics is reported.", 51L, TRUE);
}

void BEGIN_MLMASLOG()
{
  static BOOLEAN has_been_called = FALSE;

  if (!has_been_called) {
    has_been_called = TRUE;

    BEGIN_MASSTOR();
    BEGIN_MASLOG();
    BEGIN_MLOGBASE();
    BEGIN_MLOGIO();
    BEGIN_MODVAR();
    BEGIN_MASLISPU();
    BEGIN_PQBASE();
    BEGIN_RQEPRRC();
    BEGIN_SYSINFO();
    BEGIN_TFORM();

  }
}
