#define DEFINITION_MLOGBASE

#ifndef DEFINITION_MASSTOR
#include "MASSTOR.h"
#endif

typedef BOOLEAN (*MLOGBASE_PROCFB1) ARGS((MASSTOR_LIST));
typedef BOOLEAN (*MLOGBASE_PROCFB2) ARGS((MASSTOR_LIST, MASSTOR_LIST));
extern CHAR MLOGBASE_rcsid[];
extern CHAR MLOGBASE_copyright[];
extern MASSTOR_LIST MLOGBASE_ET, MLOGBASE_VEL, MLOGBASE_NON, MLOGBASE_VERUM, MLOGBASE_FALSUM, MLOGBASE_EXIST, MLOGBASE_FORALL, MLOGBASE_TVAR, MLOGBASE_REP, MLOGBASE_IMP, MLOGBASE_EQUIV, MLOGBASE_ANTIV, MLOGBASE_XOR, MLOGBASE_LVAR;
extern MASSTOR_LIST MLOGBASE_ANY, MLOGBASE_BOOL;
extern MASSTOR_LIST MLOGBASE_FORGOP ARGS((MASSTOR_LIST phi));
extern MASSTOR_LIST MLOGBASE_FORGARGS ARGS((MASSTOR_LIST phi));
extern MASSTOR_LIST MLOGBASE_FORGLVAR ARGS((MASSTOR_LIST lvar));
extern void MLOGBASE_FORPFOR ARGS((MASSTOR_LIST phi, MASSTOR_LIST *op, MASSTOR_LIST *args));
extern void MLOGBASE_FORPARGS ARGS((MASSTOR_LIST phi, MASSTOR_LIST *first, MASSTOR_LIST *red));
extern void MLOGBASE_FORPUNOP ARGS((MASSTOR_LIST phi, MASSTOR_LIST *op, MASSTOR_LIST *arg));
extern void MLOGBASE_FORPBINOP ARGS((MASSTOR_LIST phi, MASSTOR_LIST *op, MASSTOR_LIST *first, MASSTOR_LIST *second));
extern void MLOGBASE_FORPUNOPA ARGS((MASSTOR_LIST arglist, MASSTOR_LIST *arg));
extern void MLOGBASE_FORPBINOPA ARGS((MASSTOR_LIST red, MASSTOR_LIST *first, MASSTOR_LIST *second));
extern void MLOGBASE_FORPQUANT ARGS((MASSTOR_LIST phi, MASSTOR_LIST *quant, MASSTOR_LIST *vars, MASSTOR_LIST *formula));
extern void MLOGBASE_FORPQUANTA ARGS((MASSTOR_LIST red, MASSTOR_LIST *lvar, MASSTOR_LIST *formula));
extern void MLOGBASE_FORPLVAR ARGS((MASSTOR_LIST lvar, MASSTOR_LIST *varlist));
extern void MLOGBASE_FORPVAR ARGS((MASSTOR_LIST var, MASSTOR_LIST *name, MASSTOR_LIST *sort));
extern void MLOGBASE_FORPVARA ARGS((MASSTOR_LIST red, MASSTOR_LIST *name, MASSTOR_LIST *sort));
extern MASSTOR_LIST MLOGBASE_FORMKFOR ARGS((MASSTOR_LIST op, MASSTOR_LIST args));
extern MASSTOR_LIST MLOGBASE_FORMKCNST ARGS((MASSTOR_LIST cnst));
extern MASSTOR_LIST MLOGBASE_FORMKUNOP ARGS((MASSTOR_LIST op, MASSTOR_LIST arg));
extern MASSTOR_LIST MLOGBASE_FORMKBINOP ARGS((MASSTOR_LIST op, MASSTOR_LIST arg1, MASSTOR_LIST arg2));
extern MASSTOR_LIST MLOGBASE_FORMKVAR ARGS((MASSTOR_LIST name, MASSTOR_LIST sort));
extern MASSTOR_LIST MLOGBASE_FORMKLVAR ARGS((MASSTOR_LIST vars));
extern MASSTOR_LIST MLOGBASE_FORMKQUANT ARGS((MASSTOR_LIST quant, MASSTOR_LIST vars, MASSTOR_LIST formula));
extern BOOLEAN MLOGBASE_FORTST ARGS((MASSTOR_LIST L, MLOGBASE_PROCFB1 bbtst));
extern BOOLEAN MLOGBASE_FORISVAR ARGS((MASSTOR_LIST L));
extern BOOLEAN MLOGBASE_FORISBOOLVAR ARGS((MASSTOR_LIST L));
extern BOOLEAN MLOGBASE_FORISLVAR ARGS((MASSTOR_LIST L));
extern BOOLEAN MLOGBASE_FORISATOM ARGS((MASSTOR_LIST phi));
extern BOOLEAN MLOGBASE_FORISBBFOR ARGS((MASSTOR_LIST phi));
extern MASSTOR_LIST MLOGBASE_FORVTSTORE ARGS(());
extern MASSTOR_LIST MLOGBASE_FORVTRESTORE ARGS((MASSTOR_LIST vt));
extern MASSTOR_LIST MLOGBASE_FORVTENTER ARGS((MASSTOR_LIST sym));
extern MASSTOR_LIST MLOGBASE_FORVTGET ARGS((MASSTOR_LIST id));
extern void BEGIN_MLOGBASE();
