#define DEFINITION_MLOGIO

#ifndef DEFINITION_MASSTOR
#include "MASSTOR.h"
#endif

#ifndef DEFINITION_MASLISPU
#include "MASLISPU.h"
#endif

extern CHAR MLOGIO_rcsid[];
extern CHAR MLOGIO_copyright[];
extern void MLOGIO_FORPPRT ARGS((MASSTOR_LIST phi, MASLISPU_PROCP1 bbpprt));
extern void MLOGIO_FORPPVAR ARGS((MASSTOR_LIST var));
extern void MLOGIO_FORPPLVAR ARGS((MASSTOR_LIST lvar));
extern void MLOGIO_FORTEXW ARGS((MASSTOR_LIST phi, MASLISPU_PROCP1 bbtexw));
extern void MLOGIO_FORTEXWVAR ARGS((MASSTOR_LIST var));
extern void MLOGIO_FORTEXWLVAR ARGS((MASSTOR_LIST lvar));
extern MASSTOR_LIST MLOGIO_FORPREAD ARGS((MASLISPU_PROCF0 bbread));
extern MASSTOR_LIST MLOGIO_KEYREAD ARGS(());
extern MASSTOR_LIST MLOGIO_FORRDVAR ARGS(());
extern MASSTOR_LIST MLOGIO_FORRDLVAR ARGS(());
extern MASSTOR_LIST MLOGIO_FORIREAD ARGS((MASLISPU_PROCF0 bbread));
extern void BEGIN_MLOGIO();
