#define DEFINITION_NOETHER

#ifndef DEFINITION_MASSTOR
#include "MASSTOR.h"
#endif

#ifndef DEFINITION_MASELEM
#include "MASELEM.h"
#endif

extern CHAR NOETHER_rcsid[];
extern CHAR NOETHER_copyright[];
extern void NOETHER_NOEINF ARGS(());
extern void NOETHER_NOENSP ARGS((MASSTOR_LIST PG));
extern MASSTOR_LIST NOETHER_NOEL32 ARGS((MASELEM_GAMMAINT M, MASELEM_GAMMAINT K));
extern void NOETHER_MERGE ARGS((BOOLEAN FLAG, MASSTOR_LIST BASE1, MASSTOR_LIST POL1, MASSTOR_LIST *BASE2, MASSTOR_LIST *POL2));
extern MASSTOR_LIST NOETHER_NOESRT ARGS((MASSTOR_LIST POL));
extern MASSTOR_LIST NOETHER_NOEPOW ARGS((MASSTOR_LIST PG, MASELEM_GAMMAINT K));
extern MASSTOR_LIST NOETHER_NOEPSM ARGS((MASSTOR_LIST POL1, MASSTOR_LIST POL2));
extern MASSTOR_LIST NOETHER_NOEPPR ARGS((MASSTOR_LIST POL1, MASSTOR_LIST POL2, MASSTOR_LIST TERM));
extern MASSTOR_LIST NOETHER_NOEPIP ARGS((MASSTOR_LIST POL, MASSTOR_LIST FACT));
extern MASSTOR_LIST NOETHER_NOEPRM ARGS((MASSTOR_LIST POL, MASSTOR_LIST TERM));
extern void NOETHER_NOERED ARGS((MASSTOR_LIST PG, MASSTOR_LIST POL, MASSTOR_LIST *BASE, MASSTOR_LIST *BASEPOL, MASSTOR_LIST *REMPOL));
extern void BEGIN_NOETHER();
