#define DEFINITION_PQBASE

#ifndef DEFINITION_MASSTOR
#include "MASSTOR.h"
#endif

extern CHAR PQBASE_rcsid[];
extern CHAR PQBASE_copyright[];
extern MASSTOR_LIST PQBASE_EQU, PQBASE_NEQ, PQBASE_GRE, PQBASE_LES, PQBASE_GRQ, PQBASE_LSQ;
extern MASSTOR_LIST PQBASE_PQSAF;
extern MASSTOR_LIST PQBASE_DOMAIN;
extern MASSTOR_LIST PQBASE_vlistflvar ARGS((MASSTOR_LIST lvar));
extern MASSTOR_LIST PQBASE_lvarfvlist ARGS((MASSTOR_LIST vlist));
extern MASSTOR_LIST PQBASE_pqmkaf ARGS((MASSTOR_LIST rel, MASSTOR_LIST pol));
extern void PQBASE_pqpaf ARGS((MASSTOR_LIST af, MASSTOR_LIST *rel, MASSTOR_LIST *pol));
extern MASSTOR_LIST PQBASE_pqgrel ARGS((MASSTOR_LIST af));
extern MASSTOR_LIST PQBASE_pqgpol ARGS((MASSTOR_LIST af));
extern BOOLEAN PQBASE_pqatom ARGS((MASSTOR_LIST phi));
extern void PQBASE_pqprtaf ARGS((MASSTOR_LIST af));
extern void PQBASE_pqtexwaf ARGS((MASSTOR_LIST af));
extern MASSTOR_LIST PQBASE_pqnegaf ARGS((MASSTOR_LIST af));
extern MASSTOR_LIST PQBASE_pqsimplifyaf ARGS((MASSTOR_LIST af));
extern MASSTOR_LIST PQBASE_pqreadaf ARGS(());
extern void PQBASE_InitBbfParser ARGS(());
extern MASSTOR_LIST PQBASE_pqsmart ARGS((MASSTOR_LIST phi));
extern MASSTOR_LIST PQBASE_ContractVel ARGS((MASSTOR_LIST l));
extern MASSTOR_LIST PQBASE_PQCRELOR ARGS((MASSTOR_LIST left, MASSTOR_LIST right));
extern MASSTOR_LIST PQBASE_ContractEt ARGS((MASSTOR_LIST l));
extern MASSTOR_LIST PQBASE_PQCRELAND ARGS((MASSTOR_LIST left, MASSTOR_LIST right));
extern MASSTOR_LIST PQBASE_PQMKDNF ARGS((MASSTOR_LIST phi));
extern MASSTOR_LIST PQBASE_PQMKCNF ARGS((MASSTOR_LIST phi));
extern MASSTOR_LIST PQBASE_PQSMPL ARGS((MASSTOR_LIST phi));
extern MASSTOR_LIST PQBASE_PQSIMPLIFY ARGS((MASSTOR_LIST phi));
extern MASSTOR_LIST PQBASE_PQSIMPLIFYP ARGS((MASSTOR_LIST phi, MASSTOR_LIST maxlevel));
extern MASSTOR_LIST PQBASE_PQMKPOS ARGS((MASSTOR_LIST phi));
extern void PQBASE_PQPPRT ARGS((MASSTOR_LIST phi));
extern void PQBASE_PQTEXW ARGS((MASSTOR_LIST phi));
extern MASSTOR_LIST PQBASE_PQPREAD ARGS(());
extern MASSTOR_LIST PQBASE_PQIREAD ARGS(());
extern MASSTOR_LIST PQBASE_PQELIMXOPS ARGS((MASSTOR_LIST phi));
extern MASSTOR_LIST PQBASE_PQELIMXOPS1 ARGS((MASSTOR_LIST phi, MASSTOR_LIST pref));
extern MASSTOR_LIST PQBASE_PQMKPRENEX ARGS((MASSTOR_LIST phi, MASSTOR_LIST pref));
extern MASSTOR_LIST PQBASE_PQPRING ARGS((MASSTOR_LIST R));
extern void PQBASE_PQPRINGWR ARGS(());
extern MASSTOR_LIST PQBASE_PQMKVD ARGS((MASSTOR_LIST phi));
extern void BEGIN_PQBASE();
