#define DEFINITION_PQSMPL

#ifndef DEFINITION_MASSTOR
#include "MASSTOR.h"
#endif

#ifndef DEFINITION_MASLISPU
#include "MASLISPU.h"
#endif

extern CHAR PQSMPL_rcsid[];
extern CHAR PQSMPL_copyright[];
extern MASSTOR_LIST PQSMPL_PQSCNF ARGS((MASSTOR_LIST phi));
extern MASSTOR_LIST PQSMPL_PQSDNF ARGS((MASSTOR_LIST phi));
extern MASSTOR_LIST PQSMPL_PQCnfSimplify ARGS((MASSTOR_LIST nu));
extern MASSTOR_LIST PQSMPL_PQDnfSimplify ARGS((MASSTOR_LIST nu));
extern MASSTOR_LIST PQSMPL_SimplifyNf ARGS((MASSTOR_LIST nf));
extern BOOLEAN PQSMPL_IdealMember ARGS((MASSTOR_LIST G, MASSTOR_LIST p));
extern BOOLEAN PQSMPL_RadicalMember ARGS((MASSTOR_LIST G, MASSTOR_LIST p));
extern MASSTOR_LIST PQSMPL_DIPADGB ARGS((MASSTOR_LIST P));
extern MASSTOR_LIST PQSMPL_DIPADNF ARGS((MASSTOR_LIST P, MASSTOR_LIST S));
extern MASSTOR_LIST PQSMPL_DILADNF ARGS((MASSTOR_LIST P, MASSTOR_LIST S));
extern MASSTOR_LIST PQSMPL_DIPADGBext ARGS((MASSTOR_LIST gb, MASSTOR_LIST pols));
extern MASSTOR_LIST PQSMPL_DIPADGBunion ARGS((MASSTOR_LIST gb1, MASSTOR_LIST gb2));
extern MASSTOR_LIST PQSMPL_DIPADIRSET ARGS((MASSTOR_LIST P));
extern MASSTOR_LIST PQSMPL_DIPADGBRED ARGS((MASSTOR_LIST gb));
extern MASSTOR_LIST PQSMPL_PQOPT ARGS((MASSTOR_LIST O));
extern void PQSMPL_PQOPTWR ARGS(());
extern void PQSMPL_PQDEMO ARGS(());
extern void PQSMPL_DLSWRITE ARGS((CHAR S[], LONGCARD , MASSTOR_LIST b));
extern MASSTOR_LIST PQSMPL_SETADD ARGS((MASSTOR_LIST a, MASSTOR_LIST b));
extern MASSTOR_LIST PQSMPL_rabinowitsch ARGS((MASSTOR_LIST p));
extern void BEGIN_PQSMPL();
