#define DEFINITION_RRADOM

#ifndef DEFINITION_MASSTOR
#include "MASSTOR.h"
#endif

extern CHAR RRADOM_rcsid[];
extern CHAR RRADOM_copyright[];
extern MASSTOR_LIST RRADOM_EVUMSORT ARGS((MASSTOR_LIST L));
extern MASSTOR_LIST RRADOM_EVSSPROD ARGS((MASSTOR_LIST T));
extern MASSTOR_LIST RRADOM_RRVTEXT ARGS((MASSTOR_LIST C_1_A, MASSTOR_LIST L));
extern MASSTOR_LIST RRADOM_RRZDIM ARGS((MASSTOR_LIST G));
extern void RRADOM_RRREDTEST ARGS((MASSTOR_LIST G, MASSTOR_LIST t, MASSTOR_LIST *g, MASSTOR_LIST *s));
extern MASSTOR_LIST RRADOM_RRREDTERMS ARGS((MASSTOR_LIST G));
extern MASSTOR_LIST RRADOM_RRADNFORM ARGS((MASSTOR_LIST D, MASSTOR_LIST G, MASSTOR_LIST R));
extern void RRADOM_RRADSTRCONST ARGS((MASSTOR_LIST D, MASSTOR_LIST G, MASSTOR_LIST R, MASSTOR_LIST *U, MASSTOR_LIST *beta));
extern MASSTOR_LIST RRADOM_RRMMULT ARGS((MASSTOR_LIST w, MASSTOR_LIST R, MASSTOR_LIST U, MASSTOR_LIST beta));
extern MASSTOR_LIST RRADOM_RRADVARMATRICES ARGS((MASSTOR_LIST G, MASSTOR_LIST R, MASSTOR_LIST U, MASSTOR_LIST beta));
extern void RRADOM_RRADPOLMATRIX ARGS((MASSTOR_LIST D, MASSTOR_LIST R, MASSTOR_LIST h, MASSTOR_LIST *Mh, MASSTOR_LIST *L));
extern MASSTOR_LIST RRADOM_RRADQUADFORM ARGS((MASSTOR_LIST D, MASSTOR_LIST R, MASSTOR_LIST U, MASSTOR_LIST beta, MASSTOR_LIST Mh));
extern MASSTOR_LIST RRADOM_RRCSR ARGS((MASSTOR_LIST i, MASSTOR_LIST v, MASSTOR_LIST tf, MASSTOR_LIST *C_2_A, MASSTOR_LIST *N, MASSTOR_LIST *S, MASSTOR_LIST *L));
extern MASSTOR_LIST RRADOM_RRADCOUNT ARGS((MASSTOR_LIST D, MASSTOR_LIST G, MASSTOR_LIST H, MASSTOR_LIST v, MASSTOR_LIST tf));
extern void BEGIN_RRADOM();
