#define DEFINITION_RRINT

#ifndef DEFINITION_MASSTOR
#include "MASSTOR.h"
#endif

extern CHAR RRINT_rcsid[];
extern CHAR RRINT_copyright[];
extern void RRINT_RRIPIQ ARGS((MASSTOR_LIST c, MASSTOR_LIST *C_1_A, MASSTOR_LIST *a));
extern void RRINT_RRIPQSUM ARGS((MASSTOR_LIST B, MASSTOR_LIST b, MASSTOR_LIST c, MASSTOR_LIST *C_2_A, MASSTOR_LIST *a));
extern void RRINT_RRINFORM ARGS((MASSTOR_LIST G, MASSTOR_LIST R, MASSTOR_LIST *a, MASSTOR_LIST *NF));
extern void RRINT_RRISTRCONST ARGS((MASSTOR_LIST G, MASSTOR_LIST R, MASSTOR_LIST *U, MASSTOR_LIST *a, MASSTOR_LIST *beta));
extern void RRINT_RRIVARMATRICES ARGS((MASSTOR_LIST G, MASSTOR_LIST R, MASSTOR_LIST U, MASSTOR_LIST beta, MASSTOR_LIST *al, MASSTOR_LIST *L));
extern void RRINT_RRIPOLMATRIX ARGS((MASSTOR_LIST R, MASSTOR_LIST h, MASSTOR_LIST f, MASSTOR_LIST fl, MASSTOR_LIST *Mh, MASSTOR_LIST *L));
extern MASSTOR_LIST RRINT_RRIQUADFORM ARGS((MASSTOR_LIST R, MASSTOR_LIST U, MASSTOR_LIST beta, MASSTOR_LIST Mh));
extern MASSTOR_LIST RRINT_RRICOUNT ARGS((MASSTOR_LIST G, MASSTOR_LIST H, MASSTOR_LIST v, MASSTOR_LIST tf));
extern void BEGIN_RRINT();
