#define DEFINITION_RRUADOM

#ifndef DEFINITION_MASSTOR
#include "MASSTOR.h"
#endif

extern CHAR RRUADOM_rcsid[];
extern CHAR RRUADOM_copyright[];
extern MASSTOR_LIST RRUADOM_RRUADPOLTOVEC ARGS((MASSTOR_LIST D, MASSTOR_LIST g, MASSTOR_LIST d));
extern MASSTOR_LIST RRUADOM_RRUADSTRCONST ARGS((MASSTOR_LIST D, MASSTOR_LIST f, MASSTOR_LIST h));
extern MASSTOR_LIST RRUADOM_RRUADQUADFORM ARGS((MASSTOR_LIST beta));
extern MASSTOR_LIST RRUADOM_RRUADCOUNT ARGS((MASSTOR_LIST D, MASSTOR_LIST f, MASSTOR_LIST H, MASSTOR_LIST v, MASSTOR_LIST tf));
extern void BEGIN_RRUADOM();
