#define DEFINITION_RRUINT

#ifndef DEFINITION_MASSTOR
#include "MASSTOR.h"
#endif

extern CHAR RRUINT_rcsid[];
extern CHAR RRUINT_copyright[];
extern MASSTOR_LIST RRUINT_RRUIPOLTOVEC ARGS((MASSTOR_LIST g, MASSTOR_LIST d));
extern MASSTOR_LIST RRUINT_RRUISTRCONST ARGS((MASSTOR_LIST f, MASSTOR_LIST h));
extern MASSTOR_LIST RRUINT_RRUIQUADFORM ARGS((MASSTOR_LIST beta));
extern MASSTOR_LIST RRUINT_RRUICOUNT ARGS((MASSTOR_LIST f, MASSTOR_LIST H, MASSTOR_LIST V, MASSTOR_LIST tf));
extern void BEGIN_RRUINT();
