#define DEFINITION_SACANF

#ifndef DEFINITION_MASSTOR
#include "MASSTOR.h"
#endif

extern CHAR SACANF_rcsid[];
extern CHAR SACANF_copyright[];
extern MASSTOR_LIST SACANF_AFDIF ARGS((MASSTOR_LIST AL, MASSTOR_LIST BL));
extern MASSTOR_LIST SACANF_AFINV ARGS((MASSTOR_LIST M, MASSTOR_LIST AL));
extern MASSTOR_LIST SACANF_AFNEG ARGS((MASSTOR_LIST AL));
extern MASSTOR_LIST SACANF_AFPROD ARGS((MASSTOR_LIST M, MASSTOR_LIST AL, MASSTOR_LIST BL));
extern MASSTOR_LIST SACANF_AFQ ARGS((MASSTOR_LIST M, MASSTOR_LIST AL, MASSTOR_LIST BL));
extern MASSTOR_LIST SACANF_AFSIGN ARGS((MASSTOR_LIST M, MASSTOR_LIST I, MASSTOR_LIST AL));
extern MASSTOR_LIST SACANF_AFSUM ARGS((MASSTOR_LIST AL, MASSTOR_LIST BL));
extern MASSTOR_LIST SACANF_RUPMRN ARGS((MASSTOR_LIST R));
extern void BEGIN_SACANF();
