#define DEFINITION_SACBIOS

#ifndef DEFINITION_MASELEM
#include "MASELEM.h"
#endif

extern CHAR SACBIOS_rcsid[];
extern CHAR SACBIOS_copyright[];
extern void SACBIOS_CWRIT2 ARGS((MASELEM_GAMMAINT C1, MASELEM_GAMMAINT C2));
extern void SACBIOS_CWRIT3 ARGS((MASELEM_GAMMAINT C1, MASELEM_GAMMAINT C2, MASELEM_GAMMAINT C3));
extern void SACBIOS_CWRIT4 ARGS((MASELEM_GAMMAINT C1, MASELEM_GAMMAINT C2, MASELEM_GAMMAINT C3, MASELEM_GAMMAINT C4));
extern void SACBIOS_CWRIT5 ARGS((MASELEM_GAMMAINT C1, MASELEM_GAMMAINT C2, MASELEM_GAMMAINT C3, MASELEM_GAMMAINT C4, MASELEM_GAMMAINT C5));
extern void SACBIOS_CWRIT6 ARGS((MASELEM_GAMMAINT C1, MASELEM_GAMMAINT C2, MASELEM_GAMMAINT C3, MASELEM_GAMMAINT C4, MASELEM_GAMMAINT C5, MASELEM_GAMMAINT C6));
extern void BEGIN_SACBIOS();
