#define DEFINITION_SACCOMB

#ifndef DEFINITION_MASSTOR
#include "MASSTOR.h"
#endif

extern CHAR SACCOMB_rcsid[];
extern CHAR SACCOMB_copyright[];
extern void SACCOMB_ASSPR ARGS((MASSTOR_LIST C_1_A, MASSTOR_LIST *PL, MASSTOR_LIST *ML));
extern MASSTOR_LIST SACCOMB_CSFPAR ARGS((MASSTOR_LIST L));
extern MASSTOR_LIST SACCOMB_CSINT ARGS((MASSTOR_LIST C_2_A, MASSTOR_LIST B));
extern MASSTOR_LIST SACCOMB_CSSUB ARGS((MASSTOR_LIST C_3_A, MASSTOR_LIST B));
extern MASSTOR_LIST SACCOMB_CSUN ARGS((MASSTOR_LIST C_4_A, MASSTOR_LIST B));
extern MASSTOR_LIST SACCOMB_DAND ARGS((MASSTOR_LIST AL, MASSTOR_LIST BL));
extern MASSTOR_LIST SACCOMB_DNIMP ARGS((MASSTOR_LIST AL, MASSTOR_LIST BL));
extern MASSTOR_LIST SACCOMB_DNOT ARGS((MASSTOR_LIST AL));
extern MASSTOR_LIST SACCOMB_DOR ARGS((MASSTOR_LIST AL, MASSTOR_LIST BL));
extern MASSTOR_LIST SACCOMB_IBCIND ARGS((MASSTOR_LIST C_5_A, MASSTOR_LIST NL, MASSTOR_LIST KL));
extern MASSTOR_LIST SACCOMB_IBCOEF ARGS((MASSTOR_LIST NL, MASSTOR_LIST KL));
extern MASSTOR_LIST SACCOMB_IBCPS ARGS((MASSTOR_LIST NL, MASSTOR_LIST KL));
extern MASSTOR_LIST SACCOMB_IFACTL ARGS((MASSTOR_LIST NL));
extern MASSTOR_LIST SACCOMB_LEXNEX ARGS((MASSTOR_LIST C_6_A));
extern MASSTOR_LIST SACCOMB_LPERM ARGS((MASSTOR_LIST L, MASSTOR_LIST P));
extern MASSTOR_LIST SACCOMB_PARTN ARGS((MASSTOR_LIST NL, MASSTOR_LIST P));
extern MASSTOR_LIST SACCOMB_PARTR ARGS((MASSTOR_LIST NL));
extern MASSTOR_LIST SACCOMB_PARTSS ARGS((MASSTOR_LIST PL));
extern MASSTOR_LIST SACCOMB_PERMR ARGS((MASSTOR_LIST NL));
extern void SACCOMB_SDR ARGS((MASSTOR_LIST S, MASSTOR_LIST *C_7_A, MASSTOR_LIST *I));
extern MASSTOR_LIST SACCOMB_SFCS ARGS((MASSTOR_LIST C_8_A));
extern void BEGIN_SACCOMB();
