#define DEFINITION_SACDPOL

#ifndef DEFINITION_MASSTOR
#include "MASSTOR.h"
#endif

extern CHAR SACDPOL_rcsid[];
extern CHAR SACDPOL_copyright[];
extern MASSTOR_LIST SACDPOL_DMPPRD ARGS((MASSTOR_LIST RL, MASSTOR_LIST ML, MASSTOR_LIST C_1_A, MASSTOR_LIST B));
extern MASSTOR_LIST SACDPOL_DMPSUM ARGS((MASSTOR_LIST RL, MASSTOR_LIST ML, MASSTOR_LIST C_2_A, MASSTOR_LIST B));
extern MASSTOR_LIST SACDPOL_DMUPNR ARGS((MASSTOR_LIST PL, MASSTOR_LIST C_3_A, MASSTOR_LIST B));
extern MASSTOR_LIST SACDPOL_DPFP ARGS((MASSTOR_LIST RL, MASSTOR_LIST C_4_A));
extern void BEGIN_SACDPOL();
