#define DEFINITION_SACD

#ifndef DEFINITION_MASSTOR
#include "MASSTOR.h"
#endif

extern MASSTOR_LIST SACD_THETA, SACD_ZETA, SACD_DELTA, SACD_ETA, SACD_EPSIL;
extern struct SACD_1 {
    MASSTOR_LIST A[64 - 1 + 1];
} SACD_TABP2;
extern CHAR SACD_rcsid[];
extern CHAR SACD_copyright[];
extern MASSTOR_LIST SACD_BITRAN ARGS(());
extern void SACD_DEGCD ARGS((MASSTOR_LIST AL, MASSTOR_LIST BL, MASSTOR_LIST *CL, MASSTOR_LIST *UL, MASSTOR_LIST *VL));
extern MASSTOR_LIST SACD_DGCD ARGS((MASSTOR_LIST AL, MASSTOR_LIST BL));
extern MASSTOR_LIST SACD_DLOG2 ARGS((MASSTOR_LIST AL));
extern void SACD_DPCC ARGS((MASSTOR_LIST AL1, MASSTOR_LIST AL2, MASSTOR_LIST *UL, MASSTOR_LIST *ULP, MASSTOR_LIST *VL, MASSTOR_LIST *VLP));
extern void SACD_DPR ARGS((MASSTOR_LIST AL, MASSTOR_LIST BL, MASSTOR_LIST *CL, MASSTOR_LIST *DL));
extern void SACD_DQR ARGS((MASSTOR_LIST AL1, MASSTOR_LIST AL0, MASSTOR_LIST BL, MASSTOR_LIST *QL, MASSTOR_LIST *RL));
extern MASSTOR_LIST SACD_DRAN ARGS(());
extern MASSTOR_LIST SACD_DRANN ARGS(());
extern void SACD_DSQRTF ARGS((MASSTOR_LIST AL, MASSTOR_LIST *BL, MASSTOR_LIST *TL));
extern void BEGIN_SACD();
