#define DEFINITION_SACEXT2

#ifndef DEFINITION_MASSTOR
#include "MASSTOR.h"
#endif

extern CHAR SACEXT2_rcsid[];
extern CHAR SACEXT2_copyright[];
extern void SACEXT2_RNBCR ARGS((MASSTOR_LIST C_1_A, MASSTOR_LIST B, MASSTOR_LIST *M, MASSTOR_LIST *N, MASSTOR_LIST *KL));
extern void BEGIN_SACEXT2();
