#define DEFINITION_SACEXT3

#ifndef DEFINITION_MASSTOR
#include "MASSTOR.h"
#endif

extern CHAR SACEXT3_rcsid[];
extern CHAR SACEXT3_copyright[];
extern void SACEXT3_CPLEXN ARGS((MASSTOR_LIST L, MASSTOR_LIST *I, MASSTOR_LIST *M));
extern MASSTOR_LIST SACEXT3_PERMCY ARGS((MASSTOR_LIST P));
extern void BEGIN_SACEXT3();
