#define DEFINITION_SACEXT1

#ifndef DEFINITION_MASSTOR
#include "MASSTOR.h"
#endif

extern CHAR SACEXT1_rcsid[];
extern CHAR SACEXT1_copyright[];
extern MASSTOR_LIST SACEXT1_LCONC ARGS((MASSTOR_LIST L));
extern MASSTOR_LIST SACEXT1_LEQUAL ARGS((MASSTOR_LIST C_1_A, MASSTOR_LIST B));
extern MASSTOR_LIST SACEXT1_LMERGE ARGS((MASSTOR_LIST C_2_A, MASSTOR_LIST B));
extern void BEGIN_SACEXT1();
