#define DEFINITION_SACEXT4

#ifndef DEFINITION_MASSTOR
#include "MASSTOR.h"
#endif

extern CHAR SACEXT4_rcsid[];
extern CHAR SACEXT4_copyright[];
extern MASSTOR_LIST SACEXT4_IPINT ARGS((MASSTOR_LIST RL, MASSTOR_LIST C_1_A, MASSTOR_LIST BL));
extern MASSTOR_LIST SACEXT4_IUPIHT ARGS((MASSTOR_LIST C_2_A, MASSTOR_LIST NL));
extern MASSTOR_LIST SACEXT4_PCONST ARGS((MASSTOR_LIST RL, MASSTOR_LIST C_3_A));
extern MASSTOR_LIST SACEXT4_PSDSV ARGS((MASSTOR_LIST RL, MASSTOR_LIST C_4_A, MASSTOR_LIST IL, MASSTOR_LIST NL));
extern MASSTOR_LIST SACEXT4_PUNT ARGS((MASSTOR_LIST RL, MASSTOR_LIST C_5_A));
extern MASSTOR_LIST SACEXT4_RPDMV ARGS((MASSTOR_LIST RL, MASSTOR_LIST C_6_A));
extern MASSTOR_LIST SACEXT4_RPMAIP ARGS((MASSTOR_LIST RL, MASSTOR_LIST C_7_A));
extern void BEGIN_SACEXT4();
