#define DEFINITION_SACEXT8

#ifndef DEFINITION_MASSTOR
#include "MASSTOR.h"
#endif

extern CHAR SACEXT8_rcsid[];
extern CHAR SACEXT8_copyright[];
extern MASSTOR_LIST SACEXT8_AFCOMP ARGS((MASSTOR_LIST MB, MASSTOR_LIST I, MASSTOR_LIST AL, MASSTOR_LIST BL));
extern MASSTOR_LIST SACEXT8_AFFINT ARGS((MASSTOR_LIST M));
extern MASSTOR_LIST SACEXT8_AFFRN ARGS((MASSTOR_LIST R));
extern MASSTOR_LIST SACEXT8_AFPAFP ARGS((MASSTOR_LIST RL, MASSTOR_LIST M, MASSTOR_LIST AL, MASSTOR_LIST B));
extern MASSTOR_LIST SACEXT8_AFPAFQ ARGS((MASSTOR_LIST RL, MASSTOR_LIST M, MASSTOR_LIST C_1_A, MASSTOR_LIST BL));
extern MASSTOR_LIST SACEXT8_AFPDIF ARGS((MASSTOR_LIST RL, MASSTOR_LIST C_2_A, MASSTOR_LIST B));
extern MASSTOR_LIST SACEXT8_AFPDMV ARGS((MASSTOR_LIST RL, MASSTOR_LIST M, MASSTOR_LIST C_3_A));
extern MASSTOR_LIST SACEXT8_AFPEMV ARGS((MASSTOR_LIST RL, MASSTOR_LIST M, MASSTOR_LIST C_4_A, MASSTOR_LIST AL));
extern MASSTOR_LIST SACEXT8_AFPEV ARGS((MASSTOR_LIST RL, MASSTOR_LIST M, MASSTOR_LIST C_5_A, MASSTOR_LIST IL, MASSTOR_LIST AL));
extern MASSTOR_LIST SACEXT8_AFPFIP ARGS((MASSTOR_LIST RL, MASSTOR_LIST C_6_A));
extern MASSTOR_LIST SACEXT8_AFPFRP ARGS((MASSTOR_LIST RL, MASSTOR_LIST C_7_A));
extern MASSTOR_LIST SACEXT8_AFPINT ARGS((MASSTOR_LIST RL, MASSTOR_LIST M, MASSTOR_LIST C_8_A, MASSTOR_LIST BL));
extern MASSTOR_LIST SACEXT8_AFPME ARGS((MASSTOR_LIST RL, MASSTOR_LIST M, MASSTOR_LIST C_9_A, MASSTOR_LIST BL));
extern MASSTOR_LIST SACEXT8_AFPMON ARGS((MASSTOR_LIST RL, MASSTOR_LIST M, MASSTOR_LIST C_10_A));
extern void SACEXT8_AFPMPR ARGS((MASSTOR_LIST M, MASSTOR_LIST MB, MASSTOR_LIST I, MASSTOR_LIST B, MASSTOR_LIST J, MASSTOR_LIST L, MASSTOR_LIST *JS, MASSTOR_LIST *JL));
extern MASSTOR_LIST SACEXT8_AFPNEG ARGS((MASSTOR_LIST RL, MASSTOR_LIST C_11_A));
extern MASSTOR_LIST SACEXT8_AFPNIP ARGS((MASSTOR_LIST MB, MASSTOR_LIST C_12_A));
extern MASSTOR_LIST SACEXT8_AFPPR ARGS((MASSTOR_LIST RL, MASSTOR_LIST M, MASSTOR_LIST C_13_A, MASSTOR_LIST B));
extern void SACEXT8_AFPQR ARGS((MASSTOR_LIST RL, MASSTOR_LIST M, MASSTOR_LIST C_14_A, MASSTOR_LIST B, MASSTOR_LIST *Q, MASSTOR_LIST *R));
extern void SACEXT8_AFPRLS ARGS((MASSTOR_LIST M, MASSTOR_LIST MB, MASSTOR_LIST I, MASSTOR_LIST A1, MASSTOR_LIST A2, MASSTOR_LIST L1, MASSTOR_LIST L2, MASSTOR_LIST *LS1, MASSTOR_LIST *LS2));
extern MASSTOR_LIST SACEXT8_AFPRRI ARGS((MASSTOR_LIST M, MASSTOR_LIST MB, MASSTOR_LIST I, MASSTOR_LIST C_15_A, MASSTOR_LIST B, MASSTOR_LIST J, MASSTOR_LIST SL1, MASSTOR_LIST TL1));
extern void SACEXT8_AFPRRS ARGS((MASSTOR_LIST M, MASSTOR_LIST MB, MASSTOR_LIST I, MASSTOR_LIST A1, MASSTOR_LIST A2, MASSTOR_LIST I1, MASSTOR_LIST I2, MASSTOR_LIST *IS1, MASSTOR_LIST *IS2, MASSTOR_LIST *SL));
extern MASSTOR_LIST SACEXT8_AFPSUM ARGS((MASSTOR_LIST RL, MASSTOR_LIST C_16_A, MASSTOR_LIST B));
extern MASSTOR_LIST SACEXT8_AFSUPB ARGS((MASSTOR_LIST M, MASSTOR_LIST C_17_A));
extern MASSTOR_LIST SACEXT8_AFUPBA ARGS((MASSTOR_LIST M, MASSTOR_LIST C_18_A, MASSTOR_LIST B));
extern MASSTOR_LIST SACEXT8_AFUPCB ARGS((MASSTOR_LIST M, MASSTOR_LIST C_19_A));
extern void SACEXT8_AFUPGC ARGS((MASSTOR_LIST M, MASSTOR_LIST C_20_A, MASSTOR_LIST B, MASSTOR_LIST *C, MASSTOR_LIST *AB, MASSTOR_LIST *BB));
extern MASSTOR_LIST SACEXT8_AFUPGS ARGS((MASSTOR_LIST M, MASSTOR_LIST C_21_A));
extern MASSTOR_LIST SACEXT8_AFUPRB ARGS((MASSTOR_LIST MB, MASSTOR_LIST I, MASSTOR_LIST C_22_A));
extern MASSTOR_LIST SACEXT8_AFUPRL ARGS((MASSTOR_LIST M, MASSTOR_LIST C_23_A));
extern MASSTOR_LIST SACEXT8_AFUPSF ARGS((MASSTOR_LIST M, MASSTOR_LIST C_24_A));
extern MASSTOR_LIST SACEXT8_AFUPSR ARGS((MASSTOR_LIST M, MASSTOR_LIST MB, MASSTOR_LIST I, MASSTOR_LIST C_25_A, MASSTOR_LIST CL));
extern void SACEXT8_ANDWR ARGS((MASSTOR_LIST M, MASSTOR_LIST I, MASSTOR_LIST NL));
extern void SACEXT8_ANFAF ARGS((MASSTOR_LIST M, MASSTOR_LIST I, MASSTOR_LIST AL, MASSTOR_LIST *N, MASSTOR_LIST *J));
extern void SACEXT8_ANIIPE ARGS((MASSTOR_LIST MB, MASSTOR_LIST I, MASSTOR_LIST NB, MASSTOR_LIST J, MASSTOR_LIST TL, MASSTOR_LIST L, MASSTOR_LIST *S, MASSTOR_LIST *KL, MASSTOR_LIST *K));
extern void SACEXT8_ANPEDE ARGS((MASSTOR_LIST MB, MASSTOR_LIST NB, MASSTOR_LIST *TL, MASSTOR_LIST *S, MASSTOR_LIST *T));
extern MASSTOR_LIST SACEXT8_ANREPE ARGS((MASSTOR_LIST M, MASSTOR_LIST MB, MASSTOR_LIST C_26_A, MASSTOR_LIST B));
extern void SACEXT8_APDWR ARGS((MASSTOR_LIST M, MASSTOR_LIST I, MASSTOR_LIST BL, MASSTOR_LIST NL));
extern MASSTOR_LIST SACEXT8_IPAFME ARGS((MASSTOR_LIST RL, MASSTOR_LIST M, MASSTOR_LIST C_27_A, MASSTOR_LIST BL));
extern MASSTOR_LIST SACEXT8_IUPMRN ARGS((MASSTOR_LIST R));
extern MASSTOR_LIST SACEXT8_RPAFME ARGS((MASSTOR_LIST RL, MASSTOR_LIST M, MASSTOR_LIST C_28_A, MASSTOR_LIST BL));
extern void BEGIN_SACEXT8();
