#define DEFINITION_SACLDIO

#ifndef DEFINITION_MASSTOR
#include "MASSTOR.h"
#endif

extern CHAR SACLDIO_rcsid[];
extern CHAR SACLDIO_copyright[];
extern void SACLDIO_LDSMKB ARGS((MASSTOR_LIST C_1_A, MASSTOR_LIST BL, MASSTOR_LIST *XLS, MASSTOR_LIST *N));
extern void SACLDIO_LDSSBR ARGS((MASSTOR_LIST C_2_A, MASSTOR_LIST BL, MASSTOR_LIST *XLS, MASSTOR_LIST *N));
extern MASSTOR_LIST SACLDIO_MAIPDE ARGS((MASSTOR_LIST RL, MASSTOR_LIST M));
extern MASSTOR_LIST SACLDIO_MAIPDM ARGS((MASSTOR_LIST RL, MASSTOR_LIST M));
extern MASSTOR_LIST SACLDIO_MAIPHM ARGS((MASSTOR_LIST RL, MASSTOR_LIST ML, MASSTOR_LIST C_3_A));
extern MASSTOR_LIST SACLDIO_MAIPP ARGS((MASSTOR_LIST RL, MASSTOR_LIST C_4_A, MASSTOR_LIST B));
extern MASSTOR_LIST SACLDIO_MIAIM ARGS((MASSTOR_LIST C_5_A));
extern MASSTOR_LIST SACLDIO_MICINS ARGS((MASSTOR_LIST C_6_A, MASSTOR_LIST V));
extern MASSTOR_LIST SACLDIO_MICS ARGS((MASSTOR_LIST C_7_A));
extern MASSTOR_LIST SACLDIO_MINNCT ARGS((MASSTOR_LIST C_8_A));
extern MASSTOR_LIST SACLDIO_MMDDET ARGS((MASSTOR_LIST PL, MASSTOR_LIST M));
extern MASSTOR_LIST SACLDIO_MMDNSB ARGS((MASSTOR_LIST PL, MASSTOR_LIST M));
extern MASSTOR_LIST SACLDIO_MMPDMA ARGS((MASSTOR_LIST RL, MASSTOR_LIST PL, MASSTOR_LIST M));
extern MASSTOR_LIST SACLDIO_MMPEV ARGS((MASSTOR_LIST RL, MASSTOR_LIST ML, MASSTOR_LIST C_9_A, MASSTOR_LIST KL, MASSTOR_LIST AL));
extern MASSTOR_LIST SACLDIO_VIAZ ARGS((MASSTOR_LIST C_10_A, MASSTOR_LIST NL));
extern MASSTOR_LIST SACLDIO_VIDIF ARGS((MASSTOR_LIST C_11_A, MASSTOR_LIST B));
extern MASSTOR_LIST SACLDIO_VIERED ARGS((MASSTOR_LIST U, MASSTOR_LIST V, MASSTOR_LIST IL));
extern MASSTOR_LIST SACLDIO_VILCOM ARGS((MASSTOR_LIST AL, MASSTOR_LIST BL, MASSTOR_LIST C_12_A, MASSTOR_LIST B));
extern MASSTOR_LIST SACLDIO_VINEG ARGS((MASSTOR_LIST C_13_A));
extern MASSTOR_LIST SACLDIO_VISPR ARGS((MASSTOR_LIST AL, MASSTOR_LIST C_14_A));
extern MASSTOR_LIST SACLDIO_VISUM ARGS((MASSTOR_LIST C_15_A, MASSTOR_LIST B));
extern void SACLDIO_VIUT ARGS((MASSTOR_LIST U, MASSTOR_LIST V, MASSTOR_LIST IL, MASSTOR_LIST *UP, MASSTOR_LIST *VP));
extern void BEGIN_SACLDIO();
