#define DEFINITION_SACMUFAC

#ifndef DEFINITION_MASSTOR
#include "MASSTOR.h"
#endif

extern CHAR SACMUFAC_rcsid[];
extern CHAR SACMUFAC_copyright[];
extern MASSTOR_LIST SACMUFAC_MCPMV ARGS((MASSTOR_LIST NL, MASSTOR_LIST L));
extern void SACMUFAC_MIUPSE ARGS((MASSTOR_LIST M, MASSTOR_LIST C_1_A, MASSTOR_LIST B, MASSTOR_LIST S, MASSTOR_LIST T, MASSTOR_LIST C, MASSTOR_LIST *U, MASSTOR_LIST *V));
extern MASSTOR_LIST SACMUFAC_MUPBQP ARGS((MASSTOR_LIST PL, MASSTOR_LIST C_2_A));
extern MASSTOR_LIST SACMUFAC_MUPDDF ARGS((MASSTOR_LIST PL, MASSTOR_LIST C_3_A));
extern MASSTOR_LIST SACMUFAC_MUPFBL ARGS((MASSTOR_LIST PL, MASSTOR_LIST C_4_A));
extern MASSTOR_LIST SACMUFAC_MUPFS ARGS((MASSTOR_LIST PL, MASSTOR_LIST C_5_A, MASSTOR_LIST B, MASSTOR_LIST DL));
extern void BEGIN_SACMUFAC();
