#define DEFINITION_SACM

#ifndef DEFINITION_MASSTOR
#include "MASSTOR.h"
#endif

extern CHAR SACM_rcsid[];
extern CHAR SACM_copyright[];
extern MASSTOR_LIST SACM_MDCRA ARGS((MASSTOR_LIST ML1, MASSTOR_LIST ML2, MASSTOR_LIST MLP1, MASSTOR_LIST AL1, MASSTOR_LIST AL2));
extern MASSTOR_LIST SACM_MDDIF ARGS((MASSTOR_LIST ML, MASSTOR_LIST AL, MASSTOR_LIST BL));
extern MASSTOR_LIST SACM_MDEXP ARGS((MASSTOR_LIST ML, MASSTOR_LIST AL, MASSTOR_LIST NL));
extern MASSTOR_LIST SACM_MDHOM ARGS((MASSTOR_LIST ML, MASSTOR_LIST C_1_A));
extern MASSTOR_LIST SACM_MDINV ARGS((MASSTOR_LIST ML, MASSTOR_LIST AL));
extern MASSTOR_LIST SACM_MDLCRA ARGS((MASSTOR_LIST ML1, MASSTOR_LIST ML2, MASSTOR_LIST L1, MASSTOR_LIST L2));
extern MASSTOR_LIST SACM_MDNEG ARGS((MASSTOR_LIST ML, MASSTOR_LIST AL));
extern MASSTOR_LIST SACM_MDPROD ARGS((MASSTOR_LIST ML, MASSTOR_LIST AL, MASSTOR_LIST BL));
extern MASSTOR_LIST SACM_MDQ ARGS((MASSTOR_LIST ML, MASSTOR_LIST AL, MASSTOR_LIST BL));
extern MASSTOR_LIST SACM_MDRAN ARGS((MASSTOR_LIST ML));
extern MASSTOR_LIST SACM_MDSUM ARGS((MASSTOR_LIST ML, MASSTOR_LIST AL, MASSTOR_LIST BL));
extern MASSTOR_LIST SACM_MIDCRA ARGS((MASSTOR_LIST M, MASSTOR_LIST ML, MASSTOR_LIST MLP, MASSTOR_LIST C_2_A, MASSTOR_LIST AL));
extern MASSTOR_LIST SACM_MIDIF ARGS((MASSTOR_LIST M, MASSTOR_LIST C_3_A, MASSTOR_LIST B));
extern MASSTOR_LIST SACM_MIEXP ARGS((MASSTOR_LIST M, MASSTOR_LIST C_4_A, MASSTOR_LIST N));
extern MASSTOR_LIST SACM_MIHOM ARGS((MASSTOR_LIST M, MASSTOR_LIST C_5_A));
extern MASSTOR_LIST SACM_MIINV ARGS((MASSTOR_LIST M, MASSTOR_LIST C_6_A));
extern MASSTOR_LIST SACM_MINEG ARGS((MASSTOR_LIST M, MASSTOR_LIST C_7_A));
extern MASSTOR_LIST SACM_MIPROD ARGS((MASSTOR_LIST M, MASSTOR_LIST C_8_A, MASSTOR_LIST B));
extern MASSTOR_LIST SACM_MIQ ARGS((MASSTOR_LIST M, MASSTOR_LIST C_9_A, MASSTOR_LIST B));
extern MASSTOR_LIST SACM_MIRAN ARGS((MASSTOR_LIST M));
extern MASSTOR_LIST SACM_MISUM ARGS((MASSTOR_LIST M, MASSTOR_LIST C_10_A, MASSTOR_LIST B));
extern MASSTOR_LIST SACM_SMFMI ARGS((MASSTOR_LIST M, MASSTOR_LIST C_11_A));
extern void BEGIN_SACM();
