#define DEFINITION_SACMPOL

#ifndef DEFINITION_MASSTOR
#include "MASSTOR.h"
#endif

extern CHAR SACMPOL_rcsid[];
extern CHAR SACMPOL_copyright[];
extern MASSTOR_LIST SACMPOL_MIPDIF ARGS((MASSTOR_LIST RL, MASSTOR_LIST M, MASSTOR_LIST C_1_A, MASSTOR_LIST B));
extern MASSTOR_LIST SACMPOL_MIPFSM ARGS((MASSTOR_LIST RL, MASSTOR_LIST M, MASSTOR_LIST C_2_A));
extern MASSTOR_LIST SACMPOL_MIPHOM ARGS((MASSTOR_LIST RL, MASSTOR_LIST M, MASSTOR_LIST C_3_A));
extern MASSTOR_LIST SACMPOL_MIPIPR ARGS((MASSTOR_LIST RL, MASSTOR_LIST M, MASSTOR_LIST D, MASSTOR_LIST C_4_A, MASSTOR_LIST B));
extern MASSTOR_LIST SACMPOL_MIPNEG ARGS((MASSTOR_LIST RL, MASSTOR_LIST M, MASSTOR_LIST C_5_A));
extern MASSTOR_LIST SACMPOL_MIPPR ARGS((MASSTOR_LIST RL, MASSTOR_LIST M, MASSTOR_LIST C_6_A, MASSTOR_LIST B));
extern MASSTOR_LIST SACMPOL_MIPRAN ARGS((MASSTOR_LIST RL, MASSTOR_LIST M, MASSTOR_LIST QL, MASSTOR_LIST N));
extern MASSTOR_LIST SACMPOL_MIPSUM ARGS((MASSTOR_LIST RL, MASSTOR_LIST M, MASSTOR_LIST C_7_A, MASSTOR_LIST B));
extern void SACMPOL_MIUPQR ARGS((MASSTOR_LIST M, MASSTOR_LIST C_8_A, MASSTOR_LIST B, MASSTOR_LIST *Q, MASSTOR_LIST *R));
extern void SACMPOL_MMPIQR ARGS((MASSTOR_LIST RL, MASSTOR_LIST M, MASSTOR_LIST D, MASSTOR_LIST C_9_A, MASSTOR_LIST B, MASSTOR_LIST *Q, MASSTOR_LIST *R));
extern MASSTOR_LIST SACMPOL_MPDIF ARGS((MASSTOR_LIST RL, MASSTOR_LIST ML, MASSTOR_LIST C_10_A, MASSTOR_LIST B));
extern MASSTOR_LIST SACMPOL_MPEMV ARGS((MASSTOR_LIST RL, MASSTOR_LIST ML, MASSTOR_LIST C_11_A, MASSTOR_LIST AL));
extern MASSTOR_LIST SACMPOL_MPEVAL ARGS((MASSTOR_LIST RL, MASSTOR_LIST ML, MASSTOR_LIST C_12_A, MASSTOR_LIST IL, MASSTOR_LIST AL));
extern MASSTOR_LIST SACMPOL_MPEXP ARGS((MASSTOR_LIST RL, MASSTOR_LIST ML, MASSTOR_LIST C_13_A, MASSTOR_LIST NL));
extern MASSTOR_LIST SACMPOL_MPHOM ARGS((MASSTOR_LIST RL, MASSTOR_LIST ML, MASSTOR_LIST C_14_A));
extern MASSTOR_LIST SACMPOL_MPINT ARGS((MASSTOR_LIST PL, MASSTOR_LIST B, MASSTOR_LIST BL, MASSTOR_LIST BLP, MASSTOR_LIST RL, MASSTOR_LIST C_15_A, MASSTOR_LIST A1));
extern MASSTOR_LIST SACMPOL_MPMDP ARGS((MASSTOR_LIST RL, MASSTOR_LIST PL, MASSTOR_LIST AL, MASSTOR_LIST B));
extern MASSTOR_LIST SACMPOL_MPMON ARGS((MASSTOR_LIST RL, MASSTOR_LIST PL, MASSTOR_LIST C_16_A));
extern MASSTOR_LIST SACMPOL_MPNEG ARGS((MASSTOR_LIST RL, MASSTOR_LIST ML, MASSTOR_LIST C_17_A));
extern MASSTOR_LIST SACMPOL_MPPROD ARGS((MASSTOR_LIST RL, MASSTOR_LIST ML, MASSTOR_LIST C_18_A, MASSTOR_LIST B));
extern MASSTOR_LIST SACMPOL_MPPSR ARGS((MASSTOR_LIST RL, MASSTOR_LIST PL, MASSTOR_LIST C_19_A, MASSTOR_LIST B));
extern MASSTOR_LIST SACMPOL_MPQ ARGS((MASSTOR_LIST RL, MASSTOR_LIST PL, MASSTOR_LIST C_20_A, MASSTOR_LIST B));
extern void SACMPOL_MPQR ARGS((MASSTOR_LIST RL, MASSTOR_LIST PL, MASSTOR_LIST C_21_A, MASSTOR_LIST B, MASSTOR_LIST *Q, MASSTOR_LIST *R));
extern MASSTOR_LIST SACMPOL_MPRAN ARGS((MASSTOR_LIST RL, MASSTOR_LIST ML, MASSTOR_LIST QL, MASSTOR_LIST N));
extern MASSTOR_LIST SACMPOL_MPSUM ARGS((MASSTOR_LIST RL, MASSTOR_LIST ML, MASSTOR_LIST C_22_A, MASSTOR_LIST B));
extern MASSTOR_LIST SACMPOL_MPUP ARGS((MASSTOR_LIST RL, MASSTOR_LIST ML, MASSTOR_LIST CL, MASSTOR_LIST C_23_A));
extern MASSTOR_LIST SACMPOL_MPUQ ARGS((MASSTOR_LIST RL, MASSTOR_LIST PL, MASSTOR_LIST C_24_A, MASSTOR_LIST BL));
extern MASSTOR_LIST SACMPOL_MUPDER ARGS((MASSTOR_LIST ML, MASSTOR_LIST C_25_A));
extern MASSTOR_LIST SACMPOL_MUPRAN ARGS((MASSTOR_LIST PL, MASSTOR_LIST NL));
extern MASSTOR_LIST SACMPOL_SMFMIP ARGS((MASSTOR_LIST RL, MASSTOR_LIST M, MASSTOR_LIST C_26_A));
extern MASSTOR_LIST SACMPOL_VMPIP ARGS((MASSTOR_LIST RL, MASSTOR_LIST ML, MASSTOR_LIST C_27_A, MASSTOR_LIST B));
extern void BEGIN_SACMPOL();
