#define DEFINITION_SACPGCD

#ifndef DEFINITION_MASSTOR
#include "MASSTOR.h"
#endif

extern CHAR SACPGCD_rcsid[];
extern CHAR SACPGCD_copyright[];
extern MASSTOR_LIST SACPGCD_IPC ARGS((MASSTOR_LIST RL, MASSTOR_LIST C_1_A));
extern void SACPGCD_IPCPP ARGS((MASSTOR_LIST RL, MASSTOR_LIST C_2_A, MASSTOR_LIST *C, MASSTOR_LIST *AB));
extern void SACPGCD_IPGCDC ARGS((MASSTOR_LIST RL, MASSTOR_LIST C_3_A, MASSTOR_LIST B, MASSTOR_LIST *C, MASSTOR_LIST *AB, MASSTOR_LIST *BB));
extern MASSTOR_LIST SACPGCD_IPIC ARGS((MASSTOR_LIST RL, MASSTOR_LIST C_4_A));
extern void SACPGCD_IPICPP ARGS((MASSTOR_LIST RL, MASSTOR_LIST C_5_A, MASSTOR_LIST *AL, MASSTOR_LIST *AB));
extern MASSTOR_LIST SACPGCD_IPICS ARGS((MASSTOR_LIST RL, MASSTOR_LIST C_6_A, MASSTOR_LIST CL));
extern MASSTOR_LIST SACPGCD_IPIPP ARGS((MASSTOR_LIST RL, MASSTOR_LIST C_7_A));
extern MASSTOR_LIST SACPGCD_IPPGSD ARGS((MASSTOR_LIST RL, MASSTOR_LIST C_8_A));
extern MASSTOR_LIST SACPGCD_IPPP ARGS((MASSTOR_LIST RL, MASSTOR_LIST C_9_A));
extern MASSTOR_LIST SACPGCD_IPRES ARGS((MASSTOR_LIST RL, MASSTOR_LIST C_10_A, MASSTOR_LIST B));
extern MASSTOR_LIST SACPGCD_IPRPRS ARGS((MASSTOR_LIST RL, MASSTOR_LIST C_11_A, MASSTOR_LIST B));
extern void SACPGCD_IPSCPP ARGS((MASSTOR_LIST RL, MASSTOR_LIST C_12_A, MASSTOR_LIST *SL, MASSTOR_LIST *C, MASSTOR_LIST *AB));
extern MASSTOR_LIST SACPGCD_IPSF ARGS((MASSTOR_LIST RL, MASSTOR_LIST C_13_A));
extern MASSTOR_LIST SACPGCD_IPSPRS ARGS((MASSTOR_LIST RL, MASSTOR_LIST C_14_A, MASSTOR_LIST B));
extern void SACPGCD_IPSRP ARGS((MASSTOR_LIST RL, MASSTOR_LIST C_15_A, MASSTOR_LIST *AL, MASSTOR_LIST *AB));
extern void SACPGCD_MPGCDC ARGS((MASSTOR_LIST RL, MASSTOR_LIST PL, MASSTOR_LIST C_16_A, MASSTOR_LIST B, MASSTOR_LIST *C, MASSTOR_LIST *AB, MASSTOR_LIST *BB));
extern MASSTOR_LIST SACPGCD_MPRES ARGS((MASSTOR_LIST RL, MASSTOR_LIST PL, MASSTOR_LIST C_17_A, MASSTOR_LIST B));
extern MASSTOR_LIST SACPGCD_MPSPRS ARGS((MASSTOR_LIST RL, MASSTOR_LIST PL, MASSTOR_LIST C_18_A, MASSTOR_LIST B));
extern MASSTOR_LIST SACPGCD_MPUC ARGS((MASSTOR_LIST RL, MASSTOR_LIST PL, MASSTOR_LIST C_19_A));
extern void SACPGCD_MPUCPP ARGS((MASSTOR_LIST RL, MASSTOR_LIST PL, MASSTOR_LIST C_20_A, MASSTOR_LIST *AL, MASSTOR_LIST *AB));
extern MASSTOR_LIST SACPGCD_MPUCS ARGS((MASSTOR_LIST RL, MASSTOR_LIST PL, MASSTOR_LIST C_21_A, MASSTOR_LIST CL));
extern MASSTOR_LIST SACPGCD_MPUPP ARGS((MASSTOR_LIST RL, MASSTOR_LIST PL, MASSTOR_LIST C_22_A));
extern void SACPGCD_MUPEGC ARGS((MASSTOR_LIST PL, MASSTOR_LIST C_23_A, MASSTOR_LIST B, MASSTOR_LIST *C, MASSTOR_LIST *U, MASSTOR_LIST *V));
extern MASSTOR_LIST SACPGCD_MUPGCD ARGS((MASSTOR_LIST PL, MASSTOR_LIST C_24_A, MASSTOR_LIST B));
extern void SACPGCD_MUPHEG ARGS((MASSTOR_LIST PL, MASSTOR_LIST C_25_A, MASSTOR_LIST B, MASSTOR_LIST *C, MASSTOR_LIST *V));
extern MASSTOR_LIST SACPGCD_MUPRES ARGS((MASSTOR_LIST PL, MASSTOR_LIST C_26_A, MASSTOR_LIST B));
extern MASSTOR_LIST SACPGCD_MUPSFF ARGS((MASSTOR_LIST PL, MASSTOR_LIST C_27_A));
extern void SACPGCD_RPBLGS ARGS((MASSTOR_LIST RL, MASSTOR_LIST C_28_A, MASSTOR_LIST *AL, MASSTOR_LIST *BL, MASSTOR_LIST *SL));
extern void BEGIN_SACPGCD();
