#define DEFINITION_SACPRIM

#ifndef DEFINITION_MASSTOR
#include "MASSTOR.h"
#endif

extern MASSTOR_LIST SACPRIM_UZ210, SACPRIM_SMPRM;
extern CHAR SACPRIM_rcsid[];
extern CHAR SACPRIM_copyright[];
extern MASSTOR_LIST SACPRIM_DPGEN ARGS((MASSTOR_LIST ML, MASSTOR_LIST K));
extern void SACPRIM_FRESL ARGS((MASSTOR_LIST NL, MASSTOR_LIST *ML, MASSTOR_LIST *L));
extern MASSTOR_LIST SACPRIM_FRLSM ARGS((MASSTOR_LIST ML, MASSTOR_LIST AL));
extern MASSTOR_LIST SACPRIM_GDPGEN ARGS((MASSTOR_LIST ML, INTEGER KL));
extern MASSTOR_LIST SACPRIM_IFACT ARGS((MASSTOR_LIST NL));
extern void SACPRIM_ILPDS ARGS((MASSTOR_LIST NL, MASSTOR_LIST AL, MASSTOR_LIST BL, MASSTOR_LIST *PL, MASSTOR_LIST *NLP));
extern void SACPRIM_IMPDS ARGS((MASSTOR_LIST NL, MASSTOR_LIST AL, MASSTOR_LIST BL, MASSTOR_LIST *PL, MASSTOR_LIST *QL));
extern void SACPRIM_ISPD ARGS((MASSTOR_LIST NL, MASSTOR_LIST *F, MASSTOR_LIST *ML));
extern MASSTOR_LIST SACPRIM_ISPT ARGS((MASSTOR_LIST ML, MASSTOR_LIST MLP, MASSTOR_LIST F));
extern void BEGIN_SACPRIM();
