#define DEFINITION_SACPOL

#ifndef DEFINITION_MASSTOR
#include "MASSTOR.h"
#endif

extern MASSTOR_LIST SACPOL_PRIME;
extern CHAR SACPOL_rcsid[];
extern CHAR SACPOL_copyright[];
extern MASSTOR_LIST SACPOL_PBIN ARGS((MASSTOR_LIST AL1, MASSTOR_LIST EL1, MASSTOR_LIST AL2, MASSTOR_LIST EL2));
extern MASSTOR_LIST SACPOL_PCL ARGS((MASSTOR_LIST C_1_A));
extern MASSTOR_LIST SACPOL_PDBORD ARGS((MASSTOR_LIST C_2_A));
extern MASSTOR_LIST SACPOL_PDEG ARGS((MASSTOR_LIST C_3_A));
extern MASSTOR_LIST SACPOL_PDEGSV ARGS((MASSTOR_LIST RL, MASSTOR_LIST C_4_A, MASSTOR_LIST IL));
extern MASSTOR_LIST SACPOL_PDEGV ARGS((MASSTOR_LIST RL, MASSTOR_LIST C_5_A));
extern MASSTOR_LIST SACPOL_PDPV ARGS((MASSTOR_LIST RL, MASSTOR_LIST C_6_A, MASSTOR_LIST IL, MASSTOR_LIST NL));
extern MASSTOR_LIST SACPOL_PFDP ARGS((MASSTOR_LIST RL, MASSTOR_LIST C_7_A));
extern MASSTOR_LIST SACPOL_PINV ARGS((MASSTOR_LIST RL, MASSTOR_LIST C_8_A, MASSTOR_LIST KL));
extern MASSTOR_LIST SACPOL_PLBCF ARGS((MASSTOR_LIST RL, MASSTOR_LIST C_9_A));
extern MASSTOR_LIST SACPOL_PLDCF ARGS((MASSTOR_LIST C_10_A));
extern MASSTOR_LIST SACPOL_PMDEG ARGS((MASSTOR_LIST C_11_A));
extern MASSTOR_LIST SACPOL_PMON ARGS((MASSTOR_LIST AL, MASSTOR_LIST EL));
extern MASSTOR_LIST SACPOL_PMPMV ARGS((MASSTOR_LIST C_12_A, MASSTOR_LIST KL));
extern MASSTOR_LIST SACPOL_PORD ARGS((MASSTOR_LIST C_13_A));
extern MASSTOR_LIST SACPOL_PRED ARGS((MASSTOR_LIST C_14_A));
extern MASSTOR_LIST SACPOL_PRT ARGS((MASSTOR_LIST C_15_A));
extern MASSTOR_LIST SACPOL_PTBCF ARGS((MASSTOR_LIST RL, MASSTOR_LIST C_16_A));
extern MASSTOR_LIST SACPOL_PUFP ARGS((MASSTOR_LIST RL, MASSTOR_LIST C_17_A));
extern MASSTOR_LIST SACPOL_VCOMP ARGS((MASSTOR_LIST U, MASSTOR_LIST V));
extern MASSTOR_LIST SACPOL_VLREAD ARGS(());
extern MASSTOR_LIST SACPOL_VLSRCH ARGS((MASSTOR_LIST VL, MASSTOR_LIST V));
extern void SACPOL_VLWRIT ARGS((MASSTOR_LIST V));
extern MASSTOR_LIST SACPOL_VMAX ARGS((MASSTOR_LIST U, MASSTOR_LIST V));
extern MASSTOR_LIST SACPOL_VMIN ARGS((MASSTOR_LIST U, MASSTOR_LIST V));
extern MASSTOR_LIST SACPOL_VREAD ARGS(());
extern void BEGIN_SACPOL();
