#define DEFINITION_SACROOT

#ifndef DEFINITION_MASSTOR
#include "MASSTOR.h"
#endif

extern CHAR SACROOT_rcsid[];
extern CHAR SACROOT_copyright[];
extern MASSTOR_LIST SACROOT_IIC ARGS((MASSTOR_LIST C_1_A, MASSTOR_LIST AP, MASSTOR_LIST I, MASSTOR_LIST L));
extern MASSTOR_LIST SACROOT_IPFSD ARGS((MASSTOR_LIST RL, MASSTOR_LIST C_2_A));
extern MASSTOR_LIST SACROOT_IPLRRI ARGS((MASSTOR_LIST L));
extern MASSTOR_LIST SACROOT_IPRCH ARGS((MASSTOR_LIST C_3_A, MASSTOR_LIST I, MASSTOR_LIST KL));
extern MASSTOR_LIST SACROOT_IPRCHS ARGS((MASSTOR_LIST C_4_A, MASSTOR_LIST I, MASSTOR_LIST KL));
extern void SACROOT_IPRCNP ARGS((MASSTOR_LIST C_5_A, MASSTOR_LIST I, MASSTOR_LIST *SLP, MASSTOR_LIST *SLPP, MASSTOR_LIST *J));
extern MASSTOR_LIST SACROOT_IPRCN1 ARGS((MASSTOR_LIST C_6_A, MASSTOR_LIST I, MASSTOR_LIST SL, MASSTOR_LIST KL));
extern MASSTOR_LIST SACROOT_IPRIM ARGS((MASSTOR_LIST C_7_A));
extern MASSTOR_LIST SACROOT_IPRIMO ARGS((MASSTOR_LIST C_8_A, MASSTOR_LIST AP, MASSTOR_LIST I));
extern MASSTOR_LIST SACROOT_IPRIMS ARGS((MASSTOR_LIST C_9_A, MASSTOR_LIST AP, MASSTOR_LIST I));
extern MASSTOR_LIST SACROOT_IPRIMU ARGS((MASSTOR_LIST C_10_A));
extern MASSTOR_LIST SACROOT_IPRIU ARGS((MASSTOR_LIST C_11_A));
extern MASSTOR_LIST SACROOT_IPRIUP ARGS((MASSTOR_LIST C_12_A));
extern void SACROOT_IPRRLS ARGS((MASSTOR_LIST A1, MASSTOR_LIST A2, MASSTOR_LIST L1, MASSTOR_LIST L2, MASSTOR_LIST *LS1, MASSTOR_LIST *LS2));
extern void SACROOT_IPRRS ARGS((MASSTOR_LIST A1, MASSTOR_LIST A2, MASSTOR_LIST I1, MASSTOR_LIST I2, MASSTOR_LIST *IS1, MASSTOR_LIST *IS2, MASSTOR_LIST *SL));
extern MASSTOR_LIST SACROOT_IPSFSD ARGS((MASSTOR_LIST RL, MASSTOR_LIST C_13_A));
extern MASSTOR_LIST SACROOT_IPSRM ARGS((MASSTOR_LIST C_14_A, MASSTOR_LIST I));
extern MASSTOR_LIST SACROOT_IPSRMS ARGS((MASSTOR_LIST C_15_A, MASSTOR_LIST I));
extern MASSTOR_LIST SACROOT_IPVCHT ARGS((MASSTOR_LIST C_16_A));
extern MASSTOR_LIST SACROOT_IUPRB ARGS((MASSTOR_LIST C_17_A));
extern MASSTOR_LIST SACROOT_IUPRLP ARGS((MASSTOR_LIST C_18_A));
extern MASSTOR_LIST SACROOT_IUPVAR ARGS((MASSTOR_LIST C_19_A));
extern MASSTOR_LIST SACROOT_IUPVSI ARGS((MASSTOR_LIST C_20_A, MASSTOR_LIST I));
extern MASSTOR_LIST SACROOT_RIB ARGS((MASSTOR_LIST RL, MASSTOR_LIST SL));
extern MASSTOR_LIST SACROOT_RILC ARGS((MASSTOR_LIST I, MASSTOR_LIST KL));
extern MASSTOR_LIST SACROOT_RINT ARGS((MASSTOR_LIST I));
extern void BEGIN_SACROOT();
