#define DEFINITION_SACRN

#ifndef DEFINITION_MASSTOR
#include "MASSTOR.h"
#endif

extern CHAR SACRN_rcsid[];
extern CHAR SACRN_copyright[];
extern MASSTOR_LIST SACRN_RIRNP ARGS((MASSTOR_LIST I, MASSTOR_LIST CL));
extern MASSTOR_LIST SACRN_RNABS ARGS((MASSTOR_LIST R));
extern MASSTOR_LIST SACRN_RNCEIL ARGS((MASSTOR_LIST RL));
extern MASSTOR_LIST SACRN_RNCOMP ARGS((MASSTOR_LIST R, MASSTOR_LIST S));
extern MASSTOR_LIST SACRN_RNDEN ARGS((MASSTOR_LIST R));
extern MASSTOR_LIST SACRN_RNDIF ARGS((MASSTOR_LIST R, MASSTOR_LIST S));
extern void SACRN_RNDWR ARGS((MASSTOR_LIST R, MASSTOR_LIST NL));
extern void SACRN_RNFCL2 ARGS((MASSTOR_LIST AL, MASSTOR_LIST *ML, MASSTOR_LIST *NL));
extern MASSTOR_LIST SACRN_RNFLOR ARGS((MASSTOR_LIST RL));
extern MASSTOR_LIST SACRN_RNINT ARGS((MASSTOR_LIST C_1_A));
extern MASSTOR_LIST SACRN_RNINV ARGS((MASSTOR_LIST R));
extern MASSTOR_LIST SACRN_RNNEG ARGS((MASSTOR_LIST R));
extern MASSTOR_LIST SACRN_RNNUM ARGS((MASSTOR_LIST R));
extern MASSTOR_LIST SACRN_RNPROD ARGS((MASSTOR_LIST R, MASSTOR_LIST S));
extern MASSTOR_LIST SACRN_RNP2 ARGS((MASSTOR_LIST KL));
extern MASSTOR_LIST SACRN_RNQ ARGS((MASSTOR_LIST R, MASSTOR_LIST S));
extern MASSTOR_LIST SACRN_RNRAND ARGS((MASSTOR_LIST NL));
extern MASSTOR_LIST SACRN_RNREAD ARGS(());
extern MASSTOR_LIST SACRN_RNRED ARGS((MASSTOR_LIST C_2_A, MASSTOR_LIST B));
extern MASSTOR_LIST SACRN_RNSIGN ARGS((MASSTOR_LIST R));
extern MASSTOR_LIST SACRN_RNSUM ARGS((MASSTOR_LIST R, MASSTOR_LIST S));
extern void SACRN_RNWRIT ARGS((MASSTOR_LIST R));
extern void BEGIN_SACRN();
