#define DEFINITION_SACRPOL

#ifndef DEFINITION_MASSTOR
#include "MASSTOR.h"
#endif

extern CHAR SACRPOL_rcsid[];
extern CHAR SACRPOL_copyright[];
extern MASSTOR_LIST SACRPOL_RPDIF ARGS((MASSTOR_LIST RL, MASSTOR_LIST C_1_A, MASSTOR_LIST B));
extern MASSTOR_LIST SACRPOL_RPEMV ARGS((MASSTOR_LIST RL, MASSTOR_LIST C_2_A, MASSTOR_LIST BL));
extern MASSTOR_LIST SACRPOL_RPFIP ARGS((MASSTOR_LIST RL, MASSTOR_LIST C_3_A));
extern MASSTOR_LIST SACRPOL_RPIMV ARGS((MASSTOR_LIST RL, MASSTOR_LIST C_4_A));
extern MASSTOR_LIST SACRPOL_RPNEG ARGS((MASSTOR_LIST RL, MASSTOR_LIST C_5_A));
extern MASSTOR_LIST SACRPOL_RPPROD ARGS((MASSTOR_LIST RL, MASSTOR_LIST C_6_A, MASSTOR_LIST B));
extern void SACRPOL_RPQR ARGS((MASSTOR_LIST RL, MASSTOR_LIST C_7_A, MASSTOR_LIST B, MASSTOR_LIST *Q, MASSTOR_LIST *R));
extern void SACRPOL_RPREAD ARGS((MASSTOR_LIST *RL, MASSTOR_LIST *C_8_A, MASSTOR_LIST *V));
extern MASSTOR_LIST SACRPOL_RPRNP ARGS((MASSTOR_LIST RL, MASSTOR_LIST AL, MASSTOR_LIST B));
extern MASSTOR_LIST SACRPOL_RPSUM ARGS((MASSTOR_LIST RL, MASSTOR_LIST C_9_A, MASSTOR_LIST B));
extern void SACRPOL_RPWRIT ARGS((MASSTOR_LIST RL, MASSTOR_LIST C_10_A, MASSTOR_LIST V));
extern void BEGIN_SACRPOL();
