#define DEFINITION_SACSYM

#ifndef DEFINITION_MASELEM
#include "MASELEM.h"
#endif

#ifndef DEFINITION_MASSTOR
#include "MASSTOR.h"
#endif

extern MASELEM_GAMMAINT SACSYM_COUNT, SACSYM_TRMAX;
extern MASSTOR_LIST SACSYM_SYMTB;
extern CHAR SACSYM_rcsid[];
extern CHAR SACSYM_copyright[];
extern MASSTOR_LIST SACSYM_ACOMP ARGS((MASSTOR_LIST C_1_A, MASSTOR_LIST B));
extern MASSTOR_LIST SACSYM_ACOMP1 ARGS((MASSTOR_LIST C_2_A, MASSTOR_LIST B));
extern MASSTOR_LIST SACSYM_ASSOC ARGS((MASSTOR_LIST AL, MASSTOR_LIST L));
extern MASSTOR_LIST SACSYM_ASSOCQ ARGS((MASSTOR_LIST AL, MASSTOR_LIST L));
extern MASSTOR_LIST SACSYM_ATTRIB ARGS((MASSTOR_LIST L));
extern MASSTOR_LIST SACSYM_EXPLOD ARGS((MASSTOR_LIST S));
extern MASSTOR_LIST SACSYM_ENTER ARGS((MASSTOR_LIST L));
extern MASSTOR_LIST SACSYM_GENSYM ARGS(());
extern MASSTOR_LIST SACSYM_GET ARGS((MASSTOR_LIST S, MASSTOR_LIST AL));
extern MASSTOR_LIST SACSYM_NAME ARGS((MASSTOR_LIST L));
extern MASSTOR_LIST SACSYM_PACK ARGS((MASSTOR_LIST L));
extern void SACSYM_PUT ARGS((MASSTOR_LIST S, MASSTOR_LIST AL, MASSTOR_LIST C_3_A));
extern void SACSYM_REMPRP ARGS((MASSTOR_LIST S, MASSTOR_LIST AL));
extern MASSTOR_LIST SACSYM_SMEMB ARGS((MASSTOR_LIST S, MASSTOR_LIST L));
extern MASSTOR_LIST SACSYM_SREAD ARGS(());
extern MASSTOR_LIST SACSYM_SREAD1 ARGS(());
extern void SACSYM_STCNT ARGS((MASSTOR_LIST T, MASSTOR_LIST *S, MASSTOR_LIST *P));
extern MASSTOR_LIST SACSYM_STINS ARGS((MASSTOR_LIST B));
extern MASSTOR_LIST SACSYM_STLST ARGS((MASSTOR_LIST T));
extern MASSTOR_LIST SACSYM_STLSTI ARGS((MASSTOR_LIST T));
extern MASSTOR_LIST SACSYM_STSRCH ARGS((MASSTOR_LIST T, MASSTOR_LIST AP));
extern void SACSYM_STWRT ARGS((MASSTOR_LIST T));
extern BOOLEAN SACSYM_SYMBOL ARGS((MASSTOR_LIST AP));
extern void SACSYM_SymSummary ARGS(());
extern void SACSYM_SYWRIT ARGS((MASSTOR_LIST S));
extern MASSTOR_LIST SACSYM_SUBLIS ARGS((MASSTOR_LIST L, MASSTOR_LIST C_4_A));
extern MASSTOR_LIST SACSYM_UREAD ARGS(());
extern void SACSYM_UWRITE ARGS((MASSTOR_LIST L));
extern void SACSYM_UWRIT1 ARGS((MASSTOR_LIST L));
extern void BEGIN_SACSYM();
