#define DEFINITION_SUBST

#ifndef DEFINITION_MASSTOR
#include "MASSTOR.h"
#endif

#ifndef DEFINITION_MASELEM
#include "MASELEM.h"
#endif

extern CHAR SUBST_rcsid[];
extern CHAR SUBST_copyright[];
extern void SUBST_SUBINF ARGS(());
extern MASSTOR_LIST SUBST_SUBSGR ARGS((MASELEM_GAMMAINT M));
extern void SUBST_SUBSGW ARGS((MASSTOR_LIST SG));
extern MASELEM_GAMMAINT SUBST_SUBORD ARGS((MASSTOR_LIST SG));
extern MASSTOR_LIST SUBST_SUBORP ARGS((MASSTOR_LIST SG, MASSTOR_LIST POL));
extern MASELEM_GAMMAINT SUBST_SUBSYM ARGS((MASSTOR_LIST SG, MASSTOR_LIST POL));
extern MASSTOR_LIST SUBST_SUBOPL ARGS((MASSTOR_LIST SG, MASSTOR_LIST ML));
extern MASSTOR_LIST SUBST_SUBCHK ARGS((MASSTOR_LIST SG, MASSTOR_LIST BASE, MASSTOR_LIST POL));
extern MASSTOR_LIST SUBST_SUBPOW ARGS((MASSTOR_LIST SG, MASELEM_GAMMAINT K));
extern void SUBST_SUBRED ARGS((MASSTOR_LIST SG, MASSTOR_LIST POL, MASSTOR_LIST *BASE, MASSTOR_LIST *BASEPOL, MASSTOR_LIST *REMPOL));
extern void BEGIN_SUBST();
