#define DEFINITION_SYMMFU

#ifndef DEFINITION_MASSTOR
#include "MASSTOR.h"
#endif

extern CHAR SYMMFU_rcsid[];
extern CHAR SYMMFU_copyright[];
extern void SYMMFU_DIRPSR ARGS((MASSTOR_LIST Q, MASSTOR_LIST PL, MASSTOR_LIST *P1, MASSTOR_LIST *P2));
extern void SYMMFU_DIRPSE ARGS((MASSTOR_LIST Q, MASSTOR_LIST U, MASSTOR_LIST *PL, MASSTOR_LIST *V));
extern MASSTOR_LIST SYMMFU_DIRPES ARGS((MASSTOR_LIST RL));
extern MASSTOR_LIST SYMMFU_EVASC ARGS((MASSTOR_LIST U));
extern void BEGIN_SYMMFU();
