#define DEFINITION_SYZFUNC

#ifndef DEFINITION_MASSTOR
#include "MASSTOR.h"
#endif

extern CHAR SYZFUNC_rcsid[];
extern CHAR SYZFUNC_copyright[];
extern void SYZFUNC_SPC ARGS((MASSTOR_LIST P1, MASSTOR_LIST P2, MASSTOR_LIST *SPFL, MASSTOR_LIST *SP));
extern void SYZFUNC_NLSPC ARGS((MASSTOR_LIST P1, MASSTOR_LIST P2, MASSTOR_LIST *SPFL, MASSTOR_LIST *SP, MASSTOR_LIST *T));
extern void SYZFUNC_SPCGB ARGS((MASSTOR_LIST GB, MASSTOR_LIST *SPFL, MASSTOR_LIST *SPL));
extern void SYZFUNC_NLSPCGB ARGS((MASSTOR_LIST GB, MASSTOR_LIST *SPFL, MASSTOR_LIST *SPL, MASSTOR_LIST *T));
extern void SYZFUNC_SPCEGB ARGS((MASSTOR_LIST GB, MASSTOR_LIST L, MASSTOR_LIST *SPFL, MASSTOR_LIST *SPL));
extern void SYZFUNC_NLSPCEGB ARGS((MASSTOR_LIST GB, MASSTOR_LIST L, MASSTOR_LIST *SPFL, MASSTOR_LIST *SPL, MASSTOR_LIST *T));
extern MASSTOR_LIST SYZFUNC_RCSP ARGS((MASSTOR_LIST GB, MASSTOR_LIST SPL));
extern MASSTOR_LIST SYZFUNC_RCSPR ARGS((MASSTOR_LIST PL, MASSTOR_LIST *SP));
extern MASSTOR_LIST SYZFUNC_NLRCSPR ARGS((MASSTOR_LIST PL, MASSTOR_LIST *SP, MASSTOR_LIST *T));
extern MASSTOR_LIST SYZFUNC_NLRCSP ARGS((MASSTOR_LIST GB, MASSTOR_LIST SPL, MASSTOR_LIST *T));
extern MASSTOR_LIST SYZFUNC_SYGB ARGS((MASSTOR_LIST SPFL, MASSTOR_LIST SPAK));
extern MASSTOR_LIST SYZFUNC_SYGBE ARGS((MASSTOR_LIST SPFL, MASSTOR_LIST SPAK));
extern MASSTOR_LIST SYZFUNC_MMULT ARGS((MASSTOR_LIST SY1, MASSTOR_LIST GBTM));
extern MASSTOR_LIST SYZFUNC_NLMMULT ARGS((MASSTOR_LIST SY1, MASSTOR_LIST GBTM, MASSTOR_LIST *T));
extern MASSTOR_LIST SYZFUNC_BGFUP ARGS((MASSTOR_LIST P1, MASSTOR_LIST P2, MASSTOR_LIST SP, MASSTOR_LIST SPN, MASSTOR_LIST SPFL, MASSTOR_LIST GB, MASSTOR_LIST SPAK, MASSTOR_LIST GBTM));
extern MASSTOR_LIST SYZFUNC_NLBGFUP ARGS((MASSTOR_LIST P1, MASSTOR_LIST P2, MASSTOR_LIST SP, MASSTOR_LIST SPN, MASSTOR_LIST SPFL, MASSTOR_LIST GB, MASSTOR_LIST SPAK, MASSTOR_LIST GBTM, MASSTOR_LIST *T));
extern MASSTOR_LIST SYZFUNC_DGBRED ARGS((MASSTOR_LIST GB, MASSTOR_LIST GBTM, MASSTOR_LIST *SY));
extern MASSTOR_LIST SYZFUNC_NLDGBRED ARGS((MASSTOR_LIST GB, MASSTOR_LIST GBTM, MASSTOR_LIST *SY, MASSTOR_LIST *T));
extern MASSTOR_LIST SYZFUNC_SYONP ARGS((MASSTOR_LIST GB1, MASSTOR_LIST GB2, MASSTOR_LIST GBTM));
extern MASSTOR_LIST SYZFUNC_NLSYONP ARGS((MASSTOR_LIST GB1, MASSTOR_LIST GB2, MASSTOR_LIST GBTM, MASSTOR_LIST *T));
extern MASSTOR_LIST SYZFUNC_DINPQ ARGS((MASSTOR_LIST P1, MASSTOR_LIST P2, MASSTOR_LIST *T));
extern MASSTOR_LIST SYZFUNC_PLMULT ARGS((MASSTOR_LIST SY, MASSTOR_LIST PL));
extern MASSTOR_LIST SYZFUNC_NLPLMULT ARGS((MASSTOR_LIST SY, MASSTOR_LIST PL, MASSTOR_LIST *T));
extern void BEGIN_SYZFUNC();
