#define DEFINITION_SYZGB

#ifndef DEFINITION_MASSTOR
#include "MASSTOR.h"
#endif

extern CHAR SYZGB_rcsid[];
extern CHAR SYZGB_copyright[];
extern MASSTOR_LIST SYZGB_MGB ARGS((MASSTOR_LIST PM, MASSTOR_LIST SANZ));
extern MASSTOR_LIST SYZGB_NLMGB ARGS((MASSTOR_LIST PM, MASSTOR_LIST SANZ, MASSTOR_LIST *T));
extern MASSTOR_LIST SYZGB_GBE ARGS((MASSTOR_LIST PL, MASSTOR_LIST SANZ, MASSTOR_LIST L));
extern MASSTOR_LIST SYZGB_GBF ARGS((MASSTOR_LIST PL, MASSTOR_LIST SANZ, MASSTOR_LIST *GBTM));
extern MASSTOR_LIST SYZGB_GBEF ARGS((MASSTOR_LIST PL, MASSTOR_LIST SANZ, MASSTOR_LIST L, MASSTOR_LIST *GBTM));
extern MASSTOR_LIST SYZGB_NLGBE ARGS((MASSTOR_LIST PL, MASSTOR_LIST SANZ, MASSTOR_LIST L, MASSTOR_LIST *T));
extern MASSTOR_LIST SYZGB_NLGBF ARGS((MASSTOR_LIST PL, MASSTOR_LIST SANZ, MASSTOR_LIST *GBTM, MASSTOR_LIST *T));
extern MASSTOR_LIST SYZGB_NLGBEF ARGS((MASSTOR_LIST PL, MASSTOR_LIST SANZ, MASSTOR_LIST L, MASSTOR_LIST *GBTM, MASSTOR_LIST *T));
extern void BEGIN_SYZGB();
