#define DEFINITION_SYZHLP

#ifndef DEFINITION_MASSTOR
#include "MASSTOR.h"
#endif

extern CHAR SYZHLP_rcsid[];
extern CHAR SYZHLP_copyright[];
extern void SYZHLP_ALFA ARGS((MASSTOR_LIST L));
extern void SYZHLP_ALFRA ARGS((MASSTOR_LIST L));
extern MASSTOR_LIST SYZHLP_ADDPPOS ARGS((MASSTOR_LIST PL, MASSTOR_LIST P, MASSTOR_LIST POS));
extern void SYZHLP_PLWR ARGS((MASSTOR_LIST PL, MASSTOR_LIST VL));
extern void SYZHLP_PMWR ARGS((MASSTOR_LIST PM, MASSTOR_LIST VL));
extern MASSTOR_LIST SYZHLP_APP0 ARGS((MASSTOR_LIST PM));
extern MASSTOR_LIST SYZHLP_ADDLAST ARGS((MASSTOR_LIST P, MASSTOR_LIST PL));
extern MASSTOR_LIST SYZHLP_POS ARGS((MASSTOR_LIST P, MASSTOR_LIST PL));
extern MASSTOR_LIST SYZHLP_POL ARGS((MASSTOR_LIST PL, MASSTOR_LIST POS));
extern MASSTOR_LIST SYZHLP_GENPOSV ARGS((MASSTOR_LIST GB, MASSTOR_LIST GBR));
extern MASSTOR_LIST SYZHLP_INSPOSV ARGS((MASSTOR_LIST PM, MASSTOR_LIST POSV));
extern MASSTOR_LIST SYZHLP_EXPPL ARGS((MASSTOR_LIST P, MASSTOR_LIST GB));
extern MASSTOR_LIST SYZHLP_EX0PL ARGS((MASSTOR_LIST PL));
extern MASSTOR_LIST SYZHLP_EVF ARGS((MASSTOR_LIST EV, MASSTOR_LIST L));
extern MASSTOR_LIST SYZHLP_EVR ARGS((MASSTOR_LIST PM, MASSTOR_LIST L));
extern MASSTOR_LIST SYZHLP_MREAD ARGS((MASSTOR_LIST VL));
extern MASSTOR_LIST SYZHLP_NMREAD ARGS((MASSTOR_LIST VL, MASSTOR_LIST T));
extern MASSTOR_LIST SYZHLP_TA ARGS((MASSTOR_LIST L, MASSTOR_LIST T));
extern MASSTOR_LIST SYZHLP_TR ARGS((MASSTOR_LIST L, MASSTOR_LIST T));
extern void SYZHLP_NEXTPAIR ARGS((MASSTOR_LIST *P1, MASSTOR_LIST *P2, MASSTOR_LIST *PPL));
extern MASSTOR_LIST SYZHLP_EVT ARGS((MASSTOR_LIST P1, MASSTOR_LIST P2, MASSTOR_LIST L));
extern void SYZHLP_WRS1 ARGS((MASSTOR_LIST SZ, MASSTOR_LIST C1, MASSTOR_LIST C2, MASSTOR_LIST C3));
extern void SYZHLP_WRS2 ARGS((MASSTOR_LIST SZ, MASSTOR_LIST C1, MASSTOR_LIST TW1, MASSTOR_LIST C2, MASSTOR_LIST SPN, MASSTOR_LIST C3));
extern MASSTOR_LIST SYZHLP_EVL ARGS((MASSTOR_LIST PM));
extern void SYZHLP_NORMF ARGS((MASSTOR_LIST *PL, MASSTOR_LIST *GBTM));
extern MASSTOR_LIST SYZHLP_GBTMRED ARGS((MASSTOR_LIST GBTM, MASSTOR_LIST POSV));
extern MASSTOR_LIST SYZHLP_MTPLV ARGS((MASSTOR_LIST PM, MASSTOR_LIST *L));
extern MASSTOR_LIST SYZHLP_PLVTM ARGS((MASSTOR_LIST PL, MASSTOR_LIST L));
extern MASSTOR_LIST SYZHLP_MTPLH ARGS((MASSTOR_LIST PM, MASSTOR_LIST *L));
extern MASSTOR_LIST SYZHLP_PLHTP ARGS((MASSTOR_LIST PL));
extern MASSTOR_LIST SYZHLP_VMADD ARGS((MASSTOR_LIST PM));
extern void BEGIN_SYZHLP();
