#!/bin/bash
#
# Skript zum Übersetzen 
#
# (c) Gunter Mueller   v. 0.1  Januar 2017

export MOCKA=/usr/local/mocka
#export MOCKAM2="-d  $MURUS/m2bin -CcallsMocka"
export MOCKAM2="-d  ../maskern/m2bin "
export MOCKALINK="-lpthread -L/usr/X11R6/lib -lX11"




B=./m2bin
rm -f $B/* # alte Kompilate werden entfernt


# Definition Modules :
for d in  ALDPARSE.def  MASLISPU.def  MASREP.def   MASSYM2.def  MODVAR.def   SACSYM.def \
MASLISP.def   MASPARSE.def  MASSPEC.def  MASSYM.def   SACSYM2.def
do
 echo $d
 m=${d%.def}
 m2 -s $m
done

# Implementation Modules: 
for d in  ALDPARSE.mod  MASLISPU.mod  MASREP.mod   MASSYM2.mod  MODVAR.mod   SACSYM.mod \
MASLISP.mod   MASPARSE.mod  MASSPEC.mod  MASSYM.mod   SACSYM2.mod
do
 echo $d
 m=${d%.mod}
 m2 -c $m
done

