#!/bin/bash
#
# Skript zum Übersetzen 
#
# (c) Gunter Mueller   v. 0.1  Januar 2017

export MOCKA=/usr/local/mocka
#export MOCKAM2="-d  $MURUS/m2bin -CcallsMocka"
export MOCKAM2="-d  ../maskern/m2bin -d ../masarith/m2bin -d ../masdom/m2bin -d ../masmodul/m2bin"
export MOCKALINK="-lpthread -L/usr/X11R6/lib -lX11"




B=./m2bin
rm -f $B/* # alte Kompilate werden entfernt


# Definition Modules :
for d in DIPC.def  DIPIPOL.def  DIPRNPOL.def  SACDPOL.def  SACMPOL.def  SACRPOL.def \
DIPI.def  DIPRN.def    DIPTOO.def    SACIPOL.def  SACPOL.def
do
 echo $d
 m=${d%.def}
 m2 -s $m
done

# Implementation Modules: 
for d in DIPC.mod  DIPIPOL.mod  DIPRNPOL.mod  SACDPOL.mod  SACMPOL.mod  SACRPOL.mod \
DIPI.mod  DIPRN.mod    DIPTOO.mod    SACIPOL.mod  SACPOL.mod
do
 echo $d
 m=${d%.mod}
 m2 -c $m
done

