#!/bin/bash
#
# Skript zum Übersetzen 
#
# (c) Gunter Mueller   v. 0.1  Januar 2017

export MOCKA=/usr/local/mocka
#export MOCKAM2="-d  $MURUS/m2bin -CcallsMocka"
export MOCKAM2="-d  ../maskern/m2bin "
export MOCKALINK="-lpthread -L/usr/X11R6/lib -lX11"




B=./m2bin
rm -f $B/* # alte Kompilate werden entfernt


# Definition Modules :
for d in MASLOG.def  MLDEMO.def  MLOGBASE.def  MLOGIO.def  PQBASE.def  PQSMPL.def  RQEPRRC.def  TFORM.def
do
 echo $d
 m=${d%.def}
 m2 -s $m
done

# Implementation Modules: 
for d in  MASLOG.mod  MLDEMO.mod  MLOGBASE.mod  MLOGIO.mod  PQBASE.mod  PQSMPL.mod  RQEPRRC.mod  TFORM.mod
do
 echo $d
 m=${d%.mod}
 m2 -c $m
done

