#!/bin/bash
#
# Skript zum Übersetzen 
#
# (c) Gunter Mueller   v. 0.1  Januar 2017

export MOCKA=/usr/local/mocka
#export MOCKAM2="-d  $MURUS/m2bin -CcallsMocka"
export MOCKAM2="-d  ../maskern/m2bin -d ../maslisp/m2bin"
export MOCKALINK="-lpthread -L/usr/X11R6/lib -lX11"




B=./m2bin
rm -f $B/* # alte Kompilate werden entfernt


# Definition Modules :
for d in ADEXTRA.def  DIPCJ.def  DIPDCIB.def  DIPIB.def  DIPIIB.def  DIPRNIB.def
do
 echo $d
 m=${d%.def}
 m2 -s $m
done

# Implementation Modules: 
for d in  ADEXTRA.mod  DIPCJ.mod  DIPDCIB.mod  DIPIB.mod  DIPIIB.mod  DIPRNIB.mod
do
 echo $d
 m=${d%.mod}
 m2 -c $m
done

