#!/bin/bash
#
# Skript zum Übersetzen 
#
# (c) Gunter Mueller   v. 0.1  Januar 2017

export MOCKA=/usr/local/mocka
#export MOCKAM2="-d  $MURUS/m2bin -CcallsMocka"
export MOCKAM2="-d  ../maskern/m2bin -d ../maslisp/m2bin -d ../maspoly/m2bin "
export MOCKALINK="-lpthread -L/usr/X11R6/lib -lX11"




B=./m2bin
rm -f $B/* # alte Kompilate werden entfernt


# Definition Modules :
for d in  MASADOM.def ADTOOLS.def  CGBFUNC.def  CGBSYS.def   DIPDCGB.def  DIPTOOLS.def  DOMC.def   DOMIP.def  DOMO.def   DOMRN.def \
CGBAPPL.def  CGBMAIN.def  DIPADOM.def  DIPDDGB.def  DOMAF.def     DOMFF.def  DOMMD.def  DOMQ.def   DOMRP.def \
CGBDSTR.def  CGBMISC.def  DIPAGB.def   DIPGB.def    DOMAPF.def    DOMI.def   DOMMI.def  DOMRF.def  
do
 echo $d
 m=${d%.def}
 m2 -s $m
done

# Implementation Modules: 
for d in  ADTOOLS.mod  DIPDCGB.mod  DIPTOOLS.mod  DOMC.mod   DOMIP.mod  DOMO.mod   DOMRN.mod \
DIPADOM.mod  DIPDDGB.mod  DOMAF.mod     DOMFF.mod  DOMMD.mod  DOMQ.mod   DOMRP.mod \
DIPAGB.mod   DIPGB.mod    DOMAPF.mod    DOMI.mod   DOMMI.mod  DOMRF.mod  MASADOM.mod
do
 echo $d
 m=${d%.mod}
 m2 -c $m
done

