#!/bin/bash
#
# Skript zum Übersetzen 
#
# (c) Gunter Mueller   v. 0.1  Januar 2017

export MOCKA=/usr/local/mocka
#export MOCKAM2="-d  $MURUS/m2bin -CcallsMocka"
export MOCKAM2="-d  ../maskern/m2bin "
export MOCKALINK="-lpthread -L/usr/X11R6/lib -lX11"




B=./m2bin
rm -f $B/* # alte Kompilate werden entfernt


# Definition Modules :
for d in  DIPDEC0.def  DIPGCD.def    DIPIDGB.def  DIPRF.def    DIPROOT.def  MASFF.def    MASUGB.def \
DIPDIM.def   DIPIDEAL.def  DIPIGB.def   DIPRNGB.def  DIPZ.def     MASPGCD.def
do
 echo $d
 m=${d%.def}
 m2 -s $m
done

# Implementation Modules: 
for d in DIPDEC0.mod  DIPGCD.mod    DIPIDGB.mod  DIPRF.mod    DIPROOT.mod  MASFF.mod    MASUGB.mod \
DIPDIM.mod   DIPIDEAL.mod  DIPIGB.mod   DIPRNGB.mod  DIPZ.mod     MASPGCD.mod
do
 echo $d
 m=${d%.mod}
 m2 -c $m
done

