#!/bin/bash
#
# Skript zum Übersetzen 
#
# (c) Gunter Mueller   v. 0.1  Januar 2017

export MOCKA=/usr/local/mocka
#export MOCKAM2="-d  $MURUS/m2bin -CcallsMocka"
export MOCKAM2="-d  ../maskern/m2bin "
export MOCKALINK="-lpthread -L/usr/X11R6/lib -lX11"




B=./m2bin
rm -f $B/* # alte Kompilate werden entfernt


# Definition Modules :
for d in MASAPF.def  MASCOMB.def  MASI.def  MASQ.def   MASSET.def   SACCOMB.def  SACI.def  SACPRIM.def  SACSET.def \
MASC.def    MASF.def     MASO.def  MASRN.def  MathLib.def  SACD.def     SACM.def  SACRN.def
do
 echo $d
 m=${d%.def}
 m2 -s $m
done

# Implementation Modules: 
for d in  MASAPF.mod  MASCOMB.mod  MASI.mod  MASQ.mod   MASSET.mod   SACCOMB.mod  SACI.mod  SACPRIM.mod  SACSET.mod \
MASC.mod    MASF.mod     MASO.mod  MASRN.mod  MathLib.mod  SACD.mod     SACM.mod  SACRN.mod
do
 echo $d
 m=${d%.mod}
 m2 -c $m
done

