#!/bin/bash
#
# Skript zum Übersetzen 
#
# (c) Gunter Mueller   v. 0.1  Januar 2017

export MOCKA=/usr/local/mocka
#export MOCKAM2="-d  $MURUS/m2bin -CcallsMocka"
export MOCKAM2="-d  ../maskern/m2bin "
export MOCKALINK="-lpthread -L/usr/X11R6/lib -lX11"


B=./m2bin
rm -f $B/* # alte Kompilate werden entfernt


# alle in C geschriebenen Moduln werden mit dem gcc übersetzt:
## NOT YET : maskpathsea.def masreadline.def  MASCONF.def massig.def 
for d in  MASELEM.def MASSTOR.def MASBIOSU.def SACLIST.def \
LISTTOOLS.def  clock.def    Portab.def   setjmp.def MASERR.def \
MASBIOS.def    MASmtc.def       MASSIGNAL.def    SACBIOS.def  SYSINFO.def 
do
 echo $d
 m=${d%.def}
 m2 -s $m
done

# alle in Assembler geschriebenen Moduln werden mit dem as übersetzt:
## NOT YET : MASSIGNAL.mod massig.mod MASERR.mod  MASBIOS.mod
for d in  LISTTOOLS.mod  MASBIOSU.mod  SACBIOS.mod  setjmp.mod \
 MASELEM.mod   Portab.mod     SACLIST.mod  SYSINFO.mod
do
 echo $d
 m=${d%.mod}
 m2 -c $m
done

