#!/bin/bash
#
# Skript zum Übersetzen 
#
# (c) Gunter Mueller   v. 0.1  Januar 2017

export MOCKA=/usr/local/mocka
#export MOCKAM2="-d  $MURUS/m2bin -CcallsMocka"
export MOCKAM2="-d  ../maskern/m2bin "
export MOCKALINK="-lpthread -L/usr/X11R6/lib -lX11"




B=./m2bin
rm -f $B/* # alte Kompilate werden entfernt


# Definition Modules :
for d in  MASLOADA.def  MASLOADD.def  MASLOADG.def  MASLOADM.def  MASU.def      MLMLDEMO.def \
MASLOADB.def  MASLOAD.def   MASLOADJ.def  MASLOADQ.def  MASYMDIP.def  MLPQSMPL.def \
MASLOADC.def  MASLOADE.def  MASLOADL.def  MASLOADS.def  MLMASLOG.def
do
 echo $d
 m=${d%.def}
 m2 -s $m
done

# Implementation Modules: 
for d in  MASLOADA.mod  MASLOADD.mod  MASLOADJ.mod  MASLOAD.mod   MAS.mod       MLMASLOG.mod \
MASLOADB.mod  MASLOADE.mod  MASLOADL.mod  MASLOADQ.mod  MASU.mod      MLMLDEMO.mod \
MASLOADC.mod  MASLOADG.mod  MASLOADM.mod  MASLOADS.mod  MASYMDIP.mod  MLPQSMPL.mod
do
 echo $d
 m=${d%.mod}
 m2 -c $m
done

